Fab-O-Matic: fabomatic::Buffer Class Reference
fabomatic::Buffer Class Reference
#include <BufferedMsg.hpp>
Public Member Functions
auto push_back (const BufferedMsg &message) -> void
auto push_front (const BufferedMsg &message) -> void
auto getMessage () -> const BufferedMsg
auto count () const -> size_t
auto toJson (JsonDocument &doc, const std::string &element_name) const -> void
auto hasChanged () const -> bool
auto setChanged (bool new_value) -> void
Static Public Member Functions
static auto fromJsonElement (const JsonObject &json_obj) -> std::optional< Buffer >
Static Public Attributes
static constexpr auto MAX_MESSAGES = 40
Private Attributes
std::deque< BufferedMsg > msg_queue
bool has_changed {true}
Static Private Attributes
static constexpr auto MAGIC_NUMBER = 1
Detailed Description
Definition at line 26 of file BufferedMsg.hpp.
Member Function Documentation
count()
auto fabomatic::Buffer::count () const -> size_t
Definition at line 62 of file BufferedMsg.cpp.
  {
    return msg_queue.size();
  }
References msg_queue.
Referenced by fabomatic::FabBackend::hasBufferedMsg(), fabomatic::tests::test_buffered_msg(), and fabomatic::tests::test_deserialization().
fromJsonElement()
auto fabomatic::Buffer::fromJsonElement (const JsonObject & json_obj) -> std::optional<Buffer> static
Definition at line 82 of file BufferedMsg.cpp.
  {
    Buffer buff;
    // Check that the version is the same
    auto version = json_obj["VERSION"].as<unsigned int>();
    if (version != MAGIC_NUMBER)
    {
      ESP_LOGD(TAG, "Buffer::fromJson() : wrong version number (%d, expected %d)", version, MAGIC_NUMBER);
      return std::nullopt;
    }
    for (const auto &elem : json_obj["messages"].as<JsonArray>())
    {
      const auto &msg = BufferedMsg{elem["msg"].as<std::string>(),
                                    elem["tp"].as<std::string>(),
                                    elem["wait"].as<bool>()};
      buff.push_back(msg);
    }
    ESP_LOGD(TAG, "Buffer::fromJsonElement() : data loaded successfully");
    return buff;
  }
References push_back(), and TAG.
Referenced by fabomatic::SavedConfig::fromJsonDocument(), and fabomatic::tests::test_deserialization().
getMessage()
auto fabomatic::Buffer::getMessage () -> const BufferedMsg
Definition at line 47 of file BufferedMsg.cpp.
  {
    if (msg_queue.size() == 0)
    {
      ESP_LOGE(TAG, "Calling getMessage() on empty queue!");
      return {"", "", false};
    }
    auto elem = msg_queue.front();
    msg_queue.pop_front();
    has_changed = true;
    return elem;
  }
References TAG.
Referenced by fabomatic::tests::test_buffered_msg(), and fabomatic::tests::test_deserialization().
hasChanged()
auto fabomatic::Buffer::hasChanged () const -> bool inline
Definition at line 39 of file BufferedMsg.hpp.
{ return has_changed; };
References has_changed.
Referenced by fabomatic::tests::test_buffered_msg().
push_back()
auto fabomatic::Buffer::push_back (const BufferedMsg & message) -> void
Definition at line 9 of file BufferedMsg.cpp.
  {
    if constexpr (conf::debug::ENABLE_BUFFERING)
    {
      msg_queue.push_back(message);
      if (msg_queue.size() > MAX_MESSAGES)
      {
        msg_queue.pop_front();
        ESP_LOGW(TAG, "Removing first message from the buffer");
      }
      has_changed = true;
      ESP_LOGI(TAG, "Buffered %s on %s, %lu messages queued",
               message.mqtt_message.c_str(),
               message.mqtt_topic.c_str(),
               msg_queue.size());
    }
  }
References fabomatic::conf::debug::ENABLE_BUFFERING, and TAG.
Referenced by fromJsonElement(), fabomatic::FabBackend::processQuery(), and fabomatic::tests::test_buffered_msg().
push_front()
auto fabomatic::Buffer::push_front (const BufferedMsg & message) -> void
Definition at line 28 of file BufferedMsg.cpp.
  {
    if constexpr (conf::debug::ENABLE_BUFFERING)
    {
      msg_queue.push_front(message);
      if (msg_queue.size() > MAX_MESSAGES)
      {
        msg_queue.pop_back();
        ESP_LOGW(TAG, "Removing last message from the buffer");
      }
      has_changed = true;
      ESP_LOGI(TAG, "Buffered %s on %s, %lu messages queued",
               message.mqtt_message.c_str(),
               message.mqtt_topic.c_str(),
               msg_queue.size());
    }
  }
References fabomatic::conf::debug::ENABLE_BUFFERING, and TAG.
Referenced by fabomatic::tests::test_buffered_msg().
setChanged()
auto fabomatic::Buffer::setChanged (bool new_value) -> void inline
Definition at line 40 of file BufferedMsg.hpp.
{ has_changed = new_value; };
References has_changed.
Referenced by fabomatic::tests::test_buffered_msg().
toJson()
auto fabomatic::Buffer::toJson (JsonDocument & doc, const std::string & element_name) const -> void
Definition at line 67 of file BufferedMsg.cpp.
  {
    auto obj = doc.createNestedObject(element_name);
    obj["VERSION"] = MAGIC_NUMBER;
    auto json_elem = obj.createNestedArray("messages");
    for (auto elem = msg_queue.begin(); elem != msg_queue.end(); elem++)
    {
      auto obj_msg = json_elem.createNestedObject();
      obj_msg["tp"] = elem->mqtt_topic;
      obj_msg["msg"] = elem->mqtt_message;
      obj_msg["wait"] = elem->wait_for_answer;
    }
  }
Referenced by fabomatic::tests::test_deserialization(), and fabomatic::SavedConfig::toJsonDocument().
Field Documentation
has_changed
bool fabomatic::Buffer::has_changed {true} private
Definition at line 30 of file BufferedMsg.hpp.
{true};
Referenced by hasChanged(), and setChanged().
MAGIC_NUMBER
constexpr auto fabomatic::Buffer::MAGIC_NUMBER = 1 static constexpr private
Definition at line 31 of file BufferedMsg.hpp.
MAX_MESSAGES
constexpr auto fabomatic::Buffer::MAX_MESSAGES = 40 static constexpr
Definition at line 43 of file BufferedMsg.hpp.
Referenced by fabomatic::tests::test_buffered_msg().
msg_queue
std::deque<BufferedMsg> fabomatic::Buffer::msg_queue private
Definition at line 29 of file BufferedMsg.hpp.
Referenced by count().
The documentation for this class was generated from the following files:
BufferedMsg.hpp
BufferedMsg.cpp