Fab-O-Matic: fabomatic::MockMrfc522 Class Reference
fabomatic::MockMrfc522 Class Reference
This class implements a Mrfc522 with settable tag ID in order to allow simulation.
#include <MockMrfc522.hpp>
Classes
struct UidDriver
Public Member Functions
constexpr MockMrfc522 ()
auto PICC_IsNewCardPresent () -> bool
auto PICC_ReadCardSerial () -> bool
auto reset () -> void
auto PCD_Init () -> bool
auto PICC_WakeupA (byte *bufferATQA, byte &bufferSize) -> bool
auto PCD_PerformSelfTest () -> bool
auto getDriverUid () const -> MockMrfc522::UidDriver
auto PCD_SetAntennaGain (MFRC522Constants::PCD_RxGain gain) -> void
auto PCD_DumpVersionToSerial () -> void
auto setUid (const std::optional< card::uid_t > &uid, const std::optional< std::chrono::milliseconds > &max_delay) -> void
auto resetUid () -> void
Static Public Attributes
static constexpr auto RxGainMax = MFRC522::PCD_RxGain::RxGain_max
Private Member Functions
std::optional< card::uid_t > getSimulatedUid () const
Private Attributes
std::optional< card::uid_t > uid {std::nullopt}
std::optional< std::chrono::time_point< std::chrono::system_clock > > stop_uid_simulate_time {std::nullopt}
Detailed Description
This class implements a Mrfc522 with settable tag ID in order to allow simulation.
Definition at line 18 of file MockMrfc522.hpp.
Constructor & Destructor Documentation
MockMrfc522()
constexpr fabomatic::MockMrfc522::MockMrfc522 () inline constexpr
Definition at line 35 of file MockMrfc522.hpp.
{};
Member Function Documentation
getDriverUid()
auto fabomatic::MockMrfc522::getDriverUid () const -> MockMrfc522::UidDriver
Definition at line 7 of file MockMrfc522.cpp.
  {
    UidDriver retVal{};
    if (getSimulatedUid().has_value())
    {
      retVal.size = sizeof(uid.value());
      const auto arr_uid = card::to_array(uid.value());
      std::copy(arr_uid.begin(), arr_uid.end(), retVal.uidByte.begin());
      retVal.sak = 1;
    }
    return retVal;
  }
References getSimulatedUid(), fabomatic::MockMrfc522::UidDriver::size, fabomatic::card::to_array(), and uid.
getSimulatedUid()
auto fabomatic::MockMrfc522::getSimulatedUid () const private
Definition at line 62 of file MockMrfc522.cpp.
  {
    if (stop_uid_simulate_time.has_value() && std::chrono::system_clock::now() > stop_uid_simulate_time.value())
    {
      return std::nullopt;
    }
    return uid;
  }
References stop_uid_simulate_time, and uid.
Referenced by getDriverUid().
PCD_DumpVersionToSerial()
auto fabomatic::MockMrfc522::PCD_DumpVersionToSerial () -> void
Definition at line 41 of file MockMrfc522.cpp.
{}
PCD_Init()
auto fabomatic::MockMrfc522::PCD_Init () -> bool
Definition at line 26 of file MockMrfc522.cpp.
{ return true; }
PCD_PerformSelfTest()
auto fabomatic::MockMrfc522::PCD_PerformSelfTest () -> bool
Definition at line 37 of file MockMrfc522.cpp.
{ return true; }
PCD_SetAntennaGain()
auto fabomatic::MockMrfc522::PCD_SetAntennaGain (MFRC522Constants::PCD_RxGain gain) -> void
Definition at line 39 of file MockMrfc522.cpp.
{}
PICC_IsNewCardPresent()
auto fabomatic::MockMrfc522::PICC_IsNewCardPresent () -> bool
Definition at line 20 of file MockMrfc522.cpp.
{ return getSimulatedUid().has_value(); }
PICC_ReadCardSerial()
auto fabomatic::MockMrfc522::PICC_ReadCardSerial () -> bool
Definition at line 22 of file MockMrfc522.cpp.
{ return getSimulatedUid().has_value(); }
PICC_WakeupA()
auto fabomatic::MockMrfc522::PICC_WakeupA (byte * bufferATQA, byte & bufferSize) -> bool
Definition at line 28 of file MockMrfc522.cpp.
  {
    if (getSimulatedUid().has_value())
    {
      return true;
    }
    return false;
  }
reset()
void fabomatic::MockMrfc522::reset () -> void
Definition at line 24 of file MockMrfc522.cpp.
{ uid = std::nullopt; }
References uid.
resetUid()
auto fabomatic::MockMrfc522::resetUid () -> void
Definition at line 56 of file MockMrfc522.cpp.
  {
    uid = std::nullopt;
    stop_uid_simulate_time = std::nullopt;
  }
Referenced by fabomatic::tests::simulate_rfid_card().
setUid()
auto fabomatic::MockMrfc522::setUid (const std::optional< card::uid_t > & uid, const std::optional< std::chrono::milliseconds > & max_delay) -> void
Definition at line 43 of file MockMrfc522.cpp.
  {
    this->uid = uid;
    if (max_delay.has_value())
    {
      stop_uid_simulate_time = std::chrono::system_clock::now() + max_delay.value();
    }
    else
    {
      stop_uid_simulate_time = std::nullopt;
    }
  }
Referenced by fabomatic::tests::simulate_rfid_card().
Member Data Documentation
RxGainMax
constexpr auto fabomatic::MockMrfc522::RxGainMax = MFRC522::PCD_RxGain::RxGain_max static constexpr
Definition at line 51 of file MockMrfc522.hpp.
stop_uid_simulate_time
std::optional<std::chrono::time_point<std::chrono::system_clock> > fabomatic::MockMrfc522::stop_uid_simulate_time {std::nullopt} private
Definition at line 22 of file MockMrfc522.hpp.
{std::nullopt};
Referenced by getSimulatedUid().
uid
std::optional<card::uid_t> fabomatic::MockMrfc522::uid {std::nullopt} private
Definition at line 21 of file MockMrfc522.hpp.
{std::nullopt};
Referenced by getDriverUid(), getSimulatedUid(), and reset().
The documentation for this class was generated from the following files:
MockMrfc522.hpp
MockMrfc522.cpp