Fab-O-Matic: fabomatic::LCDWrapper Class Reference
fabomatic::LCDWrapper Class Reference
LCD display wrapper.
#include <LCDWrapper.hpp>
Public Types
using DisplayBuffer = std::array< std::array< char, conf::lcd::COLS >, conf::lcd::ROWS >
Public Member Functions
LCDWrapper (const pins_config::lcd_config &config)
auto begin () -> bool
auto clear () -> void
auto showConnection (bool show) -> void
auto showPower (bool show) -> void
auto setRow (uint8_t row, const std::string_view &text) -> void
auto update (const BoardInfo &boardinfo, bool forced=false) -> void
auto convertSecondsToHHMMSS (std::chrono::seconds duration) const -> const std::string
Private Member Functions
auto backlightOn () const -> void
auto backlightOff () const -> void
auto prettyPrint (const DisplayBuffer &buffer, const BoardInfo &bi) const -> void
Debug utility to print in the console the current buffer contents.
auto createChar (uint8_t char_idx, const std::array< uint8_t, HEIGHT_PX > &values) -> void
auto needsUpdate (const BoardInfo &bi) const -> bool
Checks if the LCD buffer has changed since last write to the LCD, or forced update has been requested.
Private Attributes
const pins_config::lcd_config & config
LiquidCrystal lcd
bool show_connection_status
bool show_power_status
bool forceUpdate
DisplayBuffer buffer
DisplayBuffer current
BoardInfo boardInfo
Static Private Attributes
static constexpr auto HEIGHT_PX = 8
static constexpr auto CHAR_ANTENNA = 0
static constexpr auto CHAR_CONNECTION = 1
static constexpr auto CHAR_NO_CONNECTION = 2
static constexpr auto CHAR_POWERED_ON = 3
static constexpr auto CHAR_POWERED_OFF = 4
static constexpr auto CHAR_POWERING_OFF = 5
static constexpr std::array< uint8_t, HEIGHT_PX > antenna_char {0x15, 0x0E, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04}
static constexpr std::array< uint8_t, HEIGHT_PX > connection_char {0x00, 0x00, 0x01, 0x01, 0x05, 0x05, 0x15, 0x15}
static constexpr std::array< uint8_t, HEIGHT_PX > noconnection_char {0x00, 0x00, 0x11, 0x0A, 0x04, 0x0A, 0x11, 0x00}
static constexpr std::array< uint8_t, HEIGHT_PX > powered_on_char {0x04, 0x04, 0x04, 0x1f, 0x1f, 0x1f, 0x0a, 0x0a}
static constexpr std::array< uint8_t, HEIGHT_PX > powered_off_char {0x0a, 0x04, 0x0a, 0x00, 0x1f, 0x1f, 0x0a, 0x0a}
static constexpr std::array< uint8_t, HEIGHT_PX > powering_off_char {0x0e, 0x15, 0x15, 0x15, 0x17, 0x11, 0x11, 0x0e}
Detailed Description
LCD display wrapper.
Definition at line 14 of file LCDWrapper.hpp.
Member Typedef Documentation
DisplayBuffer
using fabomatic::LCDWrapper::DisplayBuffer = std::array<std::array<char, conf::lcd::COLS>, conf::lcd::ROWS>
Definition at line 19 of file LCDWrapper.hpp.
Constructor & Destructor Documentation
LCDWrapper()
fabomatic::LCDWrapper::LCDWrapper (const pins_config::lcd_config & config)
Definition at line 12 of file LCDWrapper.cpp.
                                                          : config(conf),
                                                                lcd(config.rs_pin, config.en_pin, config.d0_pin, config.d1_pin, config.d2_pin, config.d3_pin),
                                                                show_connection_status(true), show_power_status(true), forceUpdate(true)
  {
    digitalWrite(config.rs_pin, LOW);
    pinMode(config.rs_pin, OUTPUT);
    digitalWrite(config.en_pin, HIGH);
    pinMode(config.en_pin, OUTPUT);
    digitalWrite(config.d0_pin, LOW);
    pinMode(config.d0_pin, OUTPUT);
    digitalWrite(config.d1_pin, LOW);
    pinMode(config.d1_pin, OUTPUT);
    digitalWrite(config.d2_pin, LOW);
    pinMode(config.d2_pin, OUTPUT);
    digitalWrite(config.d3_pin, LOW);
    pinMode(config.d3_pin, OUTPUT);
    for (auto &row : buffer)
      row.fill({0});
    for (auto &row : current)
      row.fill({0});
  }
References buffer, config, fabomatic::pins_config::lcd_config::d0_pin, fabomatic::pins_config::lcd_config::d1_pin, fabomatic::pins_config::lcd_config::d2_pin, fabomatic::pins_config::lcd_config::d3_pin, fabomatic::pins_config::lcd_config::en_pin, and fabomatic::pins_config::lcd_config::rs_pin.
Member Function Documentation
backlightOff()
void fabomatic::LCDWrapper::backlightOff () const -> void private
Definition at line 218 of file LCDWrapper.cpp.
  {
    if (config.bl_pin != NO_PIN)
      digitalWrite(config.bl_pin, config.active_low ? HIGH : LOW);
  }
backlightOn()
void fabomatic::LCDWrapper::backlightOn () const -> void private
Definition at line 212 of file LCDWrapper.cpp.
  {
    if (config.bl_pin != NO_PIN)
      digitalWrite(config.bl_pin, config.active_low ? LOW : HIGH);
  }
begin()
bool fabomatic::LCDWrapper::begin () -> bool
Definition at line 35 of file LCDWrapper.cpp.
  {
    lcd.begin(conf::lcd::COLS, conf::lcd::ROWS);
    lcd.createChar(CHAR_ANTENNA, antenna_char.data());
    lcd.createChar(CHAR_CONNECTION, connection_char.data());
    lcd.createChar(CHAR_NO_CONNECTION, noconnection_char.data());
    lcd.createChar(CHAR_POWERED_OFF, powered_off_char.data());
    lcd.createChar(CHAR_POWERED_ON, powered_on_char.data());
    lcd.createChar(CHAR_POWERING_OFF, powering_off_char.data());
    if (config.bl_pin != NO_PIN)
      pinMode(config.bl_pin, OUTPUT);
    backlightOn();
    ESP_LOGI(TAG, "Configured LCD %d x %d (d4=%d, d5=%d, d6=%d, d7=%d, en=%d, rs=%d), backlight=%d", conf::lcd::COLS, conf::lcd::ROWS,
             config.d0_pin, config.d1_pin, config.d2_pin, config.d3_pin,
             config.en_pin, config.rs_pin, config.bl_pin);
    return true;
  }
References begin(), createChar(), lcd, and TAG.
Referenced by begin(), fabomatic::BoardLogic::initBoard(), and setup().
clear()
void fabomatic::LCDWrapper::clear () -> void
Definition at line 58 of file LCDWrapper.cpp.
  {
    for (auto &row : current)
      row.fill({' '});
    lcd.clear();
    forceUpdate = true;
  }
Referenced by update().
convertSecondsToHHMMSS()
auto fabomatic::LCDWrapper::convertSecondsToHHMMSS (std::chrono::seconds duration) const -> const std::string
Definition at line 224 of file LCDWrapper.cpp.
  {
    std::stringstream ss{};
    const auto hrs = std::chrono::duration_cast<std::chrono::hours>(duration);
    const auto mins = std::chrono::duration_cast<std::chrono::minutes>(duration - hrs);
    const auto secs = std::chrono::duration_cast<std::chrono::seconds>(duration - hrs - mins);
    ss << std::setfill('0') << std::setw(2) << hrs.count() << ":"
       << std::setfill('0') << std::setw(2) << mins.count() << ":"
       << std::setfill('0') << std::setw(2) << secs.count();
    return ss.str();
  }
createChar()
auto fabomatic::LCDWrapper::createChar (uint8_t char_idx, const std::array< uint8_t, HEIGHT_PX > & values) -> void private
Referenced by begin().
needsUpdate()
bool fabomatic::LCDWrapper::needsUpdate (const BoardInfo & bi) const -> bool private
Checks if the LCD buffer has changed since last write to the LCD, or forced update has been requested.
Parameters
bi current state of the board
Returns
true if the buffer has changed, false otherwise
Definition at line 137 of file LCDWrapper.cpp.
  {
    if (forceUpdate || !(bi == boardInfo) || current != buffer)
    {
      if (conf::debug::ENABLE_LOGS)
      {
        prettyPrint(buffer, bi);
      }
      return true;
    }
    return false;
  }
prettyPrint()
void fabomatic::LCDWrapper::prettyPrint (const DisplayBuffer & buf, const BoardInfo & bi) const -> void private
Debug utility to print in the console the current buffer contents.
Parameters
buf character buffer
bi board info, used for special indicators status
Definition at line 155 of file LCDWrapper.cpp.
  {
    std::stringstream ss;
    ss << "/" << std::string(conf::lcd::COLS, '-') << "\\\r\n"; // LCD top
    for (const auto &row : buf)
    {
      ss << "|";
      for (const auto &ch : row)
      {
        if (ch == 0)
        {
          ss << " "; // Replace \0 with space
        }
        else
        {
          ss << ch;
        }
      }
      ss << "|\r\n"; // LCD right border
    }
    // LCD lower border
    ss << "\\" << std::string(conf::lcd::COLS, '-') << "/\r\n";
    auto str = ss.str();
    // Add symbols
    constexpr auto symbols_per_line = conf::lcd::COLS + 3;
    str[symbols_per_line * 2 - 2] = bi.server_connected ? 'Y' : 'x';
    if (bi.power_state == Machine::PowerState::PoweredOn)
      str[symbols_per_line * 3 - 1] = 'Y';
    if (bi.power_state == Machine::PowerState::PoweredOff)
      str[symbols_per_line * 3 - 1] = 'x';
    if (bi.power_state == Machine::PowerState::WaitingPowerOff)
      str[symbols_per_line * 3 - 1] = '!';
    Serial.print(str.c_str());
  }
References fabomatic::BoardInfo::power_state, and fabomatic::BoardInfo::server_connected.
setRow()
void fabomatic::LCDWrapper::setRow (uint8_t row, const std::string_view & text) -> void
Definition at line 200 of file LCDWrapper.cpp.
  {
    if (row < conf::lcd::ROWS)
    {
      buffer[row].fill({0});
      for (auto i = 0; i < text.length() && i < conf::lcd::COLS; i++)
      {
        buffer[row][i] = text[i];
      }
    }
  }
Referenced by fabomatic::BoardLogic::longTap().
showConnection()
void fabomatic::LCDWrapper::showConnection (bool show) -> void
Definition at line 117 of file LCDWrapper.cpp.
  {
    if (show_connection_status != show)
      forceUpdate = true;
    show_connection_status = show;
  }
showPower()
void fabomatic::LCDWrapper::showPower (bool show) -> void
Definition at line 125 of file LCDWrapper.cpp.
  {
    if (show_power_status != show)
      forceUpdate = true;
    show_power_status = show;
  }
update()
void fabomatic::LCDWrapper::update (const BoardInfo & boardinfo, bool forced = false) -> void
Definition at line 66 of file LCDWrapper.cpp.
  {
    if (!forced && !needsUpdate(info))
    {
      return;
    }
    lcd.clear();
    auto row_num = 0;
    for (const auto &row : buffer)
    {
      lcd.setCursor(0, row_num);
      lcd.print(row.data());
      row_num++;
    }
    static_assert(conf::lcd::COLS > 1 && conf::lcd::ROWS > 1, "LCDWrapper required at least 2x2 LCDs");
    if (show_connection_status)
    {
      lcd.setCursor(conf::lcd::COLS - 2, 0);
      lcd.write(CHAR_ANTENNA);
      lcd.write(info.server_connected ? CHAR_CONNECTION : CHAR_NO_CONNECTION);
    }
    if (show_power_status)
    {
      lcd.setCursor(conf::lcd::COLS - 1, 1);
      if (info.power_state == Machine::PowerState::PoweredOn)
      {
        lcd.write(CHAR_POWERED_ON);
      }
      else if (info.power_state == Machine::PowerState::PoweredOff)
      {
        lcd.write(CHAR_POWERED_OFF);
      }
      else if (info.power_state == Machine::PowerState::WaitingPowerOff)
      {
        lcd.write(CHAR_POWERING_OFF);
      }
      else
      {
        lcd.write('?');
      }
    }
    current = buffer;
    boardInfo = info;
    forceUpdate = false;
  }
References clear(), lcd, fabomatic::BoardInfo::power_state, and fabomatic::BoardInfo::server_connected.
Referenced by fabomatic::BoardLogic::longTap().
Member Data Documentation
antenna_char
constexpr std::array<uint8_t, HEIGHT_PX> fabomatic::LCDWrapper::antenna_char {0x15, 0x0E, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04} static constexpr private
Definition at line 39 of file LCDWrapper.hpp.
{0x15, 0x0E, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04};
boardInfo
BoardInfo fabomatic::LCDWrapper::boardInfo private
Definition at line 54 of file LCDWrapper.hpp.
buffer
DisplayBuffer fabomatic::LCDWrapper::buffer private
Definition at line 52 of file LCDWrapper.hpp.
Referenced by LCDWrapper().
CHAR_ANTENNA
constexpr auto fabomatic::LCDWrapper::CHAR_ANTENNA = 0 static constexpr private
Definition at line 32 of file LCDWrapper.hpp.
CHAR_CONNECTION
constexpr auto fabomatic::LCDWrapper::CHAR_CONNECTION = 1 static constexpr private
Definition at line 33 of file LCDWrapper.hpp.
CHAR_NO_CONNECTION
constexpr auto fabomatic::LCDWrapper::CHAR_NO_CONNECTION = 2 static constexpr private
Definition at line 34 of file LCDWrapper.hpp.
CHAR_POWERED_OFF
constexpr auto fabomatic::LCDWrapper::CHAR_POWERED_OFF = 4 static constexpr private
Definition at line 36 of file LCDWrapper.hpp.
CHAR_POWERED_ON
constexpr auto fabomatic::LCDWrapper::CHAR_POWERED_ON = 3 static constexpr private
Definition at line 35 of file LCDWrapper.hpp.
CHAR_POWERING_OFF
constexpr auto fabomatic::LCDWrapper::CHAR_POWERING_OFF = 5 static constexpr private
Definition at line 37 of file LCDWrapper.hpp.
config
const pins_config::lcd_config& fabomatic::LCDWrapper::config private
Definition at line 46 of file LCDWrapper.hpp.
Referenced by LCDWrapper().
connection_char
constexpr std::array<uint8_t, HEIGHT_PX> fabomatic::LCDWrapper::connection_char {0x00, 0x00, 0x01, 0x01, 0x05, 0x05, 0x15, 0x15} static constexpr private
Definition at line 40 of file LCDWrapper.hpp.
{0x00, 0x00, 0x01, 0x01, 0x05, 0x05, 0x15, 0x15};
current
DisplayBuffer fabomatic::LCDWrapper::current private
Definition at line 53 of file LCDWrapper.hpp.
forceUpdate
bool fabomatic::LCDWrapper::forceUpdate private
Definition at line 51 of file LCDWrapper.hpp.
HEIGHT_PX
constexpr auto fabomatic::LCDWrapper::HEIGHT_PX = 8 static constexpr private
Definition at line 31 of file LCDWrapper.hpp.
lcd
LiquidCrystal fabomatic::LCDWrapper::lcd private
Definition at line 48 of file LCDWrapper.hpp.
noconnection_char
constexpr std::array<uint8_t, HEIGHT_PX> fabomatic::LCDWrapper::noconnection_char {0x00, 0x00, 0x11, 0x0A, 0x04, 0x0A, 0x11, 0x00} static constexpr private
Definition at line 41 of file LCDWrapper.hpp.
{0x00, 0x00, 0x11, 0x0A, 0x04, 0x0A, 0x11, 0x00};
powered_off_char
constexpr std::array<uint8_t, HEIGHT_PX> fabomatic::LCDWrapper::powered_off_char {0x0a, 0x04, 0x0a, 0x00, 0x1f, 0x1f, 0x0a, 0x0a} static constexpr private
Definition at line 43 of file LCDWrapper.hpp.
{0x0a, 0x04, 0x0a, 0x00, 0x1f, 0x1f, 0x0a, 0x0a};
powered_on_char
constexpr std::array<uint8_t, HEIGHT_PX> fabomatic::LCDWrapper::powered_on_char {0x04, 0x04, 0x04, 0x1f, 0x1f, 0x1f, 0x0a, 0x0a} static constexpr private
Definition at line 42 of file LCDWrapper.hpp.
{0x04, 0x04, 0x04, 0x1f, 0x1f, 0x1f, 0x0a, 0x0a};
powering_off_char
constexpr std::array<uint8_t, HEIGHT_PX> fabomatic::LCDWrapper::powering_off_char {0x0e, 0x15, 0x15, 0x15, 0x17, 0x11, 0x11, 0x0e} static constexpr private
Definition at line 44 of file LCDWrapper.hpp.
{0x0e, 0x15, 0x15, 0x15, 0x17, 0x11, 0x11, 0x0e};
show_connection_status
bool fabomatic::LCDWrapper::show_connection_status private
Definition at line 49 of file LCDWrapper.hpp.
show_power_status
bool fabomatic::LCDWrapper::show_power_status private
Definition at line 50 of file LCDWrapper.hpp.
The documentation for this class was generated from the following files:
LCDWrapper.hpp
LCDWrapper.cpp