Fab-O-Matic: fabomatic::FabBackend Class Reference
fabomatic::FabBackend Class Reference
#include <FabBackend.hpp>
Public Member Functions
FabBackend ()=default
auto checkCard (const card::uid_t uid) -> std::unique_ptr< ServerMQTT::UserResponse >
Checks if the card ID is known to the server.
auto checkMachine () -> std::unique_ptr< ServerMQTT::MachineResponse >
Checks the machine status on the server.
auto startUse (const card::uid_t uid) -> std::unique_ptr< ServerMQTT::SimpleResponse >
Registers the start of machine usage.
auto inUse (const card::uid_t uid, std::chrono::seconds duration) -> std::unique_ptr< ServerMQTT::SimpleResponse >
Informs the backend that the machine is in use.
auto finishUse (const card::uid_t uid, std::chrono::seconds duration) -> std::unique_ptr< ServerMQTT::SimpleResponse >
Registers the end of machine usage.
auto registerMaintenance (const card::uid_t maintainer) -> std::unique_ptr< ServerMQTT::SimpleResponse >
Registers a maintenance action.
auto alive () -> bool
Sends a ping to the server.
auto publish (String topic, String payload, bool waitForAnswer) -> bool
Publishes a message on the MQTT server.
auto isOnline () const -> bool
Checks if the client is online.
auto hasBufferedMsg () const -> bool
auto transmitBuffer () -> bool
auto saveBuffer () -> bool
auto connect () -> bool
Establishes a connection to the WiFi network and the MQTT server.
auto connectWiFi () -> bool
Connects to the WiFi network.
auto loop () -> bool
Main loop for the MQTT client.
auto configure (const SavedConfig &config) -> void
Configures the FabBackend with the given configuration.
auto disconnect () -> void
Disconnects from the MQTT server.
auto setChannel (int32_t channel) -> void
Sets the WiFi channel to use.
FabBackend (const FabBackend &)=delete
FabBackend & operator= (const FabBackend &)=delete
FabBackend (FabBackend &&)=delete
FabBackend & operator= (FabBackend &&)=delete
template<typename RespT , typename QueryT , typename... QueryArgs>
std::unique_ptr< RespT > processQuery (QueryArgs &&...args)
Processes a query and returns the response.
template<typename QueryT , typename... QueryArgs>
bool processQuery (QueryArgs &&...args)
Processes a query.
Private Types
enum class PublishResult : uint8_t { ErrorNotPublished , PublishedWithoutAnswer , PublishedWithAnswer }
Private Member Functions
auto messageReceived (String &topic, String &payload) -> void
Callback function for received MQTT messages.
template<typename QueryT >
auto publish (const QueryT &payload) -> PublishResult
Publishes a query on the MQTT server.
auto waitForAnswer (std::chrono::milliseconds timeout) -> bool
Waits for an answer from the MQTT server.
auto publishWithReply (const ServerMQTT::Query &payload) -> PublishResult
Posts a query to the MQTT server and waits for a reply.
template<typename RespT , typename QueryT , typename... QueryArgs>
auto processQuery (QueryArgs &&...) -> std::unique_ptr< RespT >
template<typename QueryT , typename... QueryArgs>
auto processQuery (QueryArgs &&...args) -> bool
auto loadBuffer (const Buffer &new_buffer) -> void
Private Attributes
MQTTClient client {MAX_MSG_SIZE}
JsonDocument doc
std::string wifi_ssid {""}
std::string wifi_password {""}
std::string broker_hostname {""}
std::string mqtt_user {""}
std::string mqtt_password {""}
std::string mqtt_client_name {""}
MQTTClientCallbackSimpleFunction callback
WiFiClient wifi_client
std::string topic {""}
std::string response_topic {""}
std::string last_query {""}
std::string last_reply {""}
bool online {false}
bool answer_pending {false}
int16_t channel {-1}
Buffer buffer
Static Private Attributes
static constexpr auto MAX_MSG_SIZE = 300
Detailed Description
This class is used to exchange messages with the MQTT broker and the backend
Definition at line 24 of file FabBackend.hpp.
Member Enumeration Documentation
PublishResult
enum class fabomatic::FabBackend::PublishResult : uint8_t strong private
Enumerator
ErrorNotPublished
PublishedWithoutAnswer
PublishedWithAnswer
Definition at line 28 of file FabBackend.hpp.
    {
      ErrorNotPublished,
      PublishedWithoutAnswer,
      PublishedWithAnswer
    };
Constructor & Destructor Documentation
FabBackend() [1/3]
fabomatic::FabBackend::FabBackend () default
FabBackend() [2/3]
fabomatic::FabBackend::FabBackend (const FabBackend &) delete
FabBackend() [3/3]
fabomatic::FabBackend::FabBackend (FabBackend &&) delete
Member Function Documentation
alive()
bool fabomatic::FabBackend::alive () -> bool
Sends a ping to the server.
Returns
true if the ping was sent successfully, false otherwise.
Definition at line 573 of file FabBackend.cpp.
  {
    return processQuery<ServerMQTT::AliveQuery>();
  }
Referenced by fabomatic::taskIsAlive(), fabomatic::tests::test_check_transmission(), and fabomatic::tests::test_fabserver_calls().
checkCard()
std::unique_ptr< ServerMQTT::UserResponse > fabomatic::FabBackend::checkCard (const card::uid_t uid) -> std::unique_ptr<ServerMQTT::UserResponse>
Checks if the card ID is known to the server.
Parameters
uid The card UID.
Returns
A unique_ptr to the server response.
Definition at line 507 of file FabBackend.cpp.
  {
    return processQuery<ServerMQTT::UserResponse, ServerMQTT::UserQuery>(uid);
  }
Referenced by fabomatic::tests::test_fabserver_calls(), and fabomatic::AuthProvider::tryLogin().
checkMachine()
std::unique_ptr< ServerMQTT::MachineResponse > fabomatic::FabBackend::checkMachine () -> std::unique_ptr<ServerMQTT::MachineResponse>
Checks the machine status on the server.
Returns
A unique_ptr to the server response.
Definition at line 517 of file FabBackend.cpp.
  {
    return processQuery<ServerMQTT::MachineResponse, ServerMQTT::MachineQuery>();
  }
Referenced by fabomatic::BoardLogic::refreshFromServer(), and fabomatic::tests::test_fabserver_calls().
configure()
void fabomatic::FabBackend::configure (const SavedConfig & config) -> void
Configures the FabBackend with the given configuration.
Parameters
config The SavedConfig object containing the configuration parameters.
Definition at line 21 of file FabBackend.cpp.
  {
    wifi_ssid = config.ssid;
    wifi_password = config.password;
    broker_hostname = config.mqtt_server;
    mqtt_user = config.mqtt_user;
    mqtt_password = config.mqtt_password;
#if (PINS_WOKWI)
    channel = 6;
    broker_hostname = "localhost";
#else
    channel = -1;
#endif
    online = false;
    std::stringstream ss_topic_name, ss_client_name;
    ss_topic_name << conf::mqtt::topic << "/" << config.machine_id;
    topic = ss_topic_name.str();
    ss_client_name << "BOARD" << random(0, 1000);
    mqtt_client_name = ss_client_name.str();
    if (client.connected()) // Topic or IP may also have changed
    {
      client.disconnect();
      wifi_client.stop();
    }
    loadBuffer(config.message_buffer);
    ESP_LOGD(TAG, "FabServer configured");
  }
References broker_hostname, channel, client, loadBuffer(), fabomatic::SavedConfig::machine_id, fabomatic::SavedConfig::message_buffer, mqtt_client_name, mqtt_password, fabomatic::SavedConfig::mqtt_password, fabomatic::SavedConfig::mqtt_server, mqtt_user, fabomatic::SavedConfig::mqtt_user, online, fabomatic::SavedConfig::password, fabomatic::SavedConfig::ssid, TAG, fabomatic::conf::mqtt::topic, topic, wifi_client, wifi_password, and wifi_ssid.
Referenced by fabomatic::BoardLogic::reconfigure(), fabomatic::tests::test_fabserver_calls(), fabomatic::tests::test_rfid_cache(), and fabomatic::tests::test_start_broker().
connect()
bool fabomatic::FabBackend::connect () -> bool
Establishes a connection to the WiFi network and the MQTT server.
Returns
true if both operations succeeded, false otherwise.
Definition at line 291 of file FabBackend.cpp.
  {
    const auto status = WiFi.status();
    ESP_LOGD(TAG, "FabServer::connect() called, Wifi status=%d", status);
    // Check if WiFi network is available, and if not, try to connect
    if (status != WL_CONNECTED)
    {
      online = false;
      if (client.connected())
      {
        ESP_LOGD(TAG, "Closing MQTT client due to WiFi down");
        client.disconnect();
      }
      Tasks::delay(100ms);
      connectWiFi();
    }
    // Check if WiFi is available but MQTT client is not
    if (WiFi.status() == WL_CONNECTED &&
        !client.connected())
    {
      IPAddress ip;
      if (WiFi.hostByName(broker_hostname.c_str(), ip))
      {
        ESP_LOGD(TAG, "Resolved MQTT server [%s] as [%s]", broker_hostname.c_str(), ip.toString().c_str());
      }
      else
      {
        ESP_LOGE(TAG, "Failed to resolve MQTT server [%s]", broker_hostname.c_str());
        return false;
      }
      ESP_LOGD(TAG, "Connecting to MQTT server [%s:%d]...", ip.toString().c_str(), conf::mqtt::PORT_NUMBER);
      client.begin(ip, conf::mqtt::PORT_NUMBER, wifi_client);
      callback = [&](String &a, String &b)
      { return messageReceived(a, b); };
      client.onMessage(callback);
      if (!client.connect(mqtt_client_name.c_str(),
                          mqtt_user.c_str(),
                          mqtt_password.c_str(), false))
      {
        ESP_LOGW(TAG, "Failure to connect as client: %s with username %s, last error %d", mqtt_client_name.c_str(), mqtt_user.c_str(), client.lastError());
        client.disconnect();
      }
      // Setup subscriptions
      if (client.connected())
      {
        std::stringstream tmp_topic;
        tmp_topic << topic << conf::mqtt::response_topic;
        response_topic.assign(tmp_topic.str());
        if (!client.subscribe(response_topic.c_str()))
        {
          ESP_LOGE(TAG, "MQTT Client: failure to subscribe to reply topic %s", response_topic.c_str());
        }
        else
        {
          ESP_LOGD(TAG, "MQTT Client: subscribed to reply topic %s", response_topic.c_str());
          online = true;
        }
        // Announce the board to the server
        if (auto query = ServerMQTT::AliveQuery{}; publish(query) == PublishResult::PublishedWithoutAnswer)
        {
          ESP_LOGI(TAG, "MQTT Client: board announced to server");
        }
        else
        {
          ESP_LOGW(TAG, "MQTT Client: failure to announce board to server");
        }
      }
      else
      {
        ESP_LOGW(TAG, "Failure to connect to MQTT server %s", broker_hostname.c_str());
      }
    }
    if (!client.connected())
    {
      online = false;
    }
    return online;
  }
References broker_hostname, callback, client, connectWiFi(), fabomatic::Tasks::delay(), messageReceived(), mqtt_client_name, mqtt_password, mqtt_user, online, fabomatic::conf::mqtt::PORT_NUMBER, publish(), PublishedWithoutAnswer, fabomatic::conf::mqtt::response_topic, response_topic, TAG, topic, and wifi_client.
Referenced by processQuery(), fabomatic::BoardLogic::refreshFromServer(), fabomatic::taskConnect(), fabomatic::tests::test_check_transmission(), fabomatic::tests::test_fabserver_calls(), fabomatic::tests::test_start_broker(), fabomatic::tests::test_taskConnect(), fabomatic::AuthProvider::tryLogin(), and waitForAnswer().
connectWiFi()
bool fabomatic::FabBackend::connectWiFi () -> bool
Connects to the WiFi network.
Returns
true if the connection succeeded, false otherwise.
Definition at line 259 of file FabBackend.cpp.
  {
    static constexpr auto NB_TRIES = 15;
    static constexpr auto DELAY_MS = 250ms;
    // Connect WiFi if needed
    if (WiFi.status() != WL_CONNECTED)
    {
      WiFi.setAutoReconnect(true);
      WiFi.persistent(true);
      WiFi.mode(WIFI_STA);
      ESP_LOGD(TAG, "FabServer::connectWiFi() : WiFi connection state=%d, connecting to SSID:%s (channel:%d)", WiFi.status(), wifi_ssid.c_str(), channel);
      WiFi.begin(wifi_ssid.data(), wifi_password.data(), channel);
      Tasks::delay(DELAY_MS);
      for (auto i = 0; i < NB_TRIES; i++)
      {
        if (WiFi.status() == WL_CONNECTED)
        {
          ESP_LOGD(TAG, "FabServer::connectWiFi() : WiFi connection successful");
          break;
        }
        Tasks::delay(DELAY_MS);
      }
    }
    return WiFi.status() == WL_CONNECTED;
  }
References channel, fabomatic::Tasks::delay(), TAG, wifi_password, and wifi_ssid.
Referenced by connect(), and fabomatic::tests::test_start_broker().
disconnect()
void fabomatic::FabBackend::disconnect () -> void
Disconnects from the MQTT server.
Definition at line 386 of file FabBackend.cpp.
  {
    client.disconnect();
    wifi_client.stop();
    Tasks::delay(100ms);
  }
References client, fabomatic::Tasks::delay(), and wifi_client.
Referenced by processQuery(), and fabomatic::tests::test_fabserver_calls().
finishUse()
std::unique_ptr< ServerMQTT::SimpleResponse > fabomatic::FabBackend::finishUse (const card::uid_t uid, std::chrono::seconds duration_s) -> std::unique_ptr<ServerMQTT::SimpleResponse>
Registers the end of machine usage.
Parameters
uid The card UID of the user.
duration_s The duration of usage in seconds.
Returns
A unique_ptr to the server response.
Definition at line 540 of file FabBackend.cpp.
  {
    return processQuery<ServerMQTT::SimpleResponse, ServerMQTT::StopUseQuery>(uid, duration_s);
  }
Referenced by fabomatic::BoardLogic::logout(), fabomatic::tests::test_create_buffered_messages(), and fabomatic::tests::test_fabserver_calls().
hasBufferedMsg()
auto fabomatic::FabBackend::hasBufferedMsg () const -> bool
Definition at line 588 of file FabBackend.cpp.
  {
    return this->buffer.count() > 0;
  }
References buffer, and fabomatic::Buffer::count().
Referenced by processQuery(), fabomatic::tests::test_check_transmission(), and fabomatic::tests::test_create_buffered_messages().
inUse()
std::unique_ptr< ServerMQTT::SimpleResponse > fabomatic::FabBackend::inUse (const card::uid_t uid, std::chrono::seconds duration_s) -> std::unique_ptr<ServerMQTT::SimpleResponse>
Informs the backend that the machine is in use.
Parameters
uid The card UID of the user.
duration_s The duration of usage in seconds.
Returns
A unique_ptr to the server response.
Definition at line 552 of file FabBackend.cpp.
  {
    return processQuery<ServerMQTT::SimpleResponse, ServerMQTT::InUseQuery>(uid, duration_s);
  }
Referenced by fabomatic::tests::test_create_buffered_messages(), and fabomatic::tests::test_fabserver_calls().
isOnline()
bool fabomatic::FabBackend::isOnline () const -> bool
Checks if the client is online.
Returns
true if the client is online, false otherwise.
Definition at line 235 of file FabBackend.cpp.
  {
    return online;
  }
References online.
Referenced by fabomatic::BoardLogic::blinkLed(), fabomatic::BoardLogic::longTap(), processQuery(), fabomatic::taskConnect(), fabomatic::taskIsAlive(), fabomatic::taskMQTTClientLoop(), fabomatic::tests::test_fabserver_calls(), fabomatic::tests::test_taskConnect(), fabomatic::tests::test_taskMQTTAlive(), fabomatic::AuthProvider::tryLogin(), and fabomatic::BoardLogic::updateLCD().
loadBuffer()
auto fabomatic::FabBackend::loadBuffer (const Buffer & new_buffer) -> void private
Definition at line 654 of file FabBackend.cpp.
  {
    buffer = new_buffer;
    buffer.setChanged(false);
    ESP_LOGI(TAG, "Loaded buffer with %d messages", buffer.count());
  }
References TAG.
Referenced by configure().
loop()
bool fabomatic::FabBackend::loop () -> bool
Main loop for the MQTT client.
Returns
true if the client is running successfully, false otherwise.
Definition at line 184 of file FabBackend.cpp.
  {
    if (!client.loop())
    {
      if (online)
      {
        ESP_LOGI(TAG, "MQTT Client: connection lost");
      }
      online = false;
      return false;
    }
    return true;
  }
References client, online, and TAG.
Referenced by fabomatic::taskMQTTClientLoop(), fabomatic::tests::test_fabserver_calls(), and fabomatic::tests::test_taskMQTTAlive().
messageReceived()
void fabomatic::FabBackend::messageReceived (String & s_topic, String & s_payload) -> void private
Callback function for received MQTT messages.
Parameters
s_topic The topic the message was received on.
s_payload The payload of the message.
Definition at line 246 of file FabBackend.cpp.
  {
    ESP_LOGI(TAG, "MQTT Client: Received on %s -> %s", s_topic.c_str(), s_payload.c_str());
    last_reply.assign(s_payload.c_str());
    answer_pending = false;
  }
References answer_pending, last_reply, and TAG.
Referenced by connect().
operator=() [1/2]
FabBackend & fabomatic::FabBackend::operator= (const FabBackend &) delete
operator=() [2/2]
FabBackend & fabomatic::FabBackend::operator= (FabBackend &&) delete
processQuery() [1/4]
template<typename RespT , typename QueryT , typename... QueryArgs> auto fabomatic::FabBackend::processQuery (QueryArgs && ...) -> std::unique_ptr< RespT > private
processQuery() [2/4]
template<typename RespT , typename QueryT , typename... QueryArgs> std::unique_ptr< RespT > fabomatic::FabBackend::processQuery (QueryArgs &&... args)
Processes a query and returns the response.
Template Parameters
RespT The type of the response.
QueryT The type of the query.
...Args The arguments to be passed to the query constructor.
Returns
A unique_ptr to the response.
Definition at line 402 of file FabBackend.cpp.
  {
    static_assert(std::is_base_of<ServerMQTT::Query, QueryT>::value, "QueryT must inherit from Query");
    static_assert(std::is_base_of<ServerMQTT::Response, RespT>::value, "RespT must inherit from Response");
    QueryT query{args...};
    auto nb_tries = 0;
    while (isOnline() && hasBufferedMsg() && !transmitBuffer() && nb_tries < 3)
    {
      // To preserve chronological order, we cannot send new messages until the old ones have been sent.
      ESP_LOGW(TAG, "Online with pending messages that could not be transmitted, retrying...");
      Tasks::delay(250ms);
      if (!isOnline())
      {
        connect();
      }
      nb_tries++;
    }
    if (isOnline() && !hasBufferedMsg())
    {
      if (publishWithReply(query) == PublishResult::PublishedWithAnswer)
      {
        // Deserialize the JSON document
        const auto payload = last_reply.c_str();
        if (DeserializationError error = deserializeJson(doc, payload))
        {
          ESP_LOGE(TAG, "Failed to parse json: %s (%s)", payload, error.c_str());
          return std::make_unique<RespT>(false);
        }
        return RespT::fromJson(doc);
      }
      else
      {
        ESP_LOGE(TAG, "Failed to publish query %s", query.payload().data());
        this->disconnect();
      }
    }
    if (query.buffered())
    {
      const auto &msg = BufferedMsg{query.payload(), topic, query.waitForReply()};
      buffer.push_back(msg);
    }
    return std::make_unique<RespT>(false);
  }
References buffer, connect(), fabomatic::Tasks::delay(), disconnect(), doc, hasBufferedMsg(), isOnline(), last_reply, PublishedWithAnswer, publishWithReply(), fabomatic::Buffer::push_back(), TAG, topic, and transmitBuffer().
processQuery() [3/4]
template<typename QueryT , typename... QueryArgs> bool fabomatic::FabBackend::processQuery (QueryArgs &&... args)
Processes a query.
Template Parameters
QueryT The type of the query.
...Args The arguments to be passed to the query constructor.
Returns
true if the query was processed successfully, false otherwise.
Definition at line 460 of file FabBackend.cpp.
  {
    static_assert(std::is_base_of<ServerMQTT::Query, QueryT>::value, "QueryT must inherit from Query");
    QueryT query{args...};
    auto nb_tries = 0;
    while (isOnline() && hasBufferedMsg() && !transmitBuffer() && nb_tries < 3)
    {
      // To preserve chronological order, we cannot send new messages until the old ones have been sent.
      ESP_LOGW(TAG, "Online with pending messages that could not be transmitted, retrying...");
      Tasks::delay(250ms);
      if (!isOnline())
      {
        connect();
      }
      nb_tries++;
    }
    if (isOnline() && !hasBufferedMsg())
    {
      if (publish(query) == PublishResult::PublishedWithoutAnswer)
      {
        return true;
      }
      else
      {
        ESP_LOGW(TAG, "Failed to publish query %s", query.payload().data());
        this->disconnect();
      }
    }
    if (query.buffered())
    {
      const auto &msg = BufferedMsg{query.payload(), topic, query.waitForReply()};
      buffer.push_back(msg);
    }
    return false;
  }
References buffer, connect(), fabomatic::Tasks::delay(), disconnect(), hasBufferedMsg(), isOnline(), publish(), PublishedWithoutAnswer, fabomatic::Buffer::push_back(), TAG, topic, and transmitBuffer().
processQuery() [4/4]
template<typename QueryT , typename... QueryArgs> auto fabomatic::FabBackend::processQuery (QueryArgs &&... args) -> bool private
publish() [1/2]
template<typename QueryT > auto fabomatic::FabBackend::publish (const QueryT & query) -> PublishResult private
Publishes a query on the MQTT server.
Parameters
query The query to be published.
Returns
true if the query was published successfully, false otherwise.
Definition at line 141 of file FabBackend.cpp.
  {
    String s_payload(query.payload().c_str());
    std::string temp_topic;
    // Check at compile-time if topic is specified
    if constexpr (std::is_base_of<BufferedQuery, QueryT>::value)
    {
      temp_topic = static_cast<BufferedQuery>(query).topic();
    }
    else
    {
      // Just use the default topic for the machine
      temp_topic = this->topic;
    }
    String s_topic{temp_topic.c_str()};
    if (s_payload.length() + s_topic.length() > FabBackend::MAX_MSG_SIZE - 8)
    {
      ESP_LOGE(TAG, "MQTT Client: Message is too long: %s", s_payload.c_str());
      return PublishResult::ErrorNotPublished;
    }
    answer_pending = query.waitForReply(); // Don't wait if not needed
    last_query.assign(s_payload.c_str());
    last_reply.clear();
    ESP_LOGD(TAG, "MQTT Client: sending message %s on topic %s", s_payload.c_str(), s_topic.c_str());
    if (client.publish(s_topic, s_payload))
    {
      return PublishResult::PublishedWithoutAnswer;
    }
    return PublishResult::ErrorNotPublished;
  }
References MAX_MSG_SIZE, and TAG.
Referenced by connect(), and processQuery().
publish() [2/2]
bool fabomatic::FabBackend::publish (String mqtt_topic, String mqtt_payload, bool waitForAnswer) -> bool
Publishes a message on the MQTT server.
Parameters
mqtt_topic The topic to publish to.
mqtt_payload The payload to publish.
waitForAnswer Whether to wait for an answer.
Returns
true if the message was published successfully, false otherwise.
Definition at line 118 of file FabBackend.cpp.
  {
    if (mqtt_payload.length() + mqtt_topic.length() > FabBackend::MAX_MSG_SIZE - 8)
    {
      ESP_LOGE(TAG, "MQTT Client: Message is too long: %s", mqtt_payload.c_str());
      return false;
    }
    answer_pending = waitForAnswer;
    last_query.assign(mqtt_payload.c_str());
    ESP_LOGI(TAG, "MQTT Client: sending message %s on topic %s", mqtt_payload.c_str(), mqtt_topic.c_str());
    return client.publish(mqtt_topic.c_str(), mqtt_payload.c_str());
  }
References answer_pending, client, last_query, MAX_MSG_SIZE, TAG, and waitForAnswer().
publishWithReply()
auto fabomatic::FabBackend::publishWithReply (const ServerMQTT::Query & query) -> PublishResult private
Posts a query to the MQTT server and waits for a reply.
Parameters
query The query to be posted.
Returns
true if the server answered, false otherwise.
Definition at line 61 of file FabBackend.cpp.
  {
    auto try_cpt = 0;
    auto published = false;
    while (try_cpt < conf::mqtt::MAX_TRIES)
    {
      try_cpt++;
      if (!published)
      {
        if (publish(query) == PublishResult::PublishedWithoutAnswer)
        {
          published = true;
        }
        else
        {
          ESP_LOGE(TAG, "MQTT Client: failure to send query %s", query.payload().data());
          Tasks::delay(conf::mqtt::TIMEOUT_REPLY_SERVER);
        }
      }
      if (waitForAnswer(conf::mqtt::TIMEOUT_REPLY_SERVER))
      {
        ESP_LOGD(TAG, "MQTT Client: received answer: %s", last_reply.data());
        return PublishResult::PublishedWithAnswer;
      }
      ESP_LOGW(TAG, "MQTT Client: no answer received, retrying %d/%d", try_cpt, conf::mqtt::MAX_TRIES);
      Tasks::delay(conf::mqtt::TIMEOUT_REPLY_SERVER);
    }
    ESP_LOGE(TAG, "MQTT Client: failure to send query %s", query.payload().data());
    // Do not send twice if response did not arrive
    if (query.buffered() && !published)
    {
      const auto &msg = BufferedMsg{query.payload(), topic, query.waitForReply()};
      buffer.push_back(msg);
    }
    if (published)
    {
      return PublishResult::PublishedWithoutAnswer;
    }
    return PublishResult::ErrorNotPublished;
  }
References fabomatic::Tasks::delay(), fabomatic::conf::mqtt::MAX_TRIES, TAG, and fabomatic::conf::mqtt::TIMEOUT_REPLY_SERVER.
Referenced by processQuery().
registerMaintenance()
std::unique_ptr< ServerMQTT::SimpleResponse > fabomatic::FabBackend::registerMaintenance (const card::uid_t maintainer) -> std::unique_ptr<ServerMQTT::SimpleResponse>
Registers a maintenance action.
Parameters
maintainer The UID of the person performing maintenance.
Returns
A unique_ptr to the server response.
Definition at line 563 of file FabBackend.cpp.
  {
    return processQuery<ServerMQTT::SimpleResponse, ServerMQTT::RegisterMaintenanceQuery>(maintainer);
  }
Referenced by fabomatic::BoardLogic::authorize(), fabomatic::tests::test_create_buffered_messages(), and fabomatic::tests::test_fabserver_calls().
saveBuffer()
auto fabomatic::FabBackend::saveBuffer () -> bool
Definition at line 633 of file FabBackend.cpp.
  {
    if (!buffer.hasChanged())
    {
      return true;
    }
    auto sc = SavedConfig::LoadFromEEPROM().value_or(SavedConfig::DefaultConfig());
    sc.message_buffer = buffer;
    if (sc.SaveToEEPROM())
    {
      buffer.setChanged(false);
      ESP_LOGI(TAG, "Saved %d buffered messages", buffer.count());
      return true;
    }
    ESP_LOGE(TAG, "Failed to save buffered messages!");
    return false;
  }
References fabomatic::SavedConfig::DefaultConfig(), fabomatic::SavedConfig::LoadFromEEPROM(), and TAG.
Referenced by fabomatic::taskIsAlive(), fabomatic::tests::test_check_transmission(), and fabomatic::tests::test_create_buffered_messages().
setChannel()
void fabomatic::FabBackend::setChannel (int32_t channel) -> void
Sets the WiFi channel to use.
Parameters
channel The channel number.
Definition at line 583 of file FabBackend.cpp.
  {
    this->channel = channel;
  }
References channel.
Referenced by fabomatic::tests::test_start_broker().
startUse()
std::unique_ptr< ServerMQTT::SimpleResponse > fabomatic::FabBackend::startUse (const card::uid_t uid) -> std::unique_ptr<ServerMQTT::SimpleResponse>
Registers the start of machine usage.
Parameters
uid The card UID of the user.
Returns
A unique_ptr to the server response.
Definition at line 528 of file FabBackend.cpp.
  {
    return processQuery<ServerMQTT::SimpleResponse, ServerMQTT::StartUseQuery>(uid);
  }
Referenced by fabomatic::BoardLogic::authorize(), fabomatic::tests::test_create_buffered_messages(), and fabomatic::tests::test_fabserver_calls().
transmitBuffer()
auto fabomatic::FabBackend::transmitBuffer () -> bool
Definition at line 593 of file FabBackend.cpp.
  {
    while (hasBufferedMsg() && isOnline())
    {
      ESP_LOGD(TAG, "Retransmitting buffered messages...");
      const auto &msg = buffer.getMessage();
      const BufferedQuery bq{msg.mqtt_message, msg.mqtt_topic, msg.wait_for_answer};
      if (bq.waitForReply())
      {
        if (auto result = publishWithReply(bq); result != PublishResult::PublishedWithAnswer)
        {
          ESP_LOGW(TAG, "Retransmitting buffered message failed!");
          // If it has been published but not answered, do not try again
          if (result == PublishResult::PublishedWithoutAnswer)
          {
            const auto &bmsg = BufferedMsg{msg.mqtt_message, msg.mqtt_topic, msg.wait_for_answer};
            buffer.push_front(bmsg);
          }
          break;
        }
      }
      else
      {
        if (publish(bq) == PublishResult::ErrorNotPublished)
        {
          // Will try again
          ESP_LOGW(TAG, "Retransmitting buffered message failed!");
          const auto &bmsg = BufferedMsg{msg.mqtt_message, msg.mqtt_topic, msg.wait_for_answer};
          buffer.push_front(bmsg);
          break;
        }
      }
    }
    last_reply = "";
    ESP_LOGW(TAG, "Retransmittion completed, remaining messages=%d", buffer.count());
    return !hasBufferedMsg();
  }
References fabomatic::BufferedMsg::mqtt_message, fabomatic::BufferedQuery::mqtt_topic, and TAG.
Referenced by processQuery().
waitForAnswer()
bool fabomatic::FabBackend::waitForAnswer (std::chrono::milliseconds max_duration) -> bool private
Waits for an answer from the MQTT server.
Parameters
max_duration The maximum duration to wait.
Returns
true if the server answered, false otherwise.
Definition at line 204 of file FabBackend.cpp.
  {
    const auto start_time = std::chrono::system_clock::now();
    const auto DELAY_MS = 25ms;
    do
    {
      if (answer_pending)
      {
        client.loop();
        if (!client.connected())
        {
          ESP_LOGW(TAG, "MQTT Client: connection lost while waiting for answer");
          connect();
        }
        Tasks::delay(DELAY_MS);
      }
      else
      {
        return true;
      }
    } while (std::chrono::system_clock::now() < (start_time + max_duration));
    ESP_LOGE(TAG, "Failure, no answer from MQTT server (timeout:%lld ms)", max_duration.count());
    return false;
  }
References answer_pending, client, connect(), fabomatic::Tasks::delay(), and TAG.
Referenced by publish().
Member Data Documentation
answer_pending
bool fabomatic::FabBackend::answer_pending {false} private
Definition at line 54 of file FabBackend.hpp.
{false};
Referenced by messageReceived(), publish(), and waitForAnswer().
broker_hostname
std::string fabomatic::FabBackend::broker_hostname {""} private
Definition at line 40 of file FabBackend.hpp.
{""};
Referenced by configure(), and connect().
buffer
Buffer fabomatic::FabBackend::buffer private
Definition at line 57 of file FabBackend.hpp.
Referenced by hasBufferedMsg(), and processQuery().
callback
MQTTClientCallbackSimpleFunction fabomatic::FabBackend::callback private
Definition at line 45 of file FabBackend.hpp.
Referenced by connect().
channel
int16_t fabomatic::FabBackend::channel {-1} private
Definition at line 55 of file FabBackend.hpp.
{-1};
Referenced by configure(), connectWiFi(), and setChannel().
client
MQTTClient fabomatic::FabBackend::client {MAX_MSG_SIZE} private
Definition at line 35 of file FabBackend.hpp.
{MAX_MSG_SIZE}; // Default is 128, and can be reached with some messages
Referenced by configure(), connect(), disconnect(), loop(), publish(), and waitForAnswer().
doc
JsonDocument fabomatic::FabBackend::doc private
Definition at line 36 of file FabBackend.hpp.
Referenced by processQuery().
last_query
std::string fabomatic::FabBackend::last_query {""} private
Definition at line 50 of file FabBackend.hpp.
{""};
Referenced by publish().
last_reply
std::string fabomatic::FabBackend::last_reply {""} private
Definition at line 51 of file FabBackend.hpp.
{""};
Referenced by messageReceived(), and processQuery().
MAX_MSG_SIZE
constexpr auto fabomatic::FabBackend::MAX_MSG_SIZE = 300 static constexpr private
Definition at line 27 of file FabBackend.hpp.
Referenced by publish(), and publish().
mqtt_client_name
std::string fabomatic::FabBackend::mqtt_client_name {""} private
Definition at line 43 of file FabBackend.hpp.
{""};
Referenced by configure(), and connect().
mqtt_password
std::string fabomatic::FabBackend::mqtt_password {""} private
Definition at line 42 of file FabBackend.hpp.
{""};
Referenced by configure(), and connect().
mqtt_user
std::string fabomatic::FabBackend::mqtt_user {""} private
Definition at line 41 of file FabBackend.hpp.
{""};
Referenced by configure(), and connect().
online
bool fabomatic::FabBackend::online {false} private
Definition at line 53 of file FabBackend.hpp.
{false};
Referenced by configure(), connect(), isOnline(), and loop().
response_topic
std::string fabomatic::FabBackend::response_topic {""} private
Definition at line 49 of file FabBackend.hpp.
{""};
Referenced by connect().
topic
std::string fabomatic::FabBackend::topic {""} private
Definition at line 48 of file FabBackend.hpp.
{""};
Referenced by configure(), connect(), and processQuery().
wifi_client
WiFiClient fabomatic::FabBackend::wifi_client private
Definition at line 46 of file FabBackend.hpp.
Referenced by configure(), connect(), and disconnect().
wifi_password
std::string fabomatic::FabBackend::wifi_password {""} private
Definition at line 39 of file FabBackend.hpp.
{""};
Referenced by configure(), and connectWiFi().
wifi_ssid
std::string fabomatic::FabBackend::wifi_ssid {""} private
Definition at line 38 of file FabBackend.hpp.
{""};
Referenced by configure(), and connectWiFi().
The documentation for this class was generated from the following files:
FabBackend.hpp
FabBackend.cpp