Fab-O-Matic: fabomatic::Led Class Reference
fabomatic::Led Class Reference
RGB/LED/NeoPixel class.
#include <Led.hpp>
Public Types
enum class Status { Off , On , Blinking }
Public Member Functions
Led ()=default
auto set (Status status) -> void
auto setColor (uint8_t r, uint8_t g, uint8_t b) -> void
auto update () -> void
Private Member Functions
void outputColor (uint8_t r, uint8_t g, uint8_t b)
void init ()
Private Attributes
Adafruit_NeoPixel pixel {1, pins.led.pin, pins.led.neopixel_config}
std::array< uint8_t, 3 > color {128, 128, 128}
Status status {Status::On}
bool isOn {false}
bool initialized {false}
Detailed Description
RGB/LED/NeoPixel class.
Definition at line 13 of file Led.hpp.
Member Enumeration Documentation
Status
enum class fabomatic::Led::Status strong
Enumerator
Off
On
Blinking
Definition at line 16 of file Led.hpp.
    {
      Off,
      On,
      Blinking,
    };
Constructor & Destructor Documentation
Led()
fabomatic::Led::Led () default
Member Function Documentation
init()
auto fabomatic::Led::init () private
Definition at line 6 of file Led.cpp.
  {
    if (initialized || pins.led.pin == NO_PIN)
    {
      return;
    }
    ESP_LOGD(TAG, "Initializing LED (pin %d, is_neopixel %d, flags %lu)",
             pins.led.pin, pins.led.is_neopixel, pins.led.neopixel_config);
    if constexpr (pins.led.is_neopixel)
    {
      pixel.begin();
    }
    else if constexpr (pins.led.is_rgb)
    {
      pinMode(pins.led.pin, OUTPUT);
      pinMode(pins.led.green_pin, OUTPUT);
      pinMode(pins.led.blue_pin, OUTPUT);
    }
    else
    {
      digitalWrite(pins.led.pin, LOW);
      pinMode(pins.led.pin, OUTPUT);
    }
    initialized = true;
  }
References fabomatic::pins_config::led_config::blue_pin, fabomatic::pins_config::led_config::green_pin, fabomatic::pins_config::led_config::is_neopixel, fabomatic::pins_config::led_config::is_rgb, fabomatic::pins_config::led, fabomatic::pins_config::led_config::neopixel_config, fabomatic::NO_PIN, fabomatic::pins_config::led_config::pin, fabomatic::pins, and TAG.
outputColor()
auto fabomatic::Led::outputColor (uint8_t r, uint8_t g, uint8_t b) private
Definition at line 44 of file Led.cpp.
  {
    if constexpr (pins.led.is_neopixel)
    {
      pixel.setPixelColor(0, r, g, b);
      pixel.show();
    }
    if constexpr (pins.led.is_rgb)
    {
      analogWrite(pins.led.pin, r);
      analogWrite(pins.led.green_pin, g);
      analogWrite(pins.led.blue_pin, b);
    }
    if constexpr (!pins.led.is_rgb || !pins.led.is_neopixel)
    {
      const auto light = r > 0 || g > 0 || b > 0;
      digitalWrite(pins.led.pin, light ? HIGH : LOW);
    }
  }
References fabomatic::pins_config::led_config::blue_pin, fabomatic::pins_config::led_config::green_pin, fabomatic::pins_config::led_config::is_neopixel, fabomatic::pins_config::led_config::is_rgb, fabomatic::pins_config::led, fabomatic::pins_config::led_config::pin, and fabomatic::pins.
set()
auto fabomatic::Led::set (Status status) -> void
Definition at line 39 of file Led.cpp.
  {
    this->status = new_status;
  }
Referenced by fabomatic::BoardLogic::blinkLed().
setColor()
auto fabomatic::Led::setColor (uint8_t r, uint8_t g, uint8_t b) -> void
Definition at line 34 of file Led.cpp.
  {
    color = {r, g, b};
  }
Referenced by fabomatic::BoardLogic::blinkLed().
update()
auto fabomatic::Led::update () -> void
Definition at line 64 of file Led.cpp.
  {
    init();
    switch (status)
    {
    case Status::Off:
      isOn = false;
      break;
    case Status::On:
      isOn = true;
      break;
    case Status::Blinking:
      isOn = !isOn;
      break;
    }
    if (isOn)
    {
      outputColor(color[0], color[1], color[2]);
    }
    else
    {
      outputColor(0, 0, 0);
    }
  }
Referenced by fabomatic::BoardLogic::blinkLed().
Member Data Documentation
color
std::array<uint8_t, 3> fabomatic::Led::color {128, 128, 128} private
Definition at line 31 of file Led.hpp.
{128, 128, 128};
initialized
bool fabomatic::Led::initialized {false} private
Definition at line 34 of file Led.hpp.
{false};
isOn
bool fabomatic::Led::isOn {false} private
Definition at line 33 of file Led.hpp.
{false};
pixel
Adafruit_NeoPixel fabomatic::Led::pixel {1, pins.led.pin, pins.led.neopixel_config} private
Definition at line 30 of file Led.hpp.
{1, pins.led.pin, pins.led.neopixel_config};
status
Status fabomatic::Led::status {Status::On} private
Definition at line 32 of file Led.hpp.
{Status::On};
The documentation for this class was generated from the following files:
Led.hpp
Led.cpp