Fab-O-Matic: fabomatic::AuthProvider Class Reference
fabomatic::AuthProvider Class Reference
#include <AuthProvider.hpp>
Public Member Functions
AuthProvider ()=delete
AuthProvider (WhiteList whitelist)
auto tryLogin (card::uid_t uid, FabBackend &server) const -> std::optional< FabUser >
Verifies the card ID against the server (if available) or the whitelist.
auto setWhitelist (WhiteList list) -> void
Sets the whitelist.
auto saveCache () const -> bool
Saves the cache of RFID to EEPROM.
auto loadCache () -> void
Loads the cache from EEPROM.
Private Member Functions
auto uidInWhitelist (card::uid_t uid) const -> std::optional< WhiteListEntry >
Checks if the card ID is whitelisted.
auto uidInCache (card::uid_t uid) const -> std::optional< CachedCard >
Checks if the card ID is whitelisted.
auto searchCache (card::uid_t candidate_uid) const -> std::optional< CachedCard >
auto updateCache (card::uid_t candidate_uid, FabUser::UserLevel level) const -> void
Cache the user request.
Private Attributes
WhiteList whitelist
CachedCards cache
size_t cache_idx {0}
Detailed Description
This class manages authentication of a RFID tag through cache, whitelist or network request.
Definition at line 19 of file AuthProvider.hpp.
Constructor & Destructor Documentation
AuthProvider() [1/2]
fabomatic::AuthProvider::AuthProvider () delete
AuthProvider() [2/2]
fabomatic::AuthProvider::AuthProvider (WhiteList whitelist)
Definition at line 18 of file AuthProvider.cpp.
: whitelist{list}, cache{} {}
Member Function Documentation
loadCache()
auto fabomatic::AuthProvider::loadCache () -> void
Loads the cache from EEPROM.
Definition at line 163 of file AuthProvider.cpp.
  {
    const auto &config = SavedConfig::LoadFromEEPROM();
    if (!config.has_value())
      return;
    const auto &loaded = config.value().cachedRfid;
    std::copy(loaded.cards.cbegin(), loaded.cards.cend(), cache.cards.begin());
    std::copy(loaded.levels.cbegin(), loaded.levels.cend(), cache.levels.begin());
  }
References fabomatic::SavedConfig::LoadFromEEPROM().
Referenced by fabomatic::BoardLogic::reconfigure().
saveCache()
auto fabomatic::AuthProvider::saveCache () const -> bool
Saves the cache of RFID to EEPROM.
Definition at line 183 of file AuthProvider.cpp.
  {
    SavedConfig config = SavedConfig::LoadFromEEPROM().value_or(SavedConfig::DefaultConfig());
    if (std::equal(config.cachedRfid.cards.cbegin(), config.cachedRfid.cards.cend(), cache.cards.cbegin()) &&
        std::equal(config.cachedRfid.levels.cbegin(), config.cachedRfid.levels.cend(), cache.levels.cbegin()))
    {
      ESP_LOGD(TAG, "Cache is the same, not saving");
      return true;
    }
    std::copy(cache.cards.cbegin(), cache.cards.cend(), config.cachedRfid.cards.begin());
    std::copy(cache.levels.cbegin(), cache.levels.cend(), config.cachedRfid.levels.begin());
    return config.SaveToEEPROM();
  }
References cache, fabomatic::SavedConfig::cachedRfid, fabomatic::CachedCards::cards, fabomatic::SavedConfig::DefaultConfig(), fabomatic::CachedCards::levels, fabomatic::SavedConfig::LoadFromEEPROM(), fabomatic::SavedConfig::SaveToEEPROM(), and TAG.
Referenced by fabomatic::tests::test_fabserver_calls(), and fabomatic::tests::test_rfid_cache().
searchCache()
auto fabomatic::AuthProvider::searchCache (card::uid_t candidate_uid) const -> std::optional< CachedCard > private
setWhitelist()
auto fabomatic::AuthProvider::setWhitelist (WhiteList list) -> void
Sets the whitelist.
Parameters
list the whitelist to set
Definition at line 177 of file AuthProvider.cpp.
  {
    whitelist = list;
  }
tryLogin()
auto fabomatic::AuthProvider::tryLogin (card::uid_t uid, FabBackend & server) const -> std::optional<FabUser>
Verifies the card ID against the server (if available) or the whitelist.
Parameters
uid card ID
server the server to check the card against
Returns
a FabUser with an authenticated flag==true if valid, otherwise nullopt or FabUser with authenticated==False.
Definition at line 54 of file AuthProvider.cpp.
  {
    FabUser user;
    using UserResult = ServerMQTT::UserResult;
    const auto uid_str = card::uid_str(uid);
    ESP_LOGD(TAG, "tryLogin called for %s", uid_str.c_str());
    if (!server.isOnline())
      server.connect();
    if (server.isOnline())
    {
      const auto response = server.checkCard(uid);
      if (response->request_ok)
      {
        user.card_uid = uid;
        if (response->getResult() == UserResult::Authorized)
        {
          user.authenticated = true;
          user.holder_name = response->holder_name;
          user.user_level = response->user_level;
          // Cache the positive result
          updateCache(uid, response->user_level);
          ESP_LOGD(TAG, " -> online check OK (%s)", user.toString().c_str());
          return user;
        }
        // Invalidate the cache entries
        updateCache(uid, FabUser::UserLevel::Unknown);
      } // if (response->request_ok)
      ESP_LOGD(TAG, " -> online check NOT OK");
      user.authenticated = false;
      if (response->request_ok) // Server replied but user is not valid
      {
        return user;
      }
    }
    // Check whitelist if offline
    if (const auto &result = uidInWhitelist(uid); result.has_value())
    {
      const auto &[card, level, name] = result.value();
      user.card_uid = card;
      user.authenticated = true;
      user.user_level = level;
      user.holder_name = name;
      ESP_LOGD(TAG, " -> whilelist check OK (%s)", user.toString().c_str());
      return user;
    }
    // Finally check the cached values
    if (const auto &result = uidInCache(uid); result.has_value())
    {
      const auto &cached = result.value();
      user.card_uid = cached.uid;
      user.authenticated = (cached.level != FabUser::UserLevel::Unknown);
      user.user_level = cached.level;
      user.holder_name = card::uid_str(uid);
      ESP_LOGD(TAG, " -> cache check OK (%s)", user.toString().c_str());
      return user;
    }
    ESP_LOGD(TAG, " -> whilelist check NOK");
    return std::nullopt;
  }
References fabomatic::FabUser::authenticated, fabomatic::FabUser::card_uid, fabomatic::FabBackend::checkCard(), fabomatic::FabBackend::connect(), fabomatic::FabUser::holder_name, fabomatic::FabBackend::isOnline(), TAG, fabomatic::FabUser::toString(), fabomatic::card::uid_str(), fabomatic::FabUser::Unknown, and fabomatic::FabUser::user_level.
Referenced by fabomatic::BoardLogic::authorize(), fabomatic::tests::test_fabserver_calls(), and fabomatic::tests::test_rfid_cache().
uidInCache()
auto fabomatic::AuthProvider::uidInCache (card::uid_t candidate_uid) const -> std::optional<CachedCard> private
Checks if the card ID is whitelisted.
Parameters
uid card ID
Returns
a whitelistentry object if the card is found in whitelist
Definition at line 157 of file AuthProvider.cpp.
  {
    return cache.find_uid(candidate_uid);
  }
uidInWhitelist()
auto fabomatic::AuthProvider::uidInWhitelist (card::uid_t candidate_uid) const -> std::optional<WhiteListEntry> private
Checks if the card ID is whitelisted.
Parameters
uid card ID
Returns
a whitelistentry object if the card is found in whitelist
Definition at line 131 of file AuthProvider.cpp.
  {
    if (candidate_uid == card::INVALID)
    {
      return std::nullopt;
    }
    const auto &elem = std::find_if(whitelist.cbegin(), whitelist.cend(),
                                    [candidate_uid](const auto &input)
{
                                      const auto &[w_uid, w_level, w_name] = input;
                                      return w_uid == candidate_uid;
                                    });
    if (elem == whitelist.cend())
    {
      ESP_LOGD(TAG, "%s not found in whitelist", card::uid_str(candidate_uid).c_str());
      return std::nullopt;
    }
    return {*elem};
  }
References fabomatic::card::INVALID, TAG, and fabomatic::card::uid_str().
updateCache()
void fabomatic::AuthProvider::updateCache (card::uid_t uid, FabUser::UserLevel level) const -> void private
Cache the user request.
Parameters
uid card id of the user
name name of the user to be cached
level priviledge level of the user
Definition at line 24 of file AuthProvider.cpp.
  {
    // Search for the card in the cache
    const auto pos = std::find(cache.cards.cbegin(), cache.cards.cend(), uid);
    if (pos != cache.cards.cend())
    {
      // Update the level at same index
      const auto idx = std::distance(cache.cards.cbegin(), pos);
      cache.levels[idx] = level;
      return;
    }
    // No need to add in cache invalid cards
    if (level == FabUser::UserLevel::Unknown)
      return;
    // Sanity check
    if (cache_idx >= cache.size())
      cache_idx = 0;
    // Add into list
    cache.set_at(cache_idx, uid, level);
    cache_idx = (cache_idx + 1) % conf::rfid_tags::CACHE_LEN;
  }
References cache, cache_idx, fabomatic::conf::rfid_tags::CACHE_LEN, fabomatic::CachedCards::cards, fabomatic::CachedCards::levels, fabomatic::CachedCards::set_at(), fabomatic::CachedCards::size(), and fabomatic::FabUser::Unknown.
Member Data Documentation
cache
CachedCards fabomatic::AuthProvider::cache mutable private
Definition at line 23 of file AuthProvider.hpp.
Referenced by saveCache(), and updateCache().
cache_idx
size_t fabomatic::AuthProvider::cache_idx {0} mutable private
Definition at line 24 of file AuthProvider.hpp.
{0};
Referenced by updateCache().
whitelist
WhiteList fabomatic::AuthProvider::whitelist private
Definition at line 22 of file AuthProvider.hpp.
The documentation for this class was generated from the following files:
AuthProvider.hpp
AuthProvider.cpp