Fab-O-Matic: fabomatic::Tasks::Task Class Reference
fabomatic::Tasks::Task Class Reference
A task class which represents a function to be called at requested intervals.
#include <Tasks.hpp>
Public Member Functions
Task ()=delete
Task (const std::string &id, milliseconds period, std::function< void()> callback, Scheduler &scheduler, bool active=true, milliseconds delay=0ms)
Creates a new task.
~Task ()=default
Task (const Task &other)=default
Task (Task &&other)=default
Task & operator= (const Task &other)=default
Task & operator= (Task &&other)=default
auto run () -> void
Execute the task if active.
auto disable () -> void
Prevent the task from running again.
auto enable () -> void
Allows the task to run again.
auto updateSchedule () -> void
recompute the next run time (now + delay) and allows the task to run again
auto setPeriod (milliseconds new_period) -> void
Change the task period.
auto setDelay (milliseconds new_delay) -> void
Change the task initial delay.
auto setCallback (std::function< void()> new_callback) -> void
Change the callback function.
auto isActive () const -> bool
Status of the task.
auto getPeriod () const -> const milliseconds
Current period of the task.
auto getCallback () const -> std::function< void()>
Function to be called when task is run.
auto getId () const -> const std::string
Get the Task Identifier.
auto getDelay () const -> const milliseconds
Get the initial delay before the task is run at given period.
auto getAvgTardiness () const -> const milliseconds
Get the average tardiness, i.e. the average period between scheduled start and actual start of execution.
auto getRunCounter () const -> unsigned long
Gets the number of times the task has been run.
auto getTotalRuntime () const -> const milliseconds
Gets the total execution time of the task. Useful to spot slowest tasks.
auto getNextRun () const -> const Tasks::time_point &
When shall the task be run again.
auto toString () const -> const std::string
Private Attributes
bool active
const std::string id
milliseconds period
milliseconds delay
Tasks::time_point last_run
Tasks::time_point next_run
milliseconds average_tardiness
milliseconds total_runtime
std::function< void()> callback
unsigned long run_counter
Detailed Description
A task class which represents a function to be called at requested intervals.
Definition at line 25 of file Tasks.hpp.
Constructor & Destructor Documentation
Task() [1/4]
fabomatic::Tasks::Task::Task () delete
Task() [2/4]
fabomatic::Tasks::Task::Task (const std::string & id, milliseconds period, std::function< void()> callback, Scheduler & scheduler, bool active = true, milliseconds delay = 0ms)
Creates a new task.
Parameters
id task id, used for logging
period period of the calls
callback function to callback
scheduler scheduler object to be added into
active if false, scheduler will ignore the task until start()/restart() are called on the task
delay initial delay before considering the task for execution
id task id
period task period (if 0, will be run only once)
callback callback function to execute
scheduler reference to the scheduler
active if true, the task will be executed
delay initial delay before starting the task
Definition at line 122 of file Tasks.cpp.
                                                                    : active{active}, id{id},
                                                                      period{period}, delay{delay},
                                                                      next_run{last_run},
                                                                      average_tardiness{0ms}, total_runtime{0ms},
                                                                      callback{callback}, run_counter{0}
  {
    last_run = arduinoNow() + period;
    scheduler.addTask(this);
    if constexpr (conf::debug::ENABLE_TASK_LOGS)
    {
      ESP_LOGD(TAG, "Constructor(%s)\r\n", toString().c_str());
    }
  }
References fabomatic::Tasks::Scheduler::addTask(), fabomatic::Tasks::arduinoNow(), fabomatic::conf::debug::ENABLE_TASK_LOGS, last_run, period, TAG, and toString().
~Task()
fabomatic::Tasks::Task::~Task () default
Task() [3/4]
fabomatic::Tasks::Task::Task (const Task & other) default
Task() [4/4]
fabomatic::Tasks::Task::Task (Task && other) default
Member Function Documentation
disable()
auto fabomatic::Tasks::Task::disable () -> void
Prevent the task from running again.
Definition at line 181 of file Tasks.cpp.
  {
    active = false;
  }
enable()
auto fabomatic::Tasks::Task::enable () -> void
Allows the task to run again.
Definition at line 186 of file Tasks.cpp.
  {
    active = true;
    updateSchedule();
  }
Referenced by setup().
getAvgTardiness()
auto fabomatic::Tasks::Task::getAvgTardiness () const -> const milliseconds
Get the average tardiness, i.e. the average period between scheduled start and actual start of execution.
Definition at line 229 of file Tasks.cpp.
  {
    if (average_tardiness > period)
    {
      return average_tardiness - period;
    }
    return 0ms;
  }
References average_tardiness, and period.
getCallback()
auto fabomatic::Tasks::Task::getCallback () const -> std::function<void()>
Function to be called when task is run.
Returns
Callback function
Definition at line 219 of file Tasks.cpp.
  {
    return callback;
  }
References callback.
getDelay()
auto fabomatic::Tasks::Task::getDelay () const -> const milliseconds
Get the initial delay before the task is run at given period.
Returns
Delay in milliseconds
Definition at line 243 of file Tasks.cpp.
  {
    return delay;
  }
References delay.
getId()
auto fabomatic::Tasks::Task::getId () const -> const std::string
Get the Task Identifier.
Definition at line 224 of file Tasks.cpp.
  {
    return id;
  }
References id.
Referenced by toString().
getNextRun()
auto fabomatic::Tasks::Task::getNextRun () const -> const Tasks::time_point &
When shall the task be run again.
Returns
time_point of the next run or time_point::max() if the task will not run.
Definition at line 258 of file Tasks.cpp.
  {
    return next_run;
  }
References next_run.
getPeriod()
auto fabomatic::Tasks::Task::getPeriod () const -> const milliseconds
Current period of the task.
Definition at line 214 of file Tasks.cpp.
  {
    return period;
  }
References period.
getRunCounter()
auto fabomatic::Tasks::Task::getRunCounter () const -> unsigned long
Gets the number of times the task has been run.
Definition at line 238 of file Tasks.cpp.
  {
    return run_counter;
  }
References run_counter.
getTotalRuntime()
auto fabomatic::Tasks::Task::getTotalRuntime () const -> const milliseconds
Gets the total execution time of the task. Useful to spot slowest tasks.
Definition at line 253 of file Tasks.cpp.
  {
    return total_runtime;
  }
References total_runtime.
isActive()
auto fabomatic::Tasks::Task::isActive () const -> bool
Status of the task.
Returns
True if Scheduler can launch it
Definition at line 209 of file Tasks.cpp.
  {
    return active;
  }
References active.
operator=() [1/2]
Task & fabomatic::Tasks::Task::operator= (const Task & other) default
operator=() [2/2]
Task & fabomatic::Tasks::Task::operator= (Task && other) default
run()
auto fabomatic::Tasks::Task::run () -> void
Execute the task if active.
Definition at line 151 of file Tasks.cpp.
  {
    auto time_to_run = (arduinoNow() - next_run).count() > 0;
    if (isActive() && time_to_run)
    {
      run_counter++;
      auto last_duration = std::chrono::duration_cast<milliseconds>(arduinoNow() - last_run);
      average_tardiness = (average_tardiness * (run_counter - 1) + last_duration) / run_counter;
      last_run = arduinoNow();
      callback();
      total_runtime += std::chrono::duration_cast<milliseconds>(arduinoNow() - last_run);
      if (period > 0ms)
      {
        next_run = last_run + period; // Schedule next run
      }
      else
      {
        next_run = next_run.max(); // Disable the task
      }
      if constexpr (conf::debug::ENABLE_TASK_LOGS)
      {
        ESP_LOGD(TAG, "Completed(%s)\r\n", toString().c_str());
      }
    }
  }
References fabomatic::Tasks::arduinoNow(), fabomatic::conf::debug::ENABLE_TASK_LOGS, and TAG.
setCallback()
auto fabomatic::Tasks::Task::setCallback (std::function< void()> new_callback) -> void
Change the callback function.
Parameters
new_callback function to be called back
Definition at line 204 of file Tasks.cpp.
  {
    callback = new_callback;
  }
setDelay()
auto fabomatic::Tasks::Task::setDelay (milliseconds new_delay) -> void
Change the task initial delay.
Parameters
new_delay Initial delay. Use 0s to avoid any initial delay.
Definition at line 248 of file Tasks.cpp.
  {
    delay = new_delay;
  }
References fabomatic::Tasks::delay().
setPeriod()
auto fabomatic::Tasks::Task::setPeriod (milliseconds new_period) -> void
Change the task period.
Parameters
new_period new period. Use 0ms for single shot.
Definition at line 199 of file Tasks.cpp.
  {
    period = new_period;
  }
toString()
auto fabomatic::Tasks::Task::toString () const -> const std::string
Definition at line 138 of file Tasks.cpp.
  {
    std::stringstream ss{};
    ss << "Task " << getId() << ", active=" << active
       << ",Period(ms)=" << period << ", Delay(ms)=" << delay
       << ",Last run=" << last_run.time_since_epoch()
       << ",Next_run=" << next_run.time_since_epoch()
       << ",Avg tardiness (ms)=" << average_tardiness
       << ",total_runtime (ms)= " << total_runtime
       << ",run_counter=" << run_counter;
    return ss.str();
  }
References active, average_tardiness, delay, getId(), last_run, next_run, period, run_counter, and total_runtime.
Referenced by Task().
updateSchedule()
auto fabomatic::Tasks::Task::updateSchedule () -> void
recompute the next run time (now + delay) and allows the task to run again
recompute the next run time (now + delay)
Definition at line 193 of file Tasks.cpp.
  {
    last_run = arduinoNow() + delay;
    next_run = last_run;
  }
References fabomatic::Tasks::arduinoNow(), and fabomatic::Tasks::delay().
Referenced by fabomatic::Tasks::Scheduler::updateSchedules().
Member Data Documentation
active
bool fabomatic::Tasks::Task::active private
Definition at line 103 of file Tasks.hpp.
Referenced by isActive(), and toString().
average_tardiness
milliseconds fabomatic::Tasks::Task::average_tardiness private
Definition at line 109 of file Tasks.hpp.
Referenced by getAvgTardiness(), and toString().
callback
std::function<void()> fabomatic::Tasks::Task::callback private
Definition at line 111 of file Tasks.hpp.
Referenced by getCallback().
delay
milliseconds fabomatic::Tasks::Task::delay private
Definition at line 106 of file Tasks.hpp.
Referenced by getDelay(), and toString().
id
const std::string fabomatic::Tasks::Task::id private
Definition at line 104 of file Tasks.hpp.
Referenced by getId().
last_run
Tasks::time_point fabomatic::Tasks::Task::last_run private
Definition at line 107 of file Tasks.hpp.
Referenced by Task(), and toString().
next_run
Tasks::time_point fabomatic::Tasks::Task::next_run private
Definition at line 108 of file Tasks.hpp.
Referenced by getNextRun(), and toString().
period
milliseconds fabomatic::Tasks::Task::period private
Definition at line 105 of file Tasks.hpp.
Referenced by getAvgTardiness(), getPeriod(), Task(), and toString().
run_counter
unsigned long fabomatic::Tasks::Task::run_counter private
Definition at line 112 of file Tasks.hpp.
Referenced by getRunCounter(), and toString().
total_runtime
milliseconds fabomatic::Tasks::Task::total_runtime private
Definition at line 110 of file Tasks.hpp.
Referenced by getTotalRuntime(), and toString().
The documentation for this class was generated from the following files:
Tasks.hpp
Tasks.cpp