Fab-O-Matic: fabomatic::Buzzer Class Reference
fabomatic::Buzzer Class Reference
#include <Buzzer.hpp>
Public Member Functions
auto configure () -> void
auto beepOk () const -> void
auto beepFail () const -> void
auto getBeepCount () const -> uint16_t
Private Attributes
uint16_t beepCount {0}
Detailed Description
Definition at line 8 of file Buzzer.hpp.
Member Function Documentation
beepFail()
auto fabomatic::Buzzer::beepFail () const -> void
Definition at line 27 of file Buzzer.cpp.
  {
    if constexpr (conf::buzzer::STANDARD_BEEP_DURATION > 0ms && pins.buzzer.pin != NO_PIN)
    {
      for (auto i = 0; i < conf::buzzer::NB_BEEPS; i++)
      {
        digitalWrite(pins.buzzer.pin, 1);
        Tasks::delay(conf::buzzer::STANDARD_BEEP_DURATION);
        digitalWrite(pins.buzzer.pin, 0);
        Tasks::delay(conf::buzzer::STANDARD_BEEP_DURATION);
        beepCount++;
      }
    }
  }
References beepCount, fabomatic::pins_config::buzzer, fabomatic::Tasks::delay(), fabomatic::conf::buzzer::NB_BEEPS, fabomatic::NO_PIN, fabomatic::pins_config::buzzer_config::pin, fabomatic::pins, and fabomatic::conf::buzzer::STANDARD_BEEP_DURATION.
Referenced by fabomatic::BoardLogic::beepFail().
beepOk()
auto fabomatic::Buzzer::beepOk () const -> void
Definition at line 16 of file Buzzer.cpp.
  {
    if constexpr (conf::buzzer::STANDARD_BEEP_DURATION > 0ms && pins.buzzer.pin != NO_PIN)
    {
      digitalWrite(pins.buzzer.pin, 1);
      Tasks::delay(conf::buzzer::STANDARD_BEEP_DURATION);
      digitalWrite(pins.buzzer.pin, 0);
    }
    beepCount++;
  }
References beepCount, fabomatic::pins_config::buzzer, fabomatic::Tasks::delay(), fabomatic::NO_PIN, fabomatic::pins_config::buzzer_config::pin, fabomatic::pins, and fabomatic::conf::buzzer::STANDARD_BEEP_DURATION.
Referenced by fabomatic::BoardLogic::beepOk().
configure()
auto fabomatic::Buzzer::configure () -> void
Definition at line 9 of file Buzzer.cpp.
  {
    if constexpr (pins.buzzer.pin != NO_PIN)
    {
      pinMode(pins.buzzer.pin, OUTPUT);
    }
  }
References fabomatic::pins_config::buzzer, fabomatic::NO_PIN, fabomatic::pins_config::buzzer_config::pin, and fabomatic::pins.
Referenced by fabomatic::BoardLogic::reconfigure().
getBeepCount()
auto fabomatic::Buzzer::getBeepCount () const -> uint16_t
Definition at line 42 of file Buzzer.cpp.
  {
    return beepCount;
  }
References beepCount.
Member Data Documentation
beepCount
uint16_t fabomatic::Buzzer::beepCount {0} mutable private
Definition at line 11 of file Buzzer.hpp.
{0};
Referenced by beepFail(), beepOk(), and getBeepCount().
The documentation for this class was generated from the following files:
Buzzer.hpp
Buzzer.cpp