Fab-O-Matic: fabomatic::BaseLCDWrapper Class Reference
fabomatic::BaseLCDWrapper Class Reference abstract
#include <BaseLCDWrapper.hpp>
Public Member Functions
virtual ~BaseLCDWrapper ()=default
virtual auto begin () -> bool=0
virtual auto clear () -> void=0
virtual auto showConnection (bool show) -> void=0
virtual auto showPower (bool show) -> void=0
virtual auto setRow (uint8_t row, const std::string_view &text) -> void=0
virtual auto update (const BoardInfo &boardinfo, bool forced=false) -> void=0
auto convertSecondsToHHMMSS (std::chrono::seconds duration) const -> const std::string
Detailed Description
Definition at line 11 of file BaseLCDWrapper.hpp.
Constructor & Destructor Documentation
~BaseLCDWrapper()
virtual fabomatic::BaseLCDWrapper::~BaseLCDWrapper () virtual default
Member Function Documentation
begin()
virtual auto fabomatic::BaseLCDWrapper::begin () -> bool pure virtual
Implemented in fabomatic::LCDWrapper< LcdDriver >.
Referenced by fabomatic::BoardLogic::initBoard().
clear()
virtual auto fabomatic::BaseLCDWrapper::clear () -> void pure virtual
Implemented in fabomatic::LCDWrapper< LcdDriver >.
convertSecondsToHHMMSS()
auto fabomatic::BaseLCDWrapper::convertSecondsToHHMMSS (std::chrono::seconds duration) const -> const std::string
Definition at line 12 of file BaseLCDWrapper.cpp.
  {
    std::stringstream ss{};
    const auto hrs = duration_cast<hours>(duration);
    const auto mins = duration_cast<minutes>(duration - hrs);
    const auto secs = duration_cast<seconds>(duration - hrs - mins);
    ss << std::setfill('0') << std::setw(2) << hrs.count() << ":"
       << std::setfill('0') << std::setw(2) << mins.count() << ":"
       << std::setfill('0') << std::setw(2) << secs.count();
    return ss.str();
  }
setRow()
virtual auto fabomatic::BaseLCDWrapper::setRow (uint8_t row, const std::string_view & text) -> void pure virtual
Implemented in fabomatic::LCDWrapper< LcdDriver >.
Referenced by fabomatic::BoardLogic::longTap().
showConnection()
virtual auto fabomatic::BaseLCDWrapper::showConnection (bool show) -> void pure virtual
Implemented in fabomatic::LCDWrapper< LcdDriver >.
showPower()
virtual auto fabomatic::BaseLCDWrapper::showPower (bool show) -> void pure virtual
Implemented in fabomatic::LCDWrapper< LcdDriver >.
update()
virtual auto fabomatic::BaseLCDWrapper::update (const BoardInfo & boardinfo, bool forced = false) -> void pure virtual
Implemented in fabomatic::LCDWrapper< LcdDriver >.
Referenced by fabomatic::BoardLogic::longTap().
The documentation for this class was generated from the following files:
BaseLCDWrapper.hpp
BaseLCDWrapper.cpp