Fab-O-Matic: fabomatic::Tasks::Scheduler Class Reference
fabomatic::Tasks::Scheduler Class Reference
#include <Tasks.hpp>
Public Member Functions
auto addTask (Task &task) -> void
auto removeTask (const Task &task) -> void
auto execute () const -> void
Execute all tasks that are ready to run.
auto updateSchedules () const -> void
Recompute all the next run times for all the tasks.
auto taskCount () const -> size_t
Gets the number of tasks in the scheduler.
auto getTasks () const -> const std::vector< std::reference_wrapper< Task > >
Get a vector of references to the tasks.
Private Member Functions
auto printStats () const -> void
Private Attributes
std::vector< std::reference_wrapper< Task > > tasks
Detailed Description
The schedule is in charge of running tasks in the right order based on their requested intervals.
Definition at line 110 of file Tasks.hpp.
Member Function Documentation
addTask()
auto fabomatic::Tasks::Scheduler::addTask (Task & task) -> void
Definition at line 17 of file Tasks.cpp.
  {
    tasks.push_back(task);
  }
Referenced by fabomatic::Tasks::Task::Task().
execute()
auto fabomatic::Tasks::Scheduler::execute () const -> void
Execute all tasks that are ready to run.
Tasks will be ordered by next_run time ascending, then run sequentially
Definition at line 81 of file Tasks.cpp.
  {
    // Need a copy to mutate the order
    std::vector mutableTasks(tasks.begin(), tasks.end());
    // Tasks shall be run in order of expiration (the most expired task shall run first)
    std::sort(mutableTasks.begin(), mutableTasks.end(), [](const Task &a, const Task &b)
              { return a.getNextRun() < b.getNextRun(); });
    // Now iterate over the sorted tasks to run the tasks
    for (const auto &it : mutableTasks)
    {
      it.get().run();
    }
    if (conf::debug::ENABLE_TASK_LOGS && millis() % 1024 == 0)
    {
      printStats();
    }
#if (PINS_WOKWI)
    else
    {
      ::delay(5); // Wokwi simulation is sometimes slow and this helps to catch-up
    }
#endif
  }
References fabomatic::Tasks::delay(), fabomatic::conf::debug::ENABLE_TASK_LOGS, printStats(), and tasks.
Referenced by loop(), and fabomatic::tests::test_normal_use().
getTasks()
auto fabomatic::Tasks::Scheduler::getTasks () const -> const std::vector<std::reference_wrapper<Task>>
Get a vector of references to the tasks.
Definition at line 113 of file Tasks.cpp.
  {
    return {tasks};
  }
References tasks.
Referenced by fabomatic::tests::test_normal_use().
printStats()
auto fabomatic::Tasks::Scheduler::printStats () const -> void private
Definition at line 38 of file Tasks.cpp.
  {
    milliseconds avg_delay = 0ms;
    auto nb_runs = 0;
    for (const auto &task : tasks)
    {
      avg_delay += task.get().getAvgTardiness() * task.get().getRunCounter();
      nb_runs += task.get().getRunCounter();
    }
    if (nb_runs > 0)
    {
      avg_delay /= nb_runs;
    }
    ESP_LOGD(TAG, "Scheduler::execute complete: %d tasks total, %d runs, avg delay/run: %llu ms\r\n", tasks.size(), nb_runs, avg_delay.count());
    for (const auto &task : tasks)
    {
      if (task.get().isActive())
      {
        if (task.get().getRunCounter() > 0)
        {
          ESP_LOGD(TAG, "\t Task: %s, %lu runs, avg tardiness/run: %llu ms, period %llu ms, delay %llu ms, average task duration %llu ms\r\n",
                   task.get().getId().c_str(), task.get().getRunCounter(),
                   task.get().getAvgTardiness().count(), task.get().getPeriod().count(),
                   task.get().getDelay().count(),
                   task.get().getTotalRuntime().count() / task.get().getRunCounter());
        }
        else
        {
          ESP_LOGD(TAG, "\t Task: %s, never ran, period %llu ms, delay %llu ms\r\n",
                   task.get().getId().c_str(), task.get().getPeriod().count(),
                   task.get().getDelay().count());
        }
      }
      else
      {
        ESP_LOGD(TAG, "\t Task: %s, inactive\r\n", task.get().getId().c_str());
      }
    }
  }
References TAG, and tasks.
Referenced by execute().
removeTask()
auto fabomatic::Tasks::Scheduler::removeTask (const Task & task) -> void
Definition at line 22 of file Tasks.cpp.
  {
    tasks.erase(std::remove_if(tasks.begin(), tasks.end(),
                               [&task](const auto &t)
                               { return t.get().getId() == task.getId(); }),
                tasks.end());
  }
Referenced by fabomatic::tests::delete_tasks().
taskCount()
auto fabomatic::Tasks::Scheduler::taskCount () const -> size_t
Gets the number of tasks in the scheduler.
Definition at line 108 of file Tasks.cpp.
  {
    return tasks.size();
  }
References tasks.
Referenced by fabomatic::tests::test_execute_runs_all_tasks(), fabomatic::tests::test_normal_use(), and fabomatic::tests::test_stop_start_tasks().
updateSchedules()
auto fabomatic::Tasks::Scheduler::updateSchedules () const -> void
Recompute all the next run times for all the tasks.
Definition at line 30 of file Tasks.cpp.
  {
    for (const auto &task : tasks)
    {
      task.get().updateSchedule();
    }
  }
References tasks, and fabomatic::Tasks::Task::updateSchedule().
Referenced by setup(), and fabomatic::tests::test_normal_use().
Member Data Documentation
tasks
std::vector<std::reference_wrapper<Task> > fabomatic::Tasks::Scheduler::tasks private
Definition at line 130 of file Tasks.hpp.
Referenced by execute(), getTasks(), printStats(), taskCount(), and updateSchedules().
The documentation for this class was generated from the following files:
Tasks.hpp
Tasks.cpp