Fab-O-Matic: fabomatic::Machine Class Reference
fabomatic::Machine Class Reference
#include <Machine.hpp>
Public Types
enum class PowerState : uint8_t { Unknown , PoweredOn , WaitingPowerOff , PoweredOff }
Public Member Functions
Machine ()=default
~Machine ()=default
Machine (const Machine &)=delete
Machine & operator= (const Machine &x)=delete
Machine (Machine &&)=delete
Machine & operator= (Machine &&)=delete
auto getActiveUser () const -> FabUser
void configure (const MachineConfig &new_config, FabBackend &serv)
Configure the machine, it must be called before most methods.
auto getMachineId () const -> MachineID
Returns the machine identifier.
auto getMachineName () const -> const std::string
auto getUsageDuration () const -> std::chrono::seconds
Duration of the current usage, or 0s.
auto getAutologoffDelay () const -> std::chrono::seconds
auto getGracePeriod () const -> std::chrono::seconds
auto login (const FabUser &user) -> bool
Try to login the user and start the usage timer.
auto logout () -> void
Logoff the user and stop the usage timer.
auto setAutologoffDelay (std::chrono::seconds new_delay) -> void
Sets the delay after which the user will be logged off automatically.
auto setGracePeriod (std::chrono::seconds new_delay) -> void
Sets the idle period after which the machine will power off automatically.
auto power (bool on_or_off) -> void
Powers the machine on or off using relay/MQTT/both.
auto setMachineName (const std::string &new_name) -> void
Sets the machine name as per backend configuration.
auto setMachineType (MachineType new_type) -> void
Sets the machine type as per backend configuration.
auto getPowerState () const -> PowerState
Returns the current power state of the machine.
auto isShutdownImminent () const -> bool
Indicates if the machine will power down in less than BEEP_REMAINING_MINUTES.
auto isFree () const -> bool
Indicates is the machine is not used by anybody.
auto canPowerOff () const -> bool
Indicates if POWEROFF_DELAY_MINUTES delay has expired,and the machine is still idle.
auto toString () const -> const std::string
auto isAutologoffExpired () const -> bool
Indicates ff the user shall be logged off automatically.
auto isConfigured () const -> bool
Indicates if the machine has been configured.
auto getConfig () const -> std::optional< MachineConfig >
Returns the current configuration of the machine, used for testing.
auto isAllowed () const -> bool
auto setAllowed (bool new_allowed) -> void
auto isMaintenanceNeeded () const -> bool
auto setMaintenanceNeeded (bool new_maintenance_needed) -> void
auto getMaintenanceInfo () const -> const std::string
auto setMaintenanceInfo (const std::string &new_description) -> void
Private Member Functions
auto power_mqtt (bool on_or_off) -> void
sets the machine power to on (true) or off (false)
auto power_relay (bool on_or_off) -> void
sets the machine power to on (true) or off (false)
Private Attributes
std::optional< MachineConfig > config {std::nullopt}
std::optional< std::reference_wrapper< FabBackend > > server {std::nullopt}
bool active {false}
FabUser current_user {}
std::optional< std::chrono::time_point< std::chrono::system_clock > > usage_start_timestamp {std::nullopt}
std::optional< std::chrono::time_point< std::chrono::system_clock > > logoff_timestamp {std::nullopt}
PowerState power_state {PowerState::PoweredOff}
bool maintenanceNeeded {false}
If true, machine needs maintenance.
bool allowed {true}
If true, machine is allowed to be used by anybody.
std::string maintenanceInfo {""}
Detailed Description
Definition at line 14 of file Machine.hpp.
Member Enumeration Documentation
PowerState
enum class fabomatic::Machine::PowerState : uint8_t strong
Enumerator
Unknown
PoweredOn
WaitingPowerOff
PoweredOff
Definition at line 17 of file Machine.hpp.
    {
      Unknown,
      PoweredOn,
      WaitingPowerOff,
      PoweredOff,
    };
Constructor & Destructor Documentation
Machine() [1/3]
fabomatic::Machine::Machine () default
~Machine()
fabomatic::Machine::~Machine () default
Machine() [2/3]
fabomatic::Machine::Machine (const Machine &) delete
Machine() [3/3]
fabomatic::Machine::Machine (Machine &&) delete
Member Function Documentation
canPowerOff()
auto fabomatic::Machine::canPowerOff () const -> bool
Indicates if POWEROFF_DELAY_MINUTES delay has expired,and the machine is still idle.
indicates if the machine can be powered off
Returns
true if the grace period has expired
Definition at line 110 of file Machine.cpp.
  {
    if (!logoff_timestamp.has_value())
      return false;
    CHECK_CONFIGURED(bool);
    return (power_state == PowerState::WaitingPowerOff &&
            std::chrono::system_clock::now() - logoff_timestamp.value() > config.value().grace_period);
  }
References CHECK_CONFIGURED, config, logoff_timestamp, power_state, and WaitingPowerOff.
Referenced by fabomatic::BoardLogic::checkPowerOff().
configure()
auto fabomatic::Machine::configure (const MachineConfig & new_config, FabBackend & serv)
Configure the machine, it must be called before most methods.
Definition at line 25 of file Machine.cpp.
  {
    // https://stackoverflow.com/questions/67596731/why-is-stdoptionaltoperator-deleted-when-t-contains-a-const-data-memb
    config.emplace(new_config);
    server = std::reference_wrapper<FabBackend>(serv);
    if (config.value().hasRelay())
    {
      const auto pin = config.value().relay_config.ch1_pin;
      digitalWrite(pin,
                   config.value().relay_config.active_low ? HIGH : LOW);
      pinMode(pin, OUTPUT);
      // Relay coil requires some juice
      gpio_set_drive_capability(static_cast<gpio_num_t>(pin), GPIO_DRIVE_CAP_3);
    }
    ESP_LOGD(TAG, "Machine configured : %s", toString().c_str());
  }
References TAG.
Referenced by fabomatic::BoardLogic::reconfigure().
getActiveUser()
auto fabomatic::Machine::getActiveUser () const -> FabUser
Definition at line 219 of file Machine.cpp.
  {
    return current_user;
  }
References current_user.
Referenced by fabomatic::BoardLogic::authorize(), fabomatic::BoardLogic::logout(), fabomatic::BoardLogic::onNewCard(), and fabomatic::BoardLogic::updateLCD().
getAutologoffDelay()
auto fabomatic::Machine::getAutologoffDelay () const -> std::chrono::seconds
Definition at line 269 of file Machine.cpp.
  {
    CHECK_CONFIGURED(std::chrono::seconds);
    return config.value().autologoff;
  }
References CHECK_CONFIGURED, and config.
Referenced by isAutologoffExpired().
getConfig()
auto fabomatic::Machine::getConfig () const -> std::optional<MachineConfig>
Returns the current configuration of the machine, used for testing.
Definition at line 321 of file Machine.cpp.
  {
    return config;
  }
References config.
getGracePeriod()
auto fabomatic::Machine::getGracePeriod () const -> std::chrono::seconds
Definition at line 346 of file Machine.cpp.
  {
    CHECK_CONFIGURED(std::chrono::seconds);
    return config.value().grace_period;
  }
References CHECK_CONFIGURED, and config.
Referenced by toString().
getMachineId()
auto fabomatic::Machine::getMachineId () const -> MachineID
Returns the machine identifier.
Returns
Machine identifier
Definition at line 48 of file Machine.cpp.
  {
    CHECK_CONFIGURED(MachineID);
    return config.value().machine_id;
  }
References CHECK_CONFIGURED, and config.
Referenced by fabomatic::BoardLogic::refreshFromServer(), and toString().
getMachineName()
auto fabomatic::Machine::getMachineName () const -> const std::string
Definition at line 235 of file Machine.cpp.
  {
    CHECK_CONFIGURED(std::string);
    return std::string{config.value().machine_name.data()};
  }
References CHECK_CONFIGURED, and config.
Referenced by toString(), and fabomatic::BoardLogic::updateLCD().
getMaintenanceInfo()
auto fabomatic::Machine::getMaintenanceInfo () const -> const std::string
Definition at line 365 of file Machine.cpp.
  {
    return maintenanceInfo;
  }
References maintenanceInfo.
Referenced by fabomatic::BoardLogic::updateLCD().
getPowerState()
auto fabomatic::Machine::getPowerState () const -> PowerState
Returns the current power state of the machine.
Returns
Definition at line 80 of file Machine.cpp.
  {
    return power_state;
  }
References power_state.
Referenced by fabomatic::BoardLogic::longTap(), toString(), and fabomatic::BoardLogic::updateLCD().
getUsageDuration()
auto fabomatic::Machine::getUsageDuration () const -> std::chrono::seconds
Duration of the current usage, or 0s.
Gets the duration the machine has been used.
Returns
milliseconds since the machine has been started
Definition at line 226 of file Machine.cpp.
  {
    if (usage_start_timestamp.has_value())
    {
      return std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now() - usage_start_timestamp.value());
    }
    return 0s;
  }
References usage_start_timestamp.
Referenced by isAutologoffExpired(), fabomatic::BoardLogic::logout(), toString(), and fabomatic::BoardLogic::updateLCD().
isAllowed()
auto fabomatic::Machine::isAllowed () const -> bool
Definition at line 326 of file Machine.cpp.
  {
    return allowed;
  }
References allowed.
Referenced by fabomatic::BoardLogic::authorize(), fabomatic::BoardLogic::blinkLed(), and fabomatic::BoardLogic::updateLCD().
isAutologoffExpired()
auto fabomatic::Machine::isAutologoffExpired () const -> bool
Indicates ff the user shall be logged off automatically.
Definition at line 288 of file Machine.cpp.
  {
    return getAutologoffDelay() > 0min &&
           getUsageDuration() > getAutologoffDelay();
  }
References getAutologoffDelay(), and getUsageDuration().
isConfigured()
auto fabomatic::Machine::isConfigured () const -> bool
Indicates if the machine has been configured.
Definition at line 316 of file Machine.cpp.
  {
    return config.has_value() && server.has_value();
  }
References config, and server.
Referenced by fabomatic::BoardLogic::updateLCD().
isFree()
auto fabomatic::Machine::isFree () const -> bool
Indicates is the machine is not used by anybody.
Indicates whether the machine is used by somebody.
Returns
boolean
Definition at line 56 of file Machine.cpp.
  {
    return !active;
  }
References active.
Referenced by fabomatic::BoardLogic::blinkLed(), fabomatic::BoardLogic::checkRfid(), fabomatic::BoardLogic::onNewCard(), and toString().
isMaintenanceNeeded()
auto fabomatic::Machine::isMaintenanceNeeded () const -> bool
Definition at line 336 of file Machine.cpp.
  {
    return maintenanceNeeded;
  }
References maintenanceNeeded.
Referenced by fabomatic::BoardLogic::authorize(), fabomatic::BoardLogic::blinkLed(), and fabomatic::BoardLogic::updateLCD().
isShutdownImminent()
auto fabomatic::Machine::isShutdownImminent () const -> bool
Indicates if the machine will power down in less than BEEP_REMAINING_MINUTES.
indicates if the machine is about to shudown and board should beep
Returns
true if shutdown is imminent (within grace_period after last logoff)
Definition at line 123 of file Machine.cpp.
  {
    if (!logoff_timestamp.has_value())
      return false;
    CHECK_CONFIGURED(bool);
    return (power_state == PowerState::WaitingPowerOff &&
            std::chrono::system_clock::now() - logoff_timestamp.value() <= config.value().grace_period);
  }
References CHECK_CONFIGURED, config, logoff_timestamp, power_state, and WaitingPowerOff.
Referenced by fabomatic::BoardLogic::blinkLed(), fabomatic::BoardLogic::longTap(), toString(), and fabomatic::BoardLogic::updateLCD().
login()
auto fabomatic::Machine::login (const FabUser & user) -> bool
Try to login the user and start the usage timer.
Log the given user onto the machine, if free and not blocked.
Parameters
user user to login
Returns
true of the user has been successfully logged in
Definition at line 64 of file Machine.cpp.
  {
    CHECK_CONFIGURED(bool);
    if (isFree() && allowed)
    {
      active = true;
      current_user = user;
      power(true);
      usage_start_timestamp = std::chrono::system_clock::now();
      return true;
    }
    return false;
  }
References CHECK_CONFIGURED.
Referenced by fabomatic::BoardLogic::authorize().
logout()
auto fabomatic::Machine::logout () -> void
Logoff the user and stop the usage timer.
Removes the user from the machine, and powers off the machine (respecting POWEROFF_DELAY_MINUTES setting)
Definition at line 86 of file Machine.cpp.
  {
    CHECK_CONFIGURED(void);
    if (active)
    {
      active = false;
      power_state = PowerState::WaitingPowerOff;
      usage_start_timestamp = std::nullopt;
      // Sets the countdown to power off
      logoff_timestamp = std::chrono::system_clock::now();
      if (config.value().grace_period == 0s)
      {
        power(false);
      }
      ESP_LOGI(TAG, "Machine will be shutdown in %lld s",
               config.value().grace_period.count());
    }
  }
References CHECK_CONFIGURED, and TAG.
Referenced by fabomatic::BoardLogic::logout().
operator=() [1/2]
Machine & fabomatic::Machine::operator= (const Machine & x) delete
operator=() [2/2]
Machine & fabomatic::Machine::operator= (Machine &&) delete
power()
auto fabomatic::Machine::power (bool on_or_off) -> void
Powers the machine on or off using relay/MQTT/both.
Parameters
on_or_off new power state
Definition at line 203 of file Machine.cpp.
  {
    CHECK_CONFIGURED(void);
    ESP_LOGI(TAG, "Machine::power : power set to %d", on_or_off);
    if (config.value().hasRelay())
    {
      power_relay(on_or_off);
    }
    if (config.value().hasMqttSwitch())
    {
      power_mqtt(on_or_off);
    }
  }
References CHECK_CONFIGURED, and TAG.
Referenced by fabomatic::BoardLogic::checkPowerOff().
power_mqtt()
auto fabomatic::Machine::power_mqtt (bool value) -> void private
sets the machine power to on (true) or off (false)
Parameters
value setpoint
Definition at line 165 of file Machine.cpp.
  {
    CHECK_CONFIGURED(void);
    ESP_LOGI(TAG, "Machine::power_mqtt : power set to %d", value);
    auto &mqtt_server = server.value().get();
    const auto &sw_topic = config.value().mqtt_switch_topic;
    String topic{sw_topic.data()};
    String payload = value ? conf::default_config::mqtt_switch_on_message.data() : conf::default_config::mqtt_switch_on_message.data();
    auto retries = 0;
    while (!mqtt_server.publish(topic, payload, false))
    {
      ESP_LOGE(TAG, "Error while publishing %s to %s", payload.c_str(), topic.c_str());
      mqtt_server.connect();
      Tasks::delay(conf::mqtt::TIMEOUT_REPLY_SERVER);
      retries++;
      if (retries > conf::mqtt::MAX_TRIES)
      {
        ESP_LOGW(TAG, "Unable to publish to MQTT (%d/%d)", retries, conf::mqtt::MAX_TRIES);
        return;
      }
    }
    if (value)
    {
      logoff_timestamp = std::nullopt;
      power_state = PowerState::PoweredOn;
    }
    else
    {
      power_state = PowerState::PoweredOff;
    }
  }
References CHECK_CONFIGURED, fabomatic::Tasks::delay(), fabomatic::conf::mqtt::MAX_TRIES, fabomatic::conf::default_config::mqtt_switch_on_message, TAG, and fabomatic::conf::mqtt::TIMEOUT_REPLY_SERVER.
power_relay()
auto fabomatic::Machine::power_relay (bool value) -> void private
sets the machine power to on (true) or off (false)
Parameters
value setpoint
Definition at line 136 of file Machine.cpp.
  {
    CHECK_CONFIGURED(void);
    ESP_LOGI(TAG, "Machine::power_relay : power set to %d", value);
    const auto pin = config.value().relay_config.ch1_pin;
    if (config.value().relay_config.active_low)
    {
      digitalWrite(pin, value ? LOW : HIGH);
    }
    else
    {
      digitalWrite(pin, value ? HIGH : LOW);
    }
    if (value)
    {
      logoff_timestamp = std::nullopt;
      power_state = PowerState::PoweredOn;
    }
    else
    {
      power_state = PowerState::PoweredOff;
    }
  }
References CHECK_CONFIGURED, and TAG.
setAllowed()
auto fabomatic::Machine::setAllowed (bool new_allowed) -> void
Definition at line 331 of file Machine.cpp.
  {
    allowed = new_allowed;
  }
Referenced by fabomatic::BoardLogic::refreshFromServer().
setAutologoffDelay()
auto fabomatic::Machine::setAutologoffDelay (std::chrono::seconds new_delay) -> void
Sets the delay after which the user will be logged off automatically.
Definition at line 275 of file Machine.cpp.
  {
    CHECK_CONFIGURED(void);
    if (config.value().autologoff != new_delay)
    {
      ESP_LOGD(TAG, "Changing autologoff delay to %lld min",
               std::chrono::duration_cast<std::chrono::minutes>(config.value().autologoff).count());
    }
    config.value().autologoff = new_delay;
  }
References CHECK_CONFIGURED, and TAG.
Referenced by fabomatic::BoardLogic::refreshFromServer().
setGracePeriod()
auto fabomatic::Machine::setGracePeriod (std::chrono::seconds new_delay) -> void
Sets the idle period after which the machine will power off automatically.
Definition at line 352 of file Machine.cpp.
  {
    CHECK_CONFIGURED(void);
    if (config.value().grace_period != new_delay)
    {
      ESP_LOGD(TAG, "Changing grace period to %lld seconds",
               new_delay.count());
    }
    config.value().grace_period = new_delay;
  }
References CHECK_CONFIGURED, and TAG.
Referenced by fabomatic::BoardLogic::refreshFromServer().
setMachineName()
auto fabomatic::Machine::setMachineName (const std::string & new_name) -> void
Sets the machine name as per backend configuration.
Parameters
new_name Will be shown on LCD, keep it short.
Definition at line 294 of file Machine.cpp.
  {
    CHECK_CONFIGURED(void);
    if (config.value().machine_name != new_name)
    {
      ESP_LOGD(TAG, "Changing machine name to %s", new_name.data());
    }
    config.value().machine_name = new_name;
  }
References CHECK_CONFIGURED, and TAG.
Referenced by fabomatic::BoardLogic::refreshFromServer().
setMachineType()
auto fabomatic::Machine::setMachineType (MachineType new_type) -> void
Sets the machine type as per backend configuration.
Definition at line 306 of file Machine.cpp.
  {
    CHECK_CONFIGURED(void);
    if (config.value().machine_type != new_type)
      ESP_LOGD(TAG, "Changing machine type to %d", static_cast<uint8_t>(new_type));
    config.value().machine_type = new_type;
  }
References CHECK_CONFIGURED, and TAG.
Referenced by fabomatic::BoardLogic::refreshFromServer().
setMaintenanceInfo()
auto fabomatic::Machine::setMaintenanceInfo (const std::string & new_description) -> void
Definition at line 370 of file Machine.cpp.
  {
    maintenanceInfo = new_description;
  }
Referenced by fabomatic::BoardLogic::refreshFromServer().
setMaintenanceNeeded()
auto fabomatic::Machine::setMaintenanceNeeded (bool new_maintenance_needed) -> void
Definition at line 341 of file Machine.cpp.
  {
    maintenanceNeeded = new_maintenance_needed;
  }
Referenced by fabomatic::BoardLogic::authorize(), and fabomatic::BoardLogic::refreshFromServer().
toString()
auto fabomatic::Machine::toString () const -> const std::string
Definition at line 241 of file Machine.cpp.
  {
    std::stringstream sstream{};
    if (!config.has_value() || !server.has_value())
    {
      sstream << "Machine (not configured)";
      return sstream.str();
    }
    sstream << "Machine (ID:" << getMachineId().id;
    sstream << ", Name:" << getMachineName();
    sstream << ", IsFree: " << isFree();
    sstream << ", IsAllowed:" << allowed;
    sstream << ", PowerState:" << static_cast<int>(getPowerState());
    sstream << ", " << current_user.toString();
    sstream << ", UsageDuration (s):" << getUsageDuration().count();
    sstream << ", ShutdownImminent:" << isShutdownImminent();
    sstream << ", MaintenanceNeeded:" << maintenanceNeeded;
    sstream << ", " << config.value().toString();
    sstream << ", Active:" << active;
    sstream << ", Last logoff:" << (logoff_timestamp.has_value() ? logoff_timestamp.value().time_since_epoch().count() : 0);
    sstream << ", GracePeriod (s):" << getGracePeriod().count();
    sstream << ")";
    return sstream.str();
  }
References active, allowed, config, current_user, getGracePeriod(), getMachineId(), getMachineName(), getPowerState(), getUsageDuration(), isFree(), isShutdownImminent(), logoff_timestamp, maintenanceNeeded, server, and fabomatic::FabUser::toString().
Referenced by fabomatic::BoardLogic::refreshFromServer().
Field Documentation
active
bool fabomatic::Machine::active {false} private
Definition at line 105 of file Machine.hpp.
{false};
Referenced by isFree(), and toString().
allowed
bool fabomatic::Machine::allowed {true} private
If true, machine is allowed to be used by anybody.
Definition at line 115 of file Machine.hpp.
{true};
Referenced by isAllowed(), and toString().
config
std::optional<MachineConfig> fabomatic::Machine::config {std::nullopt} private
Definition at line 102 of file Machine.hpp.
{std::nullopt};
Referenced by canPowerOff(), getAutologoffDelay(), getConfig(), getGracePeriod(), getMachineId(), getMachineName(), isConfigured(), isShutdownImminent(), and toString().
current_user
FabUser fabomatic::Machine::current_user {} private
Definition at line 106 of file Machine.hpp.
{};
Referenced by getActiveUser(), and toString().
logoff_timestamp
std::optional<std::chrono::time_point<std::chrono::system_clock> > fabomatic::Machine::logoff_timestamp {std::nullopt} private
Definition at line 109 of file Machine.hpp.
{std::nullopt};      // When did the last user log off?
Referenced by canPowerOff(), isShutdownImminent(), and toString().
maintenanceInfo
std::string fabomatic::Machine::maintenanceInfo {""} private
Definition at line 117 of file Machine.hpp.
{""};
Referenced by getMaintenanceInfo().
maintenanceNeeded
bool fabomatic::Machine::maintenanceNeeded {false} private
If true, machine needs maintenance.
Definition at line 113 of file Machine.hpp.
{false};
Referenced by isMaintenanceNeeded(), and toString().
power_state
PowerState fabomatic::Machine::power_state {PowerState::PoweredOff} private
Definition at line 110 of file Machine.hpp.
{PowerState::PoweredOff};
Referenced by canPowerOff(), getPowerState(), and isShutdownImminent().
server
std::optional<std::reference_wrapper<FabBackend> > fabomatic::Machine::server {std::nullopt} private
Definition at line 103 of file Machine.hpp.
{std::nullopt};
Referenced by isConfigured(), and toString().
usage_start_timestamp
std::optional<std::chrono::time_point<std::chrono::system_clock> > fabomatic::Machine::usage_start_timestamp {std::nullopt} private
Definition at line 108 of file Machine.hpp.
{std::nullopt}; // When did the machine start?
Referenced by getUsageDuration().
The documentation for this class was generated from the following files:
Machine.hpp
Machine.cpp