Fab-O-Matic: fabomatic::MockMQTTBroker Class Reference
fabomatic::MockMQTTBroker Class Reference final
This class implements an MQTT broker with predefined responses to FabBackend requests.
#include <MockMQTTBroker.hpp>
Classes
struct query
Public Member Functions
MockMQTTBroker ()=default
auto isRunning () const -> bool
Checks if the MQTT broker is running.
auto start () -> void
Starts the MQTT broker.
auto onEvent (sMQTTEvent *event) -> bool override
Handles MQTT events.
auto defaultReplies (const std::string &query) const -> const std::string
Provides fake server replies for testing purposes.
auto configureReplies (std::function< const std::string(const std::string &, const std::string &)> callback) -> void
set the reply generation function. May be called from a different thread
auto processQueries () -> size_t
Processes pending MQTT queries.
auto mainLoop () -> void
Main loop for the MQTT broker.
Private Attributes
std::mutex mutex
std::string topic {""}
std::string payload {""}
std::queue< query > queries {}
std::function< const std::string(const std::string &, const std::string &)> callback
bool is_running {false}
Detailed Description
This class implements an MQTT broker with predefined responses to FabBackend requests.
Definition at line 15 of file MockMQTTBroker.hpp.
Constructor & Destructor Documentation
MockMQTTBroker()
fabomatic::MockMQTTBroker::MockMQTTBroker () default
Member Function Documentation
configureReplies()
auto fabomatic::MockMQTTBroker::configureReplies (std::function< const std::string(const std::string &, const std::string &)> callback) -> void
set the reply generation function. May be called from a different thread
Configures custom replies for MQTT queries.
Parameters
callback
callback A function that takes a topic and query as input and returns the corresponding response.
Definition at line 199 of file MockMQTTBroker.cpp.
  {
    std::lock_guard<std::mutex> lock(mutex);
    this->callback = callback;
  }
defaultReplies()
auto fabomatic::MockMQTTBroker::defaultReplies (const std::string & query) const -> const std::string
Provides fake server replies for testing purposes.
Parameters
query The query string to determine the appropriate response.
Returns
The JSON payload response as a string.
Definition at line 120 of file MockMQTTBroker.cpp.
  {
    if (query.find("checkmachine") != std::string::npos)
    {
      return "{\"request_ok\":true,\"is_valid\":true,\"allowed\":true,\"maintenance\":false,\"logoff\":30,\"name\":\"ENDER_1\",\"type\":1,\"description\":\"\"}";
    }
    if (query.find("maintenance") != std::string::npos)
    {
      return "{\"request_ok\":true}";
    }
    if (query.find("startuse") != std::string::npos)
    {
      return "{\"request_ok\":true}";
    }
    if (query.find("inuse") != std::string::npos)
    {
      return "{\"request_ok\":true}";
    }
    if (query.find("stopuse") != std::string::npos)
    {
      return "{\"request_ok\":true}";
    }
    if (query.find("checkuser") != std::string::npos)
    {
      JsonDocument doc;
      if (deserializeJson(doc, query) == DeserializationError::Ok && doc.containsKey("uid"))
      {
        const auto uid_str = doc["uid"].as<std::string>();
        // Check if the uid is present in the secrets::cards::whitelist
        const auto elem = std::find_if(secrets::cards::whitelist.begin(), secrets::cards::whitelist.end(),
                                       [&uid_str](const auto &elem)
{
                                         const auto &[id, level, name] = elem;
                                         return card::uid_str(id) == uid_str;
                                       });
        if (elem != secrets::cards::whitelist.end())
        {
          std::stringstream ss;
          const auto &[id, level, name] = *elem;
          ss << "{\"request_ok\":true,\"is_valid\":" << (level != FabUser::UserLevel::Unknown ? "true" : "false")
             << ",\"level\":" << +static_cast<uint8_t>(level)
             << ",\"name\":\"" << name << "\"}";
          return ss.str();
        }
        // Still return a valid user
        std::stringstream ss;
        ss << "{\"request_ok\":true,\"is_valid\":true,\"level\":" << +2
           << ",\"name\":\"User" << uid_str << "\"}";
        return ss.str();
      }
      ESP_LOGE(TAG2, "Failed to parse checkuser query");
      return "{\"request_ok\":false}";
    }
    if (query.find("alive") != std::string::npos)
    {
      return ""; // No reply to alive message
    }
    if (query.find(conf::mqtt::mqtt_switch_topic) != std::string::npos) // Shelly doesn't reply
    {
      return "";
    }
    return std::string{"{\"request_ok\":true}"};
  }
References fabomatic::conf::mqtt::mqtt_switch_topic, TAG2, fabomatic::card::uid_str(), fabomatic::FabUser::Unknown, and fabomatic::secrets::cards::whitelist.
isRunning()
auto fabomatic::MockMQTTBroker::isRunning () const -> bool
Checks if the MQTT broker is running.
Returns
true if the broker is running, false otherwise.
Definition at line 109 of file MockMQTTBroker.cpp.
  {
    return is_running;
  }
References is_running.
Referenced by mainLoop(), and fabomatic::tests::test_start_broker().
mainLoop()
void fabomatic::MockMQTTBroker::mainLoop () -> void
Main loop for the MQTT broker.
This function checks if the broker is running. If not, it starts the broker. If the broker is running, it updates the broker state and processes pending queries.
Definition at line 239 of file MockMQTTBroker.cpp.
  {
    // Check if the server is online
    if (!isRunning())
    {
      start();
    }
    else
    {
      update();
      processQueries();
    }
  }
References isRunning(), processQueries(), and start().
Referenced by fabomatic::tests::threadMQTTServer().
onEvent()
auto fabomatic::MockMQTTBroker::onEvent (sMQTTEvent * event) -> bool override
Handles MQTT events.
Parameters
event Pointer to the sMQTTEvent object containing event details.
Returns
true if the event was handled successfully, false otherwise.
This function handles various types of MQTT events such as new client connections, message publications, client removals, connection losses, subscriptions, and unsubscriptions.
Definition at line 46 of file MockMQTTBroker.cpp.
  {
    switch (event->Type())
    {
    case NewClient_sMQTTEventType:
    {
      // Handle new client connection event
      auto *e = static_cast<sMQTTNewClientEvent *>(event);
      ESP_LOGD(TAG2, "MQTT BROKER: client connected, id:%s", e->Client()->getClientId().c_str());
    }
    break;
    case Public_sMQTTEventType:
    {
      // Handle publish event
      std::lock_guard<std::mutex> lock(mutex);
      auto *e = static_cast<sMQTTPublicClientEvent *>(event);
      topic = e->Topic();
      payload = e->Payload();
      ESP_LOGI(TAG2, "MQTT BROKER: Received  %s -> %s", topic.c_str(), payload.c_str());
      queries.push({topic, payload, topic + "/reply"});
    }
    break;
    case RemoveClient_sMQTTEventType:
    {
      // Handle client removal event
      auto *e = static_cast<sMQTTRemoveClientEvent *>(event);
      ESP_LOGD(TAG2, "MQTT BROKER: removed client id: %s", e->Client()->getClientId().c_str());
    }
    break;
    case LostConnect_sMQTTEventType:
    {
      // Handle lost connection event
      is_running = false;
      ESP_LOGD(TAG2, "MQTT BROKER: lost connection");
    }
    break;
    case Subscribe_sMQTTEventType:
    {
      // Handle subscription event
      auto *e = static_cast<sMQTTSubUnSubClientEvent *>(event);
      ESP_LOGD(TAG2, "MQTT BROKER: client %s subscribed to %s", e->Client()->getClientId().c_str(), e->Topic().c_str());
    }
    break;
    case UnSubscribe_sMQTTEventType:
    {
      // Handle unsubscription event
      auto *e = static_cast<sMQTTSubUnSubClientEvent *>(event);
      ESP_LOGD(TAG2, "MQTT BROKER: got unsubscribe from %s", e->Topic().c_str());
    }
    break;
    default:
      ESP_LOGD(TAG2, "MQTT BROKER: unhandled event %d", event->Type());
      break;
    }
    return true;
  }
References TAG2.
processQueries()
auto fabomatic::MockMQTTBroker::processQueries () -> size_t
Processes pending MQTT queries.
Returns
The number of remaining queries.
This function processes the queries in the queue by invoking the configured callback function and publishes the response to the corresponding reply topic.
Definition at line 213 of file MockMQTTBroker.cpp.
  {
    std::lock_guard<std::mutex> lock(mutex);
    if (!queries.empty())
    {
      std::string response{""};
      const auto [topic, query, reply_topic] = queries.front();
      queries.pop();
      response = callback(topic, query);
      if (!response.empty())
      {
        ESP_LOGI(TAG2, "MQTT BROKER: Sending %s -> %s", reply_topic.c_str(), response.c_str());
        publish(reply_topic, response);
      }
    }
    return queries.size();
  }
References TAG2.
Referenced by mainLoop().
start()
auto fabomatic::MockMQTTBroker::start () -> void
Starts the MQTT broker.
This function checks if the Wi-Fi is connected and initializes the MQTT broker. If the Wi-Fi is not connected, it logs the status and returns. If the broker is not running, it initializes the broker with the configured port number.
Definition at line 20 of file MockMQTTBroker.cpp.
  {
    // Wait for the Wi-Fi to connect
    while (WiFi.status() != WL_CONNECTED)
    {
      ESP_LOGD(TAG2, "MQTT BROKER: WiFi status changed to %d", WiFi.status());
      is_running = false;
      return;
    }
    // Initialize the broker if it's not running
    if (!is_running)
    {
      is_running = init(conf::mqtt::PORT_NUMBER, true);
      ESP_LOGI(TAG2, "MQTT BROKER: started with result %d", is_running);
    }
  }
References fabomatic::conf::mqtt::PORT_NUMBER, and TAG2.
Referenced by mainLoop().
Member Data Documentation
callback
std::function<const std::string(const std::string &, const std::string &)> fabomatic::MockMQTTBroker::callback private
Initial value:
= [this](const std::string &topic, const std::string &query)
    { return defaultReplies(query); }
Definition at line 45 of file MockMQTTBroker.hpp.
    { return defaultReplies(query); };
is_running
bool fabomatic::MockMQTTBroker::is_running {false} private
Definition at line 48 of file MockMQTTBroker.hpp.
{false};
Referenced by isRunning().
mutex
std::mutex fabomatic::MockMQTTBroker::mutex private
Definition at line 34 of file MockMQTTBroker.hpp.
payload
std::string fabomatic::MockMQTTBroker::payload {""} private
Definition at line 36 of file MockMQTTBroker.hpp.
{""};
queries
std::queue<query> fabomatic::MockMQTTBroker::queries {} private
Definition at line 43 of file MockMQTTBroker.hpp.
{};
topic
std::string fabomatic::MockMQTTBroker::topic {""} private
Definition at line 35 of file MockMQTTBroker.hpp.
{""};
The documentation for this class was generated from the following files:
MockMQTTBroker.hpp
MockMQTTBroker.cpp