Fab-O-Matic: fabomatic::SavedConfig Class Reference
fabomatic::SavedConfig Class Reference
Facility to load or save data from Flash.
#include <SavedConfig.hpp>
Public Member Functions
SavedConfig ()=default
Allow compiler-time construction.
auto SaveToEEPROM () const -> bool
Saves the configuration to EEPROM.
auto setMachineID (MachineID id) -> void
Sets the machine ID (converting to string)
auto getMachineID () const -> MachineID
Gets the machine ID (converting from string)
auto toString () const -> const std::string
Returns a json-prettified fragment for logging.
Static Public Member Functions
static auto LoadFromEEPROM () -> std::optional< SavedConfig >
Loads the configuration from EEPROM if available and matching revision number.
static auto DefaultConfig () -> SavedConfig
Returns the default configuration built from conf.hpp and secrets.hpp.
static auto IncrementBootCount () -> size_t
Increments the boot count and saves it to EEPROM.
Public Attributes
uint8_t magic_number {0}
CachedCards cachedRfid
list of cached RFID cards
std::string ssid {""}
WiFi SSID.
std::string password {""}
WiFi password.
std::string mqtt_server {""}
MQTT server.
std::string mqtt_user {""}
MQTT username.
std::string mqtt_password {""}
MQTT password.
std::string mqtt_switch_topic {""}
MQTT topic for mqtt switch (if available)
std::string machine_id {""}
Machine ID connected to the board.
size_t bootCount {0}
number of boot cycles
bool disablePortal {false}
if true, the FORCE_OPEN_PORTAL flag will be ignored
Buffer message_buffer
Static Public Attributes
static constexpr auto MAGIC_NUMBER = 0x51
Private Member Functions
auto toJsonDocument () const -> JsonDocument
Serialize the current configuration into a JsonDocument.
Static Private Member Functions
static auto fromJsonDocument (const std::string &json_text) -> std::optional< SavedConfig >
Deserialize a JsonDocument into a SavedConfig.
Static Private Attributes
static constexpr auto JSON_DOC_SIZE = 4096
static std::string json_buffer
static std::mutex buffer_mutex
Detailed Description
Facility to load or save data from Flash.
Definition at line 20 of file SavedConfig.hpp.
Constructor & Destructor Documentation
SavedConfig()
fabomatic::SavedConfig::SavedConfig () default
Allow compiler-time construction.
Member Function Documentation
DefaultConfig()
auto fabomatic::SavedConfig::DefaultConfig () -> SavedConfig static
Returns the default configuration built from conf.hpp and secrets.hpp.
Definition at line 28 of file SavedConfig.cpp.
  {
    SavedConfig config;
    // Wifi
    config.ssid = secrets::credentials::ssid;
    config.password = secrets::credentials::password;
    // MQTT
    config.mqtt_server = conf::mqtt::mqtt_server;
    config.mqtt_user = secrets::credentials::mqtt_user;
    config.mqtt_password = secrets::credentials::mqtt_password;
    // MQTT Switch
    config.mqtt_switch_topic = conf::mqtt::mqtt_switch_topic;
    // Machine
    config.setMachineID(conf::default_config::machine_id);
    config.magic_number = MAGIC_NUMBER;
    config.disablePortal = false;
    return config;
  }
References disablePortal, fabomatic::conf::default_config::machine_id, magic_number, fabomatic::secrets::credentials::mqtt_password, mqtt_password, fabomatic::conf::mqtt::mqtt_server, mqtt_server, fabomatic::conf::mqtt::mqtt_switch_topic, mqtt_switch_topic, fabomatic::secrets::credentials::mqtt_user, mqtt_user, fabomatic::secrets::credentials::password, password, setMachineID(), fabomatic::secrets::credentials::ssid, and ssid.
Referenced by fabomatic::getConfig(), fabomatic::BoardLogic::reconfigure(), fabomatic::FabBackend::saveBuffer(), fabomatic::AuthProvider::saveCache(), setup(), setUp(), fabomatic::taskFactoryReset(), fabomatic::tests::test_defaults(), fabomatic::tests::test_degraded_use(), fabomatic::tests::test_fabserver_calls(), and fabomatic::tests::test_rfid_cache().
fromJsonDocument()
auto fabomatic::SavedConfig::fromJsonDocument (const std::string & json_text) -> std::optional<SavedConfig> static private
Deserialize a JsonDocument into a SavedConfig.
Parameters
json_text json document as string to be deserialized
Returns
std::nullopt if the document is invalid, or a valid SavedConfig
Definition at line 119 of file SavedConfig.cpp.
  {
    SavedConfig config;
    JsonDocument doc;
    const auto result = deserializeJson(doc, json_text);
    if (result != DeserializationError::Ok)
    {
      ESP_LOGE(TAG, "fromJsonDocument() : deserializeJson failed with code %s", result.c_str());
      return std::nullopt;
    }
    // Now map the JSON to the struct
    config.disablePortal = doc["disablePortal"];
    config.bootCount = doc["bootCount"];
    config.ssid = doc["ssid"].as<std::string>();
    config.password = doc["password"].as<std::string>();
    config.mqtt_server = doc["mqtt_server"].as<std::string>();
    config.mqtt_user = doc["mqtt_user"].as<std::string>();
    config.mqtt_password = doc["mqtt_password"].as<std::string>();
    config.mqtt_switch_topic = doc["mqtt_switch_topic"].as<std::string>();
    config.machine_id = doc["machine_id"].as<std::string>();
    config.magic_number = doc["magic_number"];
    auto idx = 0;
    for (const auto &elem : doc["cached_cards"].as<JsonArray>())
    {
      const auto level = static_cast<FabUser::UserLevel>(elem["level"].as<uint8_t>());
      config.cachedRfid.set_at(idx, elem["uid"], level);
      idx++;
    }
    while (idx < conf::rfid_tags::CACHE_LEN)
    {
      config.cachedRfid.set_at(idx, card::INVALID, FabUser::UserLevel::Unknown);
      idx++;
    }
    if (config.magic_number >= 0x51)
    {
      auto mb = doc["message_buffer"];
      auto loaded = Buffer::fromJsonElement(mb);
      if (loaded)
      {
        config.message_buffer = loaded.value();
      }
    }
    ESP_LOGD(TAG, "fromJsonDocument() : data deserialized successfully");
    return config;
  }
References bootCount, fabomatic::conf::rfid_tags::CACHE_LEN, cachedRfid, disablePortal, fabomatic::Buffer::fromJsonElement(), fabomatic::card::INVALID, machine_id, magic_number, message_buffer, mqtt_password, mqtt_server, mqtt_switch_topic, mqtt_user, password, fabomatic::CachedCards::set_at(), ssid, TAG, and fabomatic::FabUser::Unknown.
getMachineID()
auto fabomatic::SavedConfig::getMachineID () const -> MachineID
Gets the machine ID (converting from string)
Definition at line 23 of file SavedConfig.cpp.
  {
    return MachineID(std::atoi(machine_id.c_str()));
  }
References machine_id.
IncrementBootCount()
auto fabomatic::SavedConfig::IncrementBootCount () -> size_t static
Increments the boot count and saves it to EEPROM.
Definition at line 219 of file SavedConfig.cpp.
  {
    auto config = LoadFromEEPROM().value_or(DefaultConfig());
    config.bootCount++;
    if (!config.SaveToEEPROM())
    {
      ESP_LOGE(TAG, "Failed to save boot count to EEPROM");
    }
    return config.bootCount;
  }
References TAG.
Referenced by setup().
LoadFromEEPROM()
auto fabomatic::SavedConfig::LoadFromEEPROM () -> std::optional<SavedConfig> static
Loads the configuration from EEPROM if available and matching revision number.
Returns
std::nullopt if not valid, SavedConfig otherwise
Definition at line 52 of file SavedConfig.cpp.
  {
    std::lock_guard<std::mutex> lock(SavedConfig::buffer_mutex);
    SavedConfig::json_buffer.resize(JSON_DOC_SIZE);
    std::fill(SavedConfig::json_buffer.begin(), SavedConfig::json_buffer.begin() + SavedConfig::json_buffer.size(), '\0');
    if (!EEPROM.begin(JSON_DOC_SIZE))
    {
      ESP_LOGE(TAG, "SavedConfig::LoadFromEEPROM() : EEPROM.begin failed");
      return std::nullopt;
    }
    for (auto i = 0; i < SavedConfig::json_buffer.size(); i++)
    {
      char c = EEPROM.readChar(i);
      SavedConfig::json_buffer.at(i) = c;
      if (c == '\0')
      {
        break;
      }
    }
    auto reply = fromJsonDocument(SavedConfig::json_buffer);
    if (!reply.has_value())
    {
      ESP_LOGW(TAG, "Failed to load config from EEPROM");
      return std::nullopt;
    }
    if (reply.value().magic_number > MAGIC_NUMBER)
    {
      ESP_LOGW(TAG, "Found different more recent settings version in EEPROM (%d vs. %d), ignoring.", reply.value().magic_number, MAGIC_NUMBER);
      return std::nullopt;
    }
    return reply.value();
  }
References buffer_mutex, json_buffer, and TAG.
Referenced by fabomatic::getConfig(), fabomatic::AuthProvider::loadCache(), fabomatic::BoardLogic::reconfigure(), fabomatic::FabBackend::saveBuffer(), fabomatic::AuthProvider::saveCache(), setup(), setUp(), fabomatic::tests::test_changes(), fabomatic::tests::test_defaults(), fabomatic::tests::test_fabserver_calls(), fabomatic::tests::test_magic_number(), fabomatic::tests::test_messages_buffered(), fabomatic::tests::test_rfid_cache(), and fabomatic::tests::test_start_broker().
SaveToEEPROM()
auto fabomatic::SavedConfig::SaveToEEPROM () const -> bool
Saves the configuration to EEPROM.
Returns
true if successful
Definition at line 172 of file SavedConfig.cpp.
  {
    std::lock_guard<std::mutex> lock(SavedConfig::buffer_mutex);
    json_buffer.resize(JSON_DOC_SIZE);
    std::fill(SavedConfig::json_buffer.begin(), SavedConfig::json_buffer.begin() + SavedConfig::json_buffer.size(), '\0');
    if (!EEPROM.begin(JSON_DOC_SIZE))
    {
      ESP_LOGE(TAG, "SavedConfig::SaveToEEPROM() : EEPROM.begin failed");
      return false;
    }
    const auto &doc = toJsonDocument();
    serializeJson(doc, SavedConfig::json_buffer);
    json_buffer.resize(JSON_DOC_SIZE); // Ensure the buffer is the correct size as serialize may have resized it
    for (auto i = 0; i < JSON_DOC_SIZE; i++)
    {
      const char c = SavedConfig::json_buffer[i];
      EEPROM.writeChar(i, c);
      if (c == '\0')
      {
        break;
      }
    }
    auto result = EEPROM.commit();
    if (result)
    {
      ESP_LOGD(TAG, "EEPROM commit success");
      return result;
    }
    ESP_LOGE(TAG, "EEPROM commit failure");
    return false;
  }
References buffer_mutex, json_buffer, JSON_DOC_SIZE, TAG, and toJsonDocument().
Referenced by fabomatic::AuthProvider::saveCache(), setup(), and fabomatic::tests::test_changes().
setMachineID()
auto fabomatic::SavedConfig::setMachineID (MachineID id) -> void
Sets the machine ID (converting to string)
Definition at line 19 of file SavedConfig.cpp.
  {
    machine_id = std::to_string(id);
  }
Referenced by DefaultConfig().
toJsonDocument()
auto fabomatic::SavedConfig::toJsonDocument () const -> JsonDocument private
Serialize the current configuration into a JsonDocument.
Returns
JsonDocument
Definition at line 88 of file SavedConfig.cpp.
  {
    JsonDocument doc;
    magic_number = MAGIC_NUMBER;
    doc["disablePortal"] = disablePortal;
    doc["bootCount"] = bootCount;
    doc["ssid"] = ssid;
    doc["password"] = password;
    doc["mqtt_server"] = mqtt_server;
    doc["mqtt_user"] = mqtt_user;
    doc["mqtt_password"] = mqtt_password;
    doc["mqtt_switch_topic"] = mqtt_switch_topic;
    doc["machine_id"] = machine_id;
    doc["magic_number"] = magic_number;
    auto json_elem = doc.createNestedArray("cached_cards");
    for (auto idx = 0; idx < cachedRfid.size(); idx++)
    {
      const auto &entry = cachedRfid[idx];
      if (entry.uid != 0) // Skip empty entries
      {
        auto obj = json_elem.createNestedObject();
        obj["uid"] = entry.uid;
        obj["level"] = static_cast<uint8_t>(entry.level);
      }
    }
    message_buffer.toJson(doc, "message_buffer");
    return doc;
  }
References bootCount, cachedRfid, disablePortal, machine_id, MAGIC_NUMBER, magic_number, message_buffer, mqtt_password, mqtt_server, mqtt_switch_topic, mqtt_user, password, fabomatic::CachedCards::size(), ssid, and fabomatic::Buffer::toJson().
Referenced by SaveToEEPROM(), and toString().
toString()
auto fabomatic::SavedConfig::toString () const -> const std::string
Returns a json-prettified fragment for logging.
Definition at line 211 of file SavedConfig.cpp.
  {
    const auto &doc = toJsonDocument();
    std::string result;
    serializeJsonPretty(doc, result);
    return result;
  }
References toJsonDocument().
Member Data Documentation
bootCount
size_t fabomatic::SavedConfig::bootCount {0}
number of boot cycles
Definition at line 69 of file SavedConfig.hpp.
{0};
Referenced by fromJsonDocument(), and toJsonDocument().
buffer_mutex
std::mutex fabomatic::SavedConfig::buffer_mutex static private
Definition at line 26 of file SavedConfig.hpp.
Referenced by LoadFromEEPROM(), and SaveToEEPROM().
cachedRfid
CachedCards fabomatic::SavedConfig::cachedRfid
list of cached RFID cards
Definition at line 44 of file SavedConfig.hpp.
Referenced by fromJsonDocument(), fabomatic::AuthProvider::saveCache(), and toJsonDocument().
disablePortal
bool fabomatic::SavedConfig::disablePortal {false}
if true, the FORCE_OPEN_PORTAL flag will be ignored
Definition at line 72 of file SavedConfig.hpp.
{false};
Referenced by DefaultConfig(), fromJsonDocument(), and toJsonDocument().
json_buffer
std::string fabomatic::SavedConfig::json_buffer static private
Definition at line 25 of file SavedConfig.hpp.
Referenced by LoadFromEEPROM(), and SaveToEEPROM().
JSON_DOC_SIZE
constexpr auto fabomatic::SavedConfig::JSON_DOC_SIZE = 4096 static constexpr private
Definition at line 23 of file SavedConfig.hpp.
Referenced by SaveToEEPROM().
machine_id
std::string fabomatic::SavedConfig::machine_id {""}
Machine ID connected to the board.
This is a string to allow for easier integration with WiFiManager parameter
Definition at line 66 of file SavedConfig.hpp.
{""};
Referenced by fabomatic::FabBackend::configure(), fromJsonDocument(), getMachineID(), fabomatic::tests::test_changes(), and toJsonDocument().
MAGIC_NUMBER
constexpr auto fabomatic::SavedConfig::MAGIC_NUMBER = 0x51 static constexpr
Definition at line 38 of file SavedConfig.hpp.
Referenced by fabomatic::tests::test_changes(), fabomatic::tests::test_defaults(), fabomatic::tests::test_magic_number(), and toJsonDocument().
magic_number
uint8_t fabomatic::SavedConfig::magic_number {0} mutable
Definition at line 41 of file SavedConfig.hpp.
{0};
Referenced by DefaultConfig(), fromJsonDocument(), and toJsonDocument().
message_buffer
Buffer fabomatic::SavedConfig::message_buffer
Definition at line 74 of file SavedConfig.hpp.
Referenced by fabomatic::FabBackend::configure(), fromJsonDocument(), and toJsonDocument().
mqtt_password
std::string fabomatic::SavedConfig::mqtt_password {""}
MQTT password.
Definition at line 59 of file SavedConfig.hpp.
{""};
Referenced by fabomatic::FabBackend::configure(), DefaultConfig(), fromJsonDocument(), fabomatic::tests::test_changes(), and toJsonDocument().
mqtt_server
std::string fabomatic::SavedConfig::mqtt_server {""}
MQTT server.
Definition at line 53 of file SavedConfig.hpp.
{""};
Referenced by fabomatic::FabBackend::configure(), DefaultConfig(), fromJsonDocument(), fabomatic::tests::test_changes(), and toJsonDocument().
mqtt_switch_topic
std::string fabomatic::SavedConfig::mqtt_switch_topic {""}
MQTT topic for mqtt switch (if available)
Definition at line 62 of file SavedConfig.hpp.
{""};
Referenced by DefaultConfig(), fromJsonDocument(), fabomatic::tests::test_changes(), and toJsonDocument().
mqtt_user
std::string fabomatic::SavedConfig::mqtt_user {""}
MQTT username.
Definition at line 56 of file SavedConfig.hpp.
{""};
Referenced by fabomatic::FabBackend::configure(), DefaultConfig(), fromJsonDocument(), fabomatic::tests::test_changes(), and toJsonDocument().
password
std::string fabomatic::SavedConfig::password {""}
WiFi password.
Definition at line 50 of file SavedConfig.hpp.
{""};
Referenced by fabomatic::FabBackend::configure(), DefaultConfig(), fromJsonDocument(), fabomatic::tests::test_changes(), and toJsonDocument().
ssid
std::string fabomatic::SavedConfig::ssid {""}
WiFi SSID.
Definition at line 47 of file SavedConfig.hpp.
{""};
Referenced by fabomatic::FabBackend::configure(), DefaultConfig(), fromJsonDocument(), fabomatic::tests::test_changes(), and toJsonDocument().
The documentation for this class was generated from the following files:
SavedConfig.hpp
SavedConfig.cpp