Fab-O-Matic: fabomatic::BoardLogic Class Reference
fabomatic::BoardLogic Class Reference
Main class implementing the state changes.
#include <BoardLogic.hpp>
Public Types
enum class Status : uint8_t {
Clear , MachineFree , LoggedIn , LoginDenied ,
Busy , LoggedOut , Connecting , Connected ,
AlreadyInUse , MachineInUse , Offline , NotAllowed ,
Verifying , MaintenanceNeeded , MaintenanceQuery , MaintenanceDone ,
Error , ErrorHardware , PortalFailed , PortalSuccess ,
PortalStarting , Booting , ShuttingDown , OTAStarting ,
FactoryDefaults , OTAError
}
Main states of the board.
Public Member Functions
BoardLogic ()=default
auto refreshFromServer () -> void
connects and polls the server for up-to-date machine information
auto onNewCard (card::uid_t uid) -> void
Called when a RFID tag has been detected.
auto logout () -> void
Removes the current machine user and changes the status to LoggedOut.
auto changeStatus (Status newStatus) -> void
Sets the board in the state given.
auto updateLCD () const -> void
Updates the LCD screen as per the current status.
auto beepOk () const -> void
auto beepFail () const -> void
auto blinkLed (uint8_t r=0, uint8_t g=0, uint8_t b=0) -> void
Blinks the LED.
auto checkRfid () -> void
Checks if a new card is present.
auto checkPowerOff () -> void
Checks if the machine must be powered off.
auto setAutologoffDelay (std::chrono::seconds delay) -> void
Sets the autologoff delay.
auto setWhitelist (WhiteList whitelist) -> void
auto setRebootRequest (bool request) -> void
auto initBoard () -> bool
Initializes LCD and RFID classes.
auto configure (BaseRFIDWrapper &rfid, LCDWrapper &lcd) -> bool
Configures the board with the given references.
auto reconfigure () -> bool
Configures the board with the given references.
auto saveRfidCache () -> bool
auto getStatus () const -> Status
Gets the current board status.
auto getRebootRequest () const -> bool
auto getServer () -> FabBackend &
auto getMachineForTesting () -> Machine &
returns a modificable machine for testing only
auto getBuzzerForTesting () -> Buzzer *
returns a modificable machine for testing only
auto getMachine () const -> const Machine &
Gets the current machine.
auto authorize (const card::uid_t uid) -> bool
Checks if the card UID is valid, and tries to check the user in to the machine.
auto getHostname () const -> const std::string
BoardLogic & operator= (const BoardLogic &board)=delete
BoardLogic (const BoardLogic &)=delete
BoardLogic (BoardLogic &&)=default
BoardLogic & operator= (BoardLogic &&)=default
Private Member Functions
BaseRFIDWrapper & getRfid () const
LCDWrapper & getLcd () const
auto longTap (const card::uid_t card, const std::string &short_prompt) const -> bool
Asks the user to keep the RFID tag on the reader as confirmation.
Private Attributes
Status status {Status::Clear}
Led led
FabBackend server
std::optional< std::reference_wrapper< BaseRFIDWrapper > > rfid {std::nullopt}
std::optional< std::reference_wrapper< LCDWrapper > > lcd {std::nullopt}
bool ready_for_a_new_card {true}
bool led_status {false}
Machine machine
AuthProvider auth {secrets::cards::whitelist}
bool rebootRequest {false}
Buzzer buzzer
Detailed Description
Main class implementing the state changes.
Definition at line 19 of file BoardLogic.hpp.
Member Enumeration Documentation
Status
enum class fabomatic::BoardLogic::Status : uint8_t strong
Main states of the board.
Enumerator
Clear
MachineFree
LoggedIn
LoginDenied
Busy
LoggedOut
Connecting
Connected
AlreadyInUse
MachineInUse
Offline
NotAllowed
Verifying
MaintenanceNeeded
MaintenanceQuery
MaintenanceDone
Error
ErrorHardware
PortalFailed
PortalSuccess
PortalStarting
Booting
ShuttingDown
OTAStarting
FactoryDefaults
OTAError
Definition at line 23 of file BoardLogic.hpp.
    {
      Clear,
      MachineFree,
      LoggedIn,
      LoginDenied,
      Busy,
      LoggedOut,
      Connecting,
      Connected,
      AlreadyInUse,
      MachineInUse,
      Offline,
      NotAllowed,
      Verifying,
      MaintenanceNeeded,
      MaintenanceQuery,
      MaintenanceDone,
      Error,
      ErrorHardware,
      PortalFailed,
      PortalSuccess,
      PortalStarting,
      Booting,
      ShuttingDown,
      OTAStarting,
      FactoryDefaults,
      OTAError,
    };
Constructor & Destructor Documentation
BoardLogic() [1/3]
fabomatic::BoardLogic::BoardLogic () default
BoardLogic() [2/3]
fabomatic::BoardLogic::BoardLogic (const BoardLogic &) delete
BoardLogic() [3/3]
fabomatic::BoardLogic::BoardLogic (BoardLogic &&) default
Member Function Documentation
authorize()
bool fabomatic::BoardLogic::authorize (const card::uid_t uid) -> bool
Checks if the card UID is valid, and tries to check the user in to the machine.
Parameters
uid card uid
Returns
true if the user is now logged on to the machine
Definition at line 163 of file BoardLogic.cpp.
  {
    changeStatus(Status::Verifying);
    FabUser user;
    user.authenticated = false;
    user.holder_name = "?";
    user.card_uid = uid;
    user.user_level = FabUser::UserLevel::Unknown;
    const auto response = auth.tryLogin(uid, server);
    if (!response.has_value() || response.value().user_level == FabUser::UserLevel::Unknown)
    {
      ESP_LOGI(TAG, "Failed login for %s", card::uid_str(uid).c_str());
      changeStatus(Status::LoginDenied);
      beepFail();
      return false;
    }
    user = response.value();
    if (!machine.isAllowed())
    {
      ESP_LOGI(TAG, "Login refused due to machine not allowed");
      changeStatus(Status::NotAllowed);
      beepFail();
      return false;
    }
    if (machine.isMaintenanceNeeded())
    {
      if (conf::machine::MAINTENANCE_BLOCK &&
          user.user_level < FabUser::UserLevel::FabStaff)
      {
        changeStatus(Status::MaintenanceNeeded);
        beepFail();
        Tasks::delay(conf::lcd::SHORT_MESSAGE_DELAY);
        return false;
      }
      if (user.user_level >= FabUser::UserLevel::FabStaff)
      {
        beepOk();
        changeStatus(Status::MaintenanceQuery);
        if (longTap(user.card_uid, strings::S_LONGTAP_PROMPT))
        {
          const auto maint_resp = server.registerMaintenance(user.card_uid);
          if (!maint_resp->request_ok)
          {
            beepFail();
            changeStatus(Status::Error);
            Tasks::delay(conf::lcd::SHORT_MESSAGE_DELAY);
            // Allow bypass for admins
            if (user.user_level == FabUser::UserLevel::FabAdmin)
            {
              machine.setMaintenanceNeeded(false);
            }
          }
          else
          {
            changeStatus(Status::MaintenanceDone);
            machine.setMaintenanceNeeded(false);
            beepOk();
            Tasks::delay(conf::lcd::SHORT_MESSAGE_DELAY * 2);
          }
          // Proceed to log-on the staff member to the machine in all cases
        }
      }
    }
    if (machine.login(user))
    {
      const auto result = server.startUse(machine.getActiveUser().card_uid);
      ESP_LOGI(TAG, "Login, result startUse: %d", result->request_ok);
      changeStatus(Status::LoggedIn);
      beepOk();
    }
    else
    {
      changeStatus(Status::NotAllowed);
      beepFail();
      Tasks::delay(conf::lcd::SHORT_MESSAGE_DELAY);
    }
    return true;
  }
References auth, fabomatic::FabUser::authenticated, beepFail(), beepOk(), fabomatic::FabUser::card_uid, changeStatus(), fabomatic::Tasks::delay(), fabomatic::FabUser::FabAdmin, fabomatic::FabUser::FabStaff, fabomatic::Machine::getActiveUser(), fabomatic::FabUser::holder_name, fabomatic::Machine::isAllowed(), fabomatic::Machine::isMaintenanceNeeded(), fabomatic::Machine::login(), longTap(), machine, fabomatic::conf::machine::MAINTENANCE_BLOCK, fabomatic::FabBackend::registerMaintenance(), server, fabomatic::Machine::setMaintenanceNeeded(), fabomatic::conf::lcd::SHORT_MESSAGE_DELAY, fabomatic::FabBackend::startUse(), TAG, fabomatic::AuthProvider::tryLogin(), fabomatic::card::uid_str(), fabomatic::FabUser::Unknown, and fabomatic::FabUser::user_level.
Referenced by onNewCard(), and fabomatic::tests::test_whitelist_no_network().
beepFail()
void fabomatic::BoardLogic::beepFail () const -> void
Definition at line 449 of file BoardLogic.cpp.
  {
    buzzer.beepFail();
  }
References fabomatic::Buzzer::beepFail(), and buzzer.
Referenced by authorize(), setup(), fabomatic::taskLogoffCheck(), fabomatic::taskPoweroffWarning(), fabomatic::tests::test_simple_methods(), and fabomatic::tests::test_taskVarious().
beepOk()
void fabomatic::BoardLogic::beepOk () const -> void
Definition at line 444 of file BoardLogic.cpp.
  {
    buzzer.beepOk();
  }
References fabomatic::Buzzer::beepOk(), and buzzer.
Referenced by authorize(), logout(), setup(), and fabomatic::tests::test_simple_methods().
blinkLed()
void fabomatic::BoardLogic::blinkLed (uint8_t r = 0, uint8_t g = 0, uint8_t b = 0) -> void
Blinks the LED.
Definition at line 498 of file BoardLogic.cpp.
  {
    led.set(Led::Status::Blinking);
    if (server.isOnline())
    {
      if (!machine.isAllowed() || machine.isMaintenanceNeeded())
      {
        led.setColor(64, 0, 0); // Red
      }
      else
      {
        if (machine.isFree())
        {
          if (machine.isShutdownImminent())
          {
            led.setColor(64, 0, 64); // Purple
          }
          else
          {
            led.setColor(0, 64, 0); // Green
          }
        }
        else
        {
          led.setColor(0, 0, 64); // Blue
        }
      }
    }
    else
    {
      led.setColor(128, 255, 0); // Orange
    }
    // User override
    if (r != 0 || g != 0 || b != 0)
    {
      led.setColor(r, g, b);
    }
    // Color override
    if (status == Status::ErrorHardware || status == Status::Error)
    {
      led.setColor(255, 0, 0); // Red
    }
    led.update();
  }
References fabomatic::Machine::isAllowed(), fabomatic::Machine::isFree(), fabomatic::Machine::isMaintenanceNeeded(), fabomatic::FabBackend::isOnline(), fabomatic::Machine::isShutdownImminent(), led, machine, server, fabomatic::Led::set(), fabomatic::Led::setColor(), status, and fabomatic::Led::update().
Referenced by setup(), fabomatic::taskBlink(), fabomatic::taskFactoryReset(), fabomatic::tests::test_simple_methods(), and fabomatic::tests::test_taskVarious().
changeStatus()
void fabomatic::BoardLogic::changeStatus (Status new_state) -> void
Sets the board in the state given.
Parameters
new_state new state
Definition at line 272 of file BoardLogic.cpp.
  {
    if (status != new_state)
    {
      ESP_LOGI(TAG, "** Changing board state to %d", static_cast<int>(new_state));
    }
    status = new_state;
    updateLCD();
  }
References status, TAG, and updateLCD().
Referenced by authorize(), checkRfid(), fabomatic::configModeCallback(), logout(), onNewCard(), fabomatic::openConfigPortal(), setup(), fabomatic::setupOTA(), fabomatic::taskConnect(), fabomatic::taskPoweroffWarning(), fabomatic::taskRfidWatchdog(), fabomatic::tests::test_simple_methods(), and fabomatic::tests::test_taskConnect().
checkPowerOff()
void fabomatic::BoardLogic::checkPowerOff () -> void
Checks if the machine must be powered off.
Definition at line 576 of file BoardLogic.cpp.
  {
    if (machine.canPowerOff())
    {
      machine.power(false);
    }
  }
References fabomatic::Machine::canPowerOff(), machine, and fabomatic::Machine::power().
Referenced by fabomatic::taskPoweroffCheck(), fabomatic::tests::test_simple_methods(), and fabomatic::tests::test_taskVarious().
checkRfid()
void fabomatic::BoardLogic::checkRfid () -> void
Checks if a new card is present.
Definition at line 548 of file BoardLogic.cpp.
  {
    auto &rfid = getRfid();
    // check if there is a card
    if (rfid.isNewCardPresent())
    {
      const auto &result = rfid.readCardSerial();
      if (result)
      {
        onNewCard(result.value());
      }
      return;
    }
    // No new card present
    ready_for_a_new_card = true;
    if (machine.isFree())
    {
      changeStatus(Status::MachineFree);
    }
    else
    {
      changeStatus(Status::MachineInUse);
    }
  }
References changeStatus(), getRfid(), fabomatic::Machine::isFree(), machine, onNewCard(), ready_for_a_new_card, and rfid.
Referenced by fabomatic::tests::simulate_rfid_card(), fabomatic::taskCheckRfid(), fabomatic::tests::test_taskCheckRfid(), and fabomatic::tests::test_whitelist_no_network().
configure()
bool fabomatic::BoardLogic::configure (BaseRFIDWrapper & rfid, LCDWrapper & lcd) -> bool
Configures the board with the given references.
Definition at line 455 of file BoardLogic.cpp.
  {
    this->rfid = rfid;
    this->lcd = lcd;
    return reconfigure();
  }
References lcd, reconfigure(), and rfid.
Referenced by setup(), and setUp().
getBuzzerForTesting()
auto fabomatic::BoardLogic::getBuzzerForTesting () -> Buzzer *
returns a modificable machine for testing only
Returns
a non-null Buzzer*
Definition at line 593 of file BoardLogic.cpp.
  {
    return &buzzer;
  }
Referenced by fabomatic::tests::test_simple_methods().
getHostname()
auto fabomatic::BoardLogic::getHostname () const -> const std::string
Definition at line 653 of file BoardLogic.cpp.
  {
    // Hostname is BOARD + machine_id (which shall be unique) e.g. BOARD1
    return conf::default_config::hostname.data() +
           std::to_string(conf::default_config::machine_id.id);
  }
References fabomatic::conf::default_config::hostname, and fabomatic::conf::default_config::machine_id.
getLcd()
auto fabomatic::BoardLogic::getLcd () const private
Definition at line 605 of file BoardLogic.cpp.
  {
    if (lcd.has_value())
    {
      return lcd.value().get();
    }
    else
    {
      ESP_LOGE(TAG, "LCD not initialized");
      while (true)
      {
        Tasks::delay(1s);
      };
    }
  }
References fabomatic::Tasks::delay(), lcd, and TAG.
Referenced by initBoard(), longTap(), and updateLCD().
getMachine()
auto fabomatic::BoardLogic::getMachine () const -> const Machine &
Gets the current machine.
Returns
a machine object
Definition at line 600 of file BoardLogic.cpp.
  {
    return machine;
  }
References machine.
Referenced by fabomatic::tests::machine_init(), fabomatic::taskLogoffCheck(), fabomatic::tests::test_machine_defaults(), fabomatic::tests::test_machine_maintenance(), fabomatic::tests::test_one_user_at_a_time(), fabomatic::tests::test_taskVarious(), fabomatic::tests::test_user_autologoff(), fabomatic::tests::test_whitelist_no_network(), and updateLCD().
getMachineForTesting()
auto fabomatic::BoardLogic::getMachineForTesting () -> Machine &
returns a modificable machine for testing only
Returns
machine
Definition at line 586 of file BoardLogic.cpp.
  {
    return machine;
  }
Referenced by fabomatic::tests::machine_init(), fabomatic::tests::test_machine_allowed(), fabomatic::tests::test_machine_maintenance(), and fabomatic::tests::test_user_autologoff().
getRebootRequest()
auto fabomatic::BoardLogic::getRebootRequest () const -> bool
Definition at line 643 of file BoardLogic.cpp.
  {
    return rebootRequest;
  }
References rebootRequest.
getRfid()
BaseRFIDWrapper & fabomatic::BoardLogic::getRfid () const private
Definition at line 28 of file BoardLogic.cpp.
  {
    if (rfid.has_value())
      return rfid.value().get();
    ESP_LOGE(TAG, "RFID not initialized");
    while (true)
    {
      Tasks::delay(1s);
    };
  }
References fabomatic::Tasks::delay(), rfid, and TAG.
Referenced by checkRfid(), initBoard(), and longTap().
getServer()
auto fabomatic::BoardLogic::getServer () -> FabBackend &
Definition at line 633 of file BoardLogic.cpp.
  {
    return server;
  }
Referenced by setUp(), fabomatic::taskConnect(), fabomatic::taskIsAlive(), fabomatic::taskMQTTClientLoop(), fabomatic::tests::test_check_transmission(), fabomatic::tests::test_create_buffered_messages(), fabomatic::tests::test_fabserver_calls(), fabomatic::tests::test_messages_buffered(), fabomatic::tests::test_one_user_at_a_time(), fabomatic::tests::test_start_broker(), fabomatic::tests::test_taskConnect(), fabomatic::tests::test_taskMQTTAlive(), fabomatic::tests::test_user_autologoff(), and fabomatic::tests::test_whitelist_no_network().
getStatus()
auto fabomatic::BoardLogic::getStatus () const -> Status
Gets the current board status.
Returns
board status
Definition at line 439 of file BoardLogic.cpp.
  {
    return status;
  }
References status.
Referenced by fabomatic::tests::machine_init(), fabomatic::tests::simulate_rfid_card(), fabomatic::tests::test_machine_allowed(), fabomatic::tests::test_machine_maintenance(), fabomatic::tests::test_one_user_at_a_time(), fabomatic::tests::test_simple_methods(), fabomatic::tests::test_user_autologoff(), and fabomatic::tests::test_whitelist_no_network().
initBoard()
bool fabomatic::BoardLogic::initBoard () -> bool
Initializes LCD and RFID classes.
Definition at line 251 of file BoardLogic.cpp.
  {
    ESP_LOGD(TAG, "Board initialization...");
    auto success = getLcd().begin();
    success &= getRfid().rfidInit();
    // Setup buzzer pin for ESP32
    if constexpr (pins.buzzer.pin != NO_PIN)
    {
      pinMode(pins.buzzer.pin, OUTPUT);
      gpio_set_drive_capability(static_cast<gpio_num_t>(pins.buzzer.pin), GPIO_DRIVE_CAP_2);
    }
    ESP_LOGI(TAG, "Board initialization complete, success = %d", success);
    return success;
  }
References fabomatic::LCDWrapper::begin(), fabomatic::pins_config::buzzer, getLcd(), getRfid(), fabomatic::NO_PIN, fabomatic::pins_config::buzzer_config::pin, fabomatic::pins, fabomatic::BaseRFIDWrapper::rfidInit(), and TAG.
Referenced by setup(), and setUp().
logout()
void fabomatic::BoardLogic::logout () -> void
Removes the current machine user and changes the status to LoggedOut.
Definition at line 111 of file BoardLogic.cpp.
  {
    const auto result = server.finishUse(machine.getActiveUser().card_uid,
                                         machine.getUsageDuration());
    ESP_LOGI(TAG, "Logout, result finishUse: %d", result->request_ok);
    machine.logout();
    changeStatus(Status::LoggedOut);
    beepOk();
    Tasks::delay(conf::lcd::SHORT_MESSAGE_DELAY);
  }
References beepOk(), changeStatus(), fabomatic::Tasks::delay(), fabomatic::FabBackend::finishUse(), fabomatic::Machine::getActiveUser(), fabomatic::Machine::getUsageDuration(), fabomatic::Machine::logout(), machine, server, fabomatic::conf::lcd::SHORT_MESSAGE_DELAY, and TAG.
Referenced by fabomatic::tests::machine_init(), onNewCard(), fabomatic::taskLogoffCheck(), fabomatic::tests::test_taskVarious(), fabomatic::tests::test_user_autologoff(), and fabomatic::tests::test_whitelist_no_network().
longTap()
bool fabomatic::BoardLogic::longTap (const card::uid_t card, const std::string & short_prompt) const -> bool private
Asks the user to keep the RFID tag on the reader as confirmation.
Returns
True if the user accepted, False if user bailed out
Definition at line 126 of file BoardLogic.cpp.
  {
    constexpr auto STEPS_COUNT = 6;
    constexpr milliseconds delay_per_step = std::chrono::duration_cast<std::chrono::milliseconds>(conf::machine::LONG_TAP_DURATION) / STEPS_COUNT;
    const BoardInfo bi = {server.isOnline(), machine.getPowerState(), machine.isShutdownImminent()};
    for (auto step = 0; step < STEPS_COUNT; step++)
    {
      std::stringstream ss;
      ss << short_prompt << " " << step << "/" << STEPS_COUNT;
      getLcd().setRow(1, ss.str());
      getLcd().update(bi);
      const auto start = std::chrono::system_clock::now();
      if (!getRfid().cardStillThere(card, delay_per_step))
      {
        getLcd().setRow(1, strings::S_CANCELLED);
        getLcd().update(bi);
        return false;
      }
      // cardStillThere may have returned immediately, so we need to wait a bit
      const auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now() - start);
      if (delay_per_step - elapsed > 10ms)
      {
        Tasks::delay(delay_per_step - elapsed);
      }
    }
    getLcd().setRow(1, strings::S_CONFIRMED);
    getLcd().update(bi);
    return true;
  }
References fabomatic::Tasks::delay(), getLcd(), fabomatic::Machine::getPowerState(), getRfid(), fabomatic::FabBackend::isOnline(), fabomatic::Machine::isShutdownImminent(), fabomatic::conf::machine::LONG_TAP_DURATION, machine, server, fabomatic::LCDWrapper::setRow(), and fabomatic::LCDWrapper::update().
Referenced by authorize().
onNewCard()
void fabomatic::BoardLogic::onNewCard (card::uid_t uid) -> void
Called when a RFID tag has been detected.
Definition at line 73 of file BoardLogic.cpp.
  {
    ESP_LOGD(TAG, "New card present");
    if (!ready_for_a_new_card)
    {
      return;
    }
    ready_for_a_new_card = false;
    if (machine.isFree())
    {
      // machine is free
      if (!authorize(uid))
      {
        ESP_LOGI(TAG, "Login failed for %s", card::uid_str(uid).c_str());
      }
      Tasks::delay(conf::lcd::SHORT_MESSAGE_DELAY);
      refreshFromServer();
      return;
    }
    // machine is busy
    if (machine.getActiveUser().card_uid == uid)
    {
      // we can logout. we should require that the card stays in the field for some seconds, to prevent accidental logout. maybe sound a buzzer?
      logout();
    }
    else
    {
      // user is not the same, display who is using it
      changeStatus(Status::AlreadyInUse);
    }
    Tasks::delay(conf::lcd::SHORT_MESSAGE_DELAY);
    return;
  }
References authorize(), changeStatus(), fabomatic::Tasks::delay(), fabomatic::Machine::getActiveUser(), fabomatic::Machine::isFree(), logout(), machine, ready_for_a_new_card, refreshFromServer(), fabomatic::conf::lcd::SHORT_MESSAGE_DELAY, TAG, and fabomatic::card::uid_str().
Referenced by checkRfid().
operator=() [1/2]
BoardLogic & fabomatic::BoardLogic::operator= (BoardLogic &&) default
operator=() [2/2]
BoardLogic & fabomatic::BoardLogic::operator= (const BoardLogic & board) delete
reconfigure()
bool fabomatic::BoardLogic::reconfigure () -> bool
Configures the board with the given references.
Definition at line 463 of file BoardLogic.cpp.
  {
    auto success = true;
    // Load configuration
    auto config = SavedConfig::LoadFromEEPROM();
    if (!config)
    {
      ESP_LOGW(TAG, "No configuration found in EEPROM, using defaults.");
      auto new_config = SavedConfig::DefaultConfig();
      success &= new_config.SaveToEEPROM();
      config = new_config;
    }
    ESP_LOGD(TAG, "Configuration found in EEPROM: %s", config->toString().c_str());
    server.configure(config.value());
    MachineID mid = config.value().getMachineID();
    MachineConfig machine_conf(mid,
                               conf::default_config::machine_type,
                               std::string{conf::default_config::machine_name},
                               pins.relay,
                               std::string{config.value().mqtt_switch_topic},
                               conf::machine::DEFAULT_AUTO_LOGOFF_DELAY,
                               conf::machine::DEFAULT_GRACE_PERIOD);
    machine.configure(machine_conf, server);
    buzzer.configure();
    auth.loadCache();
    return success;
  }
References auth, buzzer, fabomatic::Buzzer::configure(), fabomatic::Machine::configure(), fabomatic::FabBackend::configure(), fabomatic::conf::machine::DEFAULT_AUTO_LOGOFF_DELAY, fabomatic::conf::machine::DEFAULT_GRACE_PERIOD, fabomatic::SavedConfig::DefaultConfig(), fabomatic::AuthProvider::loadCache(), fabomatic::SavedConfig::LoadFromEEPROM(), machine, fabomatic::conf::default_config::machine_name, fabomatic::conf::default_config::machine_type, fabomatic::pins, fabomatic::pins_config::relay, server, and TAG.
Referenced by configure(), and fabomatic::tests::test_simple_methods().
refreshFromServer()
void fabomatic::BoardLogic::refreshFromServer () -> void
connects and polls the server for up-to-date machine information
Definition at line 41 of file BoardLogic.cpp.
  {
    ESP_LOGD(TAG, "BoardLogic::refreshFromServer() called");
    if (server.connect())
    {
      // Check the configured machine data from the server
      const auto result = server.checkMachine();
      if (result->request_ok)
      {
        if (result->is_valid)
        {
          machine.setMaintenanceNeeded(result->maintenance);
          machine.setAllowed(result->allowed);
          machine.setAutologoffDelay(std::chrono::minutes(result->logoff));
          machine.setGracePeriod(std::chrono::minutes(result->grace));
          machine.setMachineName(result->name);
          machine.setMaintenanceInfo(result->description);
          MachineType mt = static_cast<MachineType>(result->type);
          machine.setMachineType(mt);
          ESP_LOGD(TAG, "Machine data updated:%s", machine.toString().c_str());
        }
        else
        {
          ESP_LOGW(TAG, "The configured machine ID %u is unknown to the server\r\n", machine.getMachineId().id);
        }
      }
    }
  }
References fabomatic::FabBackend::checkMachine(), fabomatic::FabBackend::connect(), fabomatic::Machine::getMachineId(), machine, server, fabomatic::Machine::setAllowed(), fabomatic::Machine::setAutologoffDelay(), fabomatic::Machine::setGracePeriod(), fabomatic::Machine::setMachineName(), fabomatic::Machine::setMachineType(), fabomatic::Machine::setMaintenanceInfo(), fabomatic::Machine::setMaintenanceNeeded(), TAG, and fabomatic::Machine::toString().
Referenced by onNewCard(), fabomatic::taskConnect(), and fabomatic::tests::test_taskConnect().
saveRfidCache()
auto fabomatic::BoardLogic::saveRfidCache () -> bool
Definition at line 648 of file BoardLogic.cpp.
  {
    return this->auth.saveCache();
  }
setAutologoffDelay()
auto fabomatic::BoardLogic::setAutologoffDelay (std::chrono::seconds delay) -> void
Sets the autologoff delay.
Parameters
delay new delay
Definition at line 623 of file BoardLogic.cpp.
  {
    machine.setAutologoffDelay(delay);
  }
Referenced by fabomatic::tests::test_user_autologoff().
setRebootRequest()
auto fabomatic::BoardLogic::setRebootRequest (bool request) -> void
Definition at line 638 of file BoardLogic.cpp.
  {
    rebootRequest = request;
  }
Referenced by fabomatic::openConfigPortal(), and fabomatic::OTAComplete().
setWhitelist()
auto fabomatic::BoardLogic::setWhitelist (WhiteList whitelist) -> void
Definition at line 628 of file BoardLogic.cpp.
  {
    auth.setWhitelist(whitelist);
  }
Referenced by setUp().
updateLCD()
void fabomatic::BoardLogic::updateLCD () const -> void
Updates the LCD screen as per the current status.
Definition at line 284 of file BoardLogic.cpp.
  {
    std::stringstream buffer; // Null terminated strings
    std::string user_name, machine_name, uid_str;
    auto &lcd = getLcd();
    lcd.showConnection(true);
    lcd.showPower(true);
    user_name = machine.getActiveUser().holder_name;
    machine_name = machine.isConfigured() ? machine.getMachineName() : "-";
    if (rfid.has_value())
    {
      auto uid = rfid.value().get().getUid();
      uid_str = card::uid_str(uid);
    }
    else
    {
      uid_str = "????????";
    }
    std::stringstream idv;
    idv << "ID:" << this->getMachine().getMachineId()
        << " V" << GIT_VERSION;
    switch (status)
    {
    case Status::Clear:
      lcd.clear();
      break;
    case Status::MachineFree:
      lcd.setRow(0, machine_name);
      if (!machine.isAllowed())
      {
        lcd.setRow(1, strings::S_MACHINE_BLOCKED);
      }
      else if (machine.isMaintenanceNeeded())
      {
        lcd.setRow(0, strings::S_MACHINE_MAINTENANCE);
        lcd.setRow(1, machine.getMaintenanceInfo());
      }
      else
      {
        lcd.setRow(1, strings::S_CARD_PROMPT);
      }
      break;
    case Status::AlreadyInUse:
      lcd.setRow(0, strings::S_USED_BY);
      lcd.setRow(1, user_name);
      break;
    case Status::LoggedIn:
      lcd.setRow(0, strings::S_START_USE);
      lcd.setRow(1, user_name);
      break;
    case Status::LoginDenied:
      lcd.setRow(0, strings::S_LOGIN_DENIED);
      lcd.setRow(1, uid_str);
      break;
    case Status::LoggedOut:
      lcd.setRow(0, strings::S_GOODBYE);
      lcd.setRow(1, user_name);
      break;
    case Status::Connecting:
      lcd.setRow(0, strings::S_CONNECTING_MQTT_1);
      lcd.setRow(1, strings::S_CONNECTING_MQTT_2);
      break;
    case Status::Connected:
      lcd.setRow(0, strings::S_CONNECTED);
      lcd.setRow(1, "");
      break;
    case Status::MachineInUse:
      buffer << strings::S_HELLO << " " << user_name;
      lcd.setRow(0, buffer.str());
      lcd.setRow(1, lcd.convertSecondsToHHMMSS(machine.getUsageDuration()));
      break;
    case Status::Busy:
      lcd.setRow(0, strings::S_WORKING);
      lcd.setRow(1, "");
      break;
    case Status::Offline:
      lcd.setRow(0, strings::S_OFFLINE_MODE);
      lcd.setRow(1, "");
      break;
    case Status::NotAllowed:
      lcd.setRow(0, strings::S_BLOCKED_ADMIN_1);
      lcd.setRow(1, strings::S_BLOCKED_ADMIN_2);
      break;
    case Status::Verifying:
      lcd.setRow(0, strings::S_VERIFYING_1);
      lcd.setRow(1, strings::S_VERIFYING_2);
      break;
    case Status::MaintenanceNeeded:
      lcd.setRow(0, strings::S_BLOCKED_MAINTENANCE_1);
      lcd.setRow(1, strings::S_BLOCKED_MAINTENANCE_2);
      break;
    case Status::MaintenanceQuery:
      lcd.setRow(0, strings::S_PROMPT_MAINTENANCE_1);
      lcd.setRow(1, strings::S_PROMPT_MAINTENANCE_2);
      break;
    case Status::MaintenanceDone:
      lcd.setRow(0, strings::S_MAINTENANCE_REGISTERED_1);
      lcd.setRow(1, strings::S_MAINTENANCE_REGISTERED_2);
      break;
    case Status::Error:
      lcd.setRow(0, strings::S_GENERIC_ERROR);
      lcd.setRow(1, idv.str());
      break;
    case Status::ErrorHardware:
      lcd.setRow(0, strings::S_HW_ERROR);
      lcd.setRow(1, idv.str());
      break;
    case Status::PortalFailed:
      lcd.setRow(0, strings::S_PORTAL_ERROR);
      lcd.setRow(1, WiFi.softAPIP().toString().c_str());
      break;
    case Status::PortalSuccess:
      lcd.setRow(0, strings::S_PORTAL_SUCCESS);
      lcd.setRow(1, idv.str());
      break;
    case Status::PortalStarting:
      lcd.setRow(0, strings::S_OPEN_PORTAL);
      lcd.setRow(1, WiFi.softAPIP().toString().c_str());
      break;
    case Status::Booting:
      lcd.setRow(0, strings::S_BOOTING);
      lcd.setRow(1, idv.str());
      break;
    case Status::ShuttingDown:
      lcd.setRow(0, machine_name);
      lcd.setRow(1, strings::S_SHUTTING_DOWN);
      break;
    case Status::OTAStarting:
      lcd.setRow(0, strings::UPDATE_OTA_1);
      lcd.setRow(1, strings::UPDATE_OTA_2);
      break;
    case Status::FactoryDefaults:
      lcd.setRow(0, strings::FACTORY_RESET_DONE_1);
      lcd.setRow(1, strings::FACTORY_RESET_DONE_2);
      break;
    case Status::OTAError:
      lcd.setRow(0, strings::S_OTA_ERROR);
      lcd.setRow(1, "");
      break;
    default:
      lcd.setRow(0, strings::S_STATUS_ERROR_1);
      buffer << strings::S_STATUS_ERROR_2 << static_cast<int>(status);
      lcd.setRow(1, buffer.str());
      break;
    }
    BoardInfo bi = {server.isOnline(), machine.getPowerState(), machine.isShutdownImminent()};
    lcd.update(bi, false);
  }
References fabomatic::Machine::getActiveUser(), getLcd(), getMachine(), fabomatic::Machine::getMachineName(), fabomatic::Machine::getMaintenanceInfo(), fabomatic::Machine::getPowerState(), fabomatic::Machine::getUsageDuration(), GIT_VERSION, fabomatic::Machine::isAllowed(), fabomatic::Machine::isConfigured(), fabomatic::Machine::isMaintenanceNeeded(), fabomatic::FabBackend::isOnline(), fabomatic::Machine::isShutdownImminent(), lcd, machine, rfid, server, status, and fabomatic::card::uid_str().
Referenced by changeStatus(), and fabomatic::tests::test_simple_methods().
Member Data Documentation
auth
AuthProvider fabomatic::BoardLogic::auth {secrets::cards::whitelist} private
Definition at line 102 of file BoardLogic.hpp.
{secrets::cards::whitelist};
Referenced by authorize(), and reconfigure().
buzzer
Buzzer fabomatic::BoardLogic::buzzer private
Definition at line 108 of file BoardLogic.hpp.
Referenced by beepFail(), beepOk(), and reconfigure().
lcd
std::optional<std::reference_wrapper<LCDWrapper> > fabomatic::BoardLogic::lcd {std::nullopt} private
Definition at line 97 of file BoardLogic.hpp.
{std::nullopt};       // Configured at runtime
Referenced by configure(), getLcd(), and updateLCD().
led
Led fabomatic::BoardLogic::led private
Definition at line 94 of file BoardLogic.hpp.
Referenced by blinkLed().
led_status
bool fabomatic::BoardLogic::led_status {false} private
Definition at line 99 of file BoardLogic.hpp.
{false};
machine
Machine fabomatic::BoardLogic::machine private
Definition at line 101 of file BoardLogic.hpp.
Referenced by authorize(), blinkLed(), checkPowerOff(), checkRfid(), getMachine(), logout(), longTap(), onNewCard(), reconfigure(), refreshFromServer(), and updateLCD().
ready_for_a_new_card
bool fabomatic::BoardLogic::ready_for_a_new_card {true} private
Definition at line 98 of file BoardLogic.hpp.
{true};
Referenced by checkRfid(), and onNewCard().
rebootRequest
bool fabomatic::BoardLogic::rebootRequest {false} private
Definition at line 107 of file BoardLogic.hpp.
{false};
Referenced by getRebootRequest().
rfid
std::optional<std::reference_wrapper<BaseRFIDWrapper> > fabomatic::BoardLogic::rfid {std::nullopt} private
Definition at line 96 of file BoardLogic.hpp.
{std::nullopt}; // Configured at runtime
Referenced by checkRfid(), configure(), getRfid(), and updateLCD().
server
FabBackend fabomatic::BoardLogic::server private
Definition at line 95 of file BoardLogic.hpp.
Referenced by authorize(), blinkLed(), logout(), longTap(), reconfigure(), refreshFromServer(), and updateLCD().
status
Status fabomatic::BoardLogic::status {Status::Clear} private
Definition at line 93 of file BoardLogic.hpp.
{Status::Clear};
Referenced by blinkLed(), changeStatus(), getStatus(), and updateLCD().
The documentation for this class was generated from the following files:
BoardLogic.hpp
BoardLogic.cpp