Fab-O-Matic: main.cpp File Reference
main.cpp File Reference
#include "pthread.h"
#include <array>
#include <cstdint>
#include <iostream>
#include <string>
#include "BoardLogic.hpp"
#include "Espressif.hpp"
#include "Logging.hpp"
#include "Mrfc522Driver.hpp"
#include "SavedConfig.hpp"
#include "Tasks.hpp"
#include "globals.hpp"
#include "pins.hpp"
#include "language/lang.hpp"
#include "OTA.hpp"
Namespaces
namespace fabomatic
namespace fabomatic::Board
Typedefs
using fabomatic::Scheduler = Tasks::Scheduler
using fabomatic::Task = Tasks::Task
using fabomatic::Status = BoardLogic::Status
Functions
void fabomatic::taskConnect ()
Opens WiFi and server connection and updates board state accordingly.
void fabomatic::taskCheckRfid ()
periodic check for new RFID card
void fabomatic::taskBlink ()
blink led
void fabomatic::taskPoweroffCheck ()
periodic check if the machine must be powered off
void fabomatic::taskPoweroffWarning ()
periodic check if the machine must be powered off
void fabomatic::taskLogoffCheck ()
periodic check if the user shall be logged off
void fabomatic::taskEspWatchdog ()
Keep the ESP32 HW watchdog alive. If code gets stuck this will cause an automatic reset.
void fabomatic::taskRfidWatchdog ()
checks the RFID chip status and re-init it if necessary.
void fabomatic::taskMQTTClientLoop ()
sends the MQTT alive message
void fabomatic::taskIsAlive ()
void fabomatic::taskFactoryReset ()
void fabomatic::printCompileSettings ()
void setup ()
void loop ()
Variables
RFIDWrapper< Mrfc522Driver > fabomatic::Board::rfid {}
Scheduler fabomatic::Board::scheduler
BoardLogic fabomatic::Board::logic
const Task fabomatic::t_rfid ("RFIDChip", conf::tasks::RFID_CHECK_PERIOD, &taskCheckRfid, Board::scheduler, true)
const Task fabomatic::t_network ("Wifi/MQTT", conf::tasks::MQTT_REFRESH_PERIOD, &taskConnect, Board::scheduler, true, conf::tasks::MQTT_REFRESH_PERIOD)
const Task fabomatic::t_powoff ("Poweroff", 1s, &taskPoweroffCheck, Board::scheduler, true)
const Task fabomatic::t_log ("Logoff", 1s, &taskLogoffCheck, Board::scheduler, true)
Task fabomatic::t_wdg ("Watchdog", conf::tasks::WATCHDOG_PERIOD, &taskEspWatchdog, Board::scheduler, false)
const Task fabomatic::t_test ("Selftest", conf::tasks::RFID_SELFTEST_PERIOD, &taskRfidWatchdog, Board::scheduler, true)
const Task fabomatic::t_warn ("PoweroffWarning", conf::machine::DELAY_BETWEEN_BEEPS, &taskPoweroffWarning, Board::scheduler, true)
const Task fabomatic::t_mqtt ("MQTT client loop", 1s, &taskMQTTClientLoop, Board::scheduler, true)
const Task fabomatic::t_led ("LED", 1s, &taskBlink, Board::scheduler, true)
const Task fabomatic::t_rst ("FactoryReset", 500ms, &taskFactoryReset, Board::scheduler, pins.buttons.factory_defaults_pin !=NO_PIN)
const Task fabomatic::t_alive ("IsAlive", conf::tasks::MQTT_ALIVE_PERIOD, &taskIsAlive, Board::scheduler, true, conf::tasks::MQTT_ALIVE_PERIOD)
Function Documentation
loop()
void loop ()
Definition at line 495 of file main.cpp.
{
  fabomatic::Board::scheduler.execute();
  ArduinoOTA.handle();
}
References fabomatic::Tasks::Scheduler::execute(), and fabomatic::Board::scheduler.
setup()
void setup ()
Definition at line 409 of file main.cpp.
{
  using Status = fabomatic::BoardLogic::Status;
  auto &logic = fabomatic::Board::logic;
  auto &scheduler = fabomatic::Board::scheduler;
  auto &rfid = fabomatic::Board::rfid;
  auto &lcd = fabomatic::Board::lcd;
  Serial.begin(fabomatic::conf::debug::SERIAL_SPEED_BDS); // Initialize serial communications with the PC for debugging.
  delay(3000);
  if constexpr (fabomatic::conf::debug::ENABLE_LOGS)
  {
    Serial.setDebugOutput(true);
    ESP_LOGD(TAG, "Starting setup!");
    fabomatic::printCompileSettings();
  }
  if constexpr (fabomatic::conf::debug::LOAD_EEPROM_DEFAULTS)
  {
    const auto &defaults = fabomatic::SavedConfig::DefaultConfig();
    ESP_LOGW(TAG, "Forcing EEPROM defaults : %s", defaults.toString().c_str());
    defaults.SaveToEEPROM();
  }
  logic.blinkLed();
  // Initialize hardware (RFID, LCD)
  auto hw_init = logic.configure(rfid, lcd);
  hw_init &= logic.initBoard();
  const auto count = fabomatic::SavedConfig::IncrementBootCount();
  ESP_LOGI(TAG, "Boot count: %d, reset reason: %d", count, esp_reset_reason());
  logic.changeStatus(Status::Booting);
  if (!hw_init)
  {
    logic.changeStatus(Status::ErrorHardware);
    logic.beepFail();
    logic.blinkLed(64, 0, 0);
    ESP_LOGE(TAG, "Hardware initialization failed");
  }
  else
  {
    logic.beepOk();
    logic.blinkLed(0, 64, 0);
  }
  fabomatic::openConfigPortal(fabomatic::conf::debug::LOAD_EEPROM_DEFAULTS,
                              !fabomatic::conf::debug::FORCE_PORTAL);
#if (MQTT_SIMULATION)
  fabomatic::startMQTTBrocker();
#endif
  fabomatic::setupOTA();
  if (!hw_init)
  {
    // If hardware initialization failed, wait for OTA for 3 minutes
    if (!fabomatic::esp32::setupWatchdog(180s))
    {
      ESP_LOGE(TAG, "Failed to setup watchdog!");
    }
    while (true)
    {
      logic.blinkLed(64, 0, 0);
      logic.changeStatus(fabomatic::BoardLogic::Status::ErrorHardware);
      fabomatic::Tasks::delay(1s);
      ESP_LOGE(TAG, "Hardware failed, waiting for OTA");
    }
  }
  // Let some time for WiFi to settle
  fabomatic::Tasks::delay(2s);
  // Enable the HW watchdog
  fabomatic::t_wdg.enable();
  // Since the WiFiManager may have taken minutes, recompute the tasks schedule
  scheduler.updateSchedules();
  // Try to connect immediately
  fabomatic::taskConnect();
}
References fabomatic::BoardLogic::beepFail(), fabomatic::BoardLogic::beepOk(), fabomatic::BoardLogic::blinkLed(), fabomatic::BoardLogic::changeStatus(), fabomatic::BoardLogic::configure(), fabomatic::SavedConfig::DefaultConfig(), fabomatic::Tasks::delay(), fabomatic::Tasks::Task::enable(), fabomatic::conf::debug::ENABLE_LOGS, fabomatic::BoardLogic::ErrorHardware, fabomatic::conf::debug::FORCE_PORTAL, fabomatic::SavedConfig::IncrementBootCount(), fabomatic::BoardLogic::initBoard(), fabomatic::Board::lcd, lcd, fabomatic::conf::debug::LOAD_EEPROM_DEFAULTS, fabomatic::Board::logic, logic, fabomatic::openConfigPortal(), fabomatic::printCompileSettings(), fabomatic::Board::rfid, rfid, fabomatic::Board::scheduler, fabomatic::conf::debug::SERIAL_SPEED_BDS, fabomatic::setupOTA(), fabomatic::esp32::setupWatchdog(), fabomatic::t_wdg, TAG, fabomatic::taskConnect(), and fabomatic::Tasks::Scheduler::updateSchedules().