Fab-O-Matic: fabomatic::Tasks Namespace Reference
fabomatic::Tasks Namespace Reference
This namespace contains the classes that implement a cooperative task scheduler.
Classes
class Scheduler
The schedule is in charge of running tasks in the right order based on their requested intervals.
class Task
A task class which represents a function to be called at requested intervals.
Typedefs
using milliseconds = std::chrono::milliseconds
typedef std::chrono::steady_clock::time_point time_point
Functions
auto delay (const milliseconds duration) -> void
Wait for a delay, allowing OTA updates.
auto arduinoNow () -> const time_point
Detailed Description
This namespace contains the classes that implement a cooperative task scheduler.
Typedef Documentation
milliseconds
typedef std::chrono::milliseconds fabomatic::Tasks::milliseconds
Definition at line 14 of file Tasks.cpp.
time_point
typedef std::chrono::steady_clock::time_point fabomatic::Tasks::time_point
Definition at line 15 of file Tasks.hpp.
Function Documentation
arduinoNow()
auto fabomatic::Tasks::arduinoNow () -> const time_point inline
Definition at line 17 of file Tasks.hpp.
  {
    return std::chrono::steady_clock::now();
  }
Referenced by fabomatic::Machine::canPowerOff(), fabomatic::BoardLogic::checkRfid(), delay(), fabomatic::MockMrfc522::getSimulatedUid(), fabomatic::Machine::getUsageDuration(), fabomatic::Machine::isShutdownImminent(), fabomatic::Machine::login(), fabomatic::Machine::logout(), fabomatic::BoardLogic::longTap(), fabomatic::Tasks::Task::run(), fabomatic::tests::run_for_duration(), fabomatic::MockMrfc522::setUid(), fabomatic::tests::simulate_rfid_card(), fabomatic::Tasks::Task::Task(), fabomatic::tests::test_normal_use(), fabomatic::tests::test_start_broker(), fabomatic::Tasks::Task::updateSchedule(), and fabomatic::FabBackend::waitForAnswer().
delay()
void fabomatic::Tasks::delay (const milliseconds duration) -> void
Wait for a delay, allowing OTA updates.
Parameters
duration period to wait
Definition at line 265 of file Tasks.cpp.
  {
    ArduinoOTA.handle();
    if (duration < 50ms)
    {
      ::delay(duration.count());
      return;
    }
    const auto &start = arduinoNow();
    do
    {
      ::delay(50);
      ArduinoOTA.handle();
    } while (arduinoNow() - start < duration);
  }
References arduinoNow(), and delay().
Referenced by fabomatic::BoardLogic::authorize(), fabomatic::Buzzer::beepFail(), fabomatic::Buzzer::beepOk(), fabomatic::FabBackend::connect(), fabomatic::FabBackend::connectWiFi(), delay(), fabomatic::FabBackend::disconnect(), fabomatic::Tasks::Scheduler::execute(), fabomatic::BoardLogic::getLcd(), fabomatic::BoardLogic::getRfid(), fabomatic::BoardLogic::logout(), fabomatic::BoardLogic::longTap(), fabomatic::BoardLogic::onNewCard(), fabomatic::Machine::power_mqtt(), fabomatic::FabBackend::processQuery(), fabomatic::FabBackend::publishWithReply(), fabomatic::Tasks::Task::setDelay(), setup(), fabomatic::taskConnect(), fabomatic::taskRfidWatchdog(), fabomatic::tests::test_whitelist_no_network(), fabomatic::Tasks::Task::updateSchedule(), and fabomatic::FabBackend::waitForAnswer().