Fab-O-Matic: fabomatic::tests Namespace Reference
fabomatic::tests Namespace Reference
Typedefs
using Task = fabomatic::Tasks::Task
using Scheduler = fabomatic::Tasks::Scheduler
Functions
void tearDown (void)
void setUp (void)
void test_steady_clock (void)
BoardLogic::Status simulate_rfid_card (RFIDWrapper< MockMrfc522 > &rfid, BoardLogic &logic, std::optional< card::uid_t > uid, std::optional< std::chrono::milliseconds > duration_tap)
Simulates RFID card tap.
void machine_init (BoardLogic &logic, RFIDWrapper< MockMrfc522 > &rfid)
Resets machine to initial state, clearing flags.
void test_machine_defaults ()
void test_simple_methods ()
void test_whitelist_no_network ()
void test_one_user_at_a_time ()
void test_user_autologoff ()
void test_machine_maintenance ()
void test_machine_allowed ()
void test_messages_buffered ()
void * threadMQTTServer (void *arg)
void test_create_buffered_messages ()
void test_check_transmission ()
void test_start_broker ()
void test_stop_broker ()
void test_fabserver_calls ()
void test_taskConnect ()
Opens WiFi and server connection and updates board state accordingly.
void test_taskCheckRfid ()
periodic check for new RFID card
void test_taskVarious ()
blink led
void test_taskEspWatchdog ()
Keep the ESP32 HW watchdog alive. If code gets stuck this will cause an automatic reset.
void test_taskRfidWatchdog ()
checks the RFID chip status and re-init it if necessary.
void test_taskMQTTAlive ()
sends the MQTT alive message
void test_normal_use ()
void test_defaults (void)
void test_changes (void)
void test_rfid_cache ()
void test_magic_number ()
bool test_deserialization (Buffer &buff)
void test_buffered_msg ()
void delete_tasks (void)
void create_tasks (Scheduler &scheduler, std::chrono::milliseconds period)
void run_for_duration (std::function< void()> callback, std::chrono::milliseconds duration)
void test_execute_runs_all_tasks (void)
void test_stop_start_tasks (void)
void test_esp32 ()
Variables
static constexpr WhiteList test_whitelist
fabomatic::RFIDWrapper< fabomatic::MockMrfc522 > rfid
fabomatic::LCDWrapper lcd {fabomatic::pins.lcd}
fabomatic::BoardLogic logic
fabomatic::MockMQTTBroker broker
fabomatic::Tasks::Scheduler test_scheduler
std::atomic< bool > exit_request {false}
auto t1 = Tasks::Task("taskConnect", 15s, &test_taskConnect, test_scheduler)
auto t2 = Tasks::Task("taskCheckRfid", 50ms, &test_taskCheckRfid, test_scheduler)
auto t3 = Tasks::Task("taskVarious", 1s, &test_taskVarious, test_scheduler)
auto t4 = Tasks::Task("taskEspWatchdog", 5s, &test_taskEspWatchdog, test_scheduler)
auto t5 = Tasks::Task("taskRfidWatchdog", 30s, &test_taskRfidWatchdog, test_scheduler)
auto t6 = Tasks::Task("taskMQTTAlive", 30s, &test_taskMQTTAlive, test_scheduler)
SavedConfig original
constexpr int NB_TASKS = 100
bool tasks_status [NB_TASKS] {false}
Task * tasks [NB_TASKS] {nullptr}
size_t task_counter {0}
Scheduler scheduler
const auto execute
Typedef Documentation
Scheduler
typedef fabomatic::Tasks::Scheduler fabomatic::tests::Scheduler
Definition at line 19 of file test_chrono.cpp.
Task
typedef fabomatic::Tasks::Task fabomatic::tests::Task
Definition at line 18 of file test_chrono.cpp.
Function Documentation
create_tasks()
void fabomatic::tests::create_tasks (Scheduler & scheduler, std::chrono::milliseconds period)
Definition at line 45 of file test_tasks.cpp.
  {
    // Clean-up
    task_counter = 0;
    for (auto &t : tasks_status)
    {
      t = false;
    }
    delete_tasks();
    // Creation
    for (size_t i = 0; i < NB_TASKS; ++i)
    {
      auto callback = [i]()
      {
        tasks_status[i] = true;
        task_counter++;
      };
      tasks[i] = new Task("T" + std::to_string(i), period, callback, scheduler, true);
      auto task = *tasks[i];
      TEST_ASSERT_MESSAGE(task.isActive(), "Task is not active");
      TEST_ASSERT_EQUAL_MESSAGE(period.count(), task.getPeriod().count(), "Task period is not 150ms");
    }
  }
References delete_tasks(), NB_TASKS, scheduler, task_counter, tasks, and tasks_status.
Referenced by test_execute_runs_all_tasks(), and test_stop_start_tasks().
delete_tasks()
void fabomatic::tests::delete_tasks (void)
Definition at line 28 of file test_tasks.cpp.
  {
    for (auto t : tasks)
    {
      if (t != nullptr)
      {
        scheduler.removeTask(t); // Because Task adds itself on creation
        delete t;
      }
    }
  }
References fabomatic::Tasks::Scheduler::removeTask(), scheduler, and tasks.
Referenced by create_tasks().
machine_init()
void fabomatic::tests::machine_init (BoardLogic & logic, RFIDWrapper< MockMrfc522 > & rfid)
Resets machine to initial state, clearing flags.
Definition at line 51 of file test_common.cpp.
  {
    auto &machine = logic.getMachineForTesting();
    machine.setAllowed(true);
    machine.setMaintenanceNeeded(false);
    logic.logout();
    simulate_rfid_card(rfid, logic, std::nullopt);
    TEST_ASSERT_TRUE_MESSAGE(logic.getStatus() == BoardLogic::Status::MachineFree, "machine_init: Status not MachineFree");
    TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().isFree(), "machine_init: machine not free");
  }
References fabomatic::BoardLogic::getMachine(), fabomatic::BoardLogic::getMachineForTesting(), fabomatic::BoardLogic::getStatus(), logic, fabomatic::BoardLogic::logout(), fabomatic::BoardLogic::MachineFree, rfid, and simulate_rfid_card().
Referenced by test_machine_allowed(), test_machine_maintenance(), test_one_user_at_a_time(), test_user_autologoff(), and test_whitelist_no_network().
run_for_duration()
void fabomatic::tests::run_for_duration (std::function< void()> callback, std::chrono::milliseconds duration)
Definition at line 70 of file test_tasks.cpp.
  {
    auto start = fabomatic::Tasks::arduinoNow();
    while (fabomatic::Tasks::arduinoNow() - start < duration)
    {
      callback();
    }
  }
References fabomatic::Tasks::arduinoNow().
Referenced by test_execute_runs_all_tasks(), and test_stop_start_tasks().
setUp()
void fabomatic::tests::setUp (void)
Definition at line 25 of file test_chrono.cpp.
  {
    // set stuff up here
  }
simulate_rfid_card()
BoardLogic::Status fabomatic::tests::simulate_rfid_card (RFIDWrapper< MockMrfc522 > & rfid, BoardLogic & logic, std::optional< card::uid_t > uid, std::optional< std::chrono::milliseconds > duration_tap)
Simulates RFID card tap.
Parameters
rfid RFID wrapper for simulation
logic Board logic, the checkRfid() method will be called repeatedly
uid card UID to tap
duration_tap duration of the tap. pass milliseconds::max() to keep the card in the field
Returns
Parameters
rfid RFID wrapper
logic Board logic
uid UID of the card to simulate or std::nullopt for no card
duration_tap Duration of the tap
Definition at line 20 of file test_common.cpp.
  {
    constexpr auto DEFAULT_CYCLES = 3;
    MockMrfc522 &driver = rfid.getDriver();
    driver.resetUid();
    for (auto i = 0; i < DEFAULT_CYCLES; i++)
    {
      logic.checkRfid();
    }
    if (uid.has_value())
    {
      driver.setUid(uid.value(), duration_tap);
      TEST_ASSERT_TRUE_MESSAGE(uid == rfid.getUid(), "Card UID not equal");
      auto start = fabomatic::Tasks::arduinoNow();
      do
      {
        logic.checkRfid();
        delay(50);
      } while (duration_tap.has_value() && fabomatic::Tasks::arduinoNow() - start < duration_tap);
    }
    else if (duration_tap)
    {
      delay(duration_tap.value().count());
    }
    return logic.getStatus();
  }
References fabomatic::Tasks::arduinoNow(), fabomatic::BoardLogic::checkRfid(), fabomatic::BoardLogic::getStatus(), logic, fabomatic::MockMrfc522::resetUid(), rfid, and fabomatic::MockMrfc522::setUid().
Referenced by machine_init(), test_machine_allowed(), test_machine_maintenance(), test_messages_buffered(), test_one_user_at_a_time(), test_user_autologoff(), and test_whitelist_no_network().
tearDown()
void fabomatic::tests::tearDown (void)
Definition at line 21 of file test_chrono.cpp.
  {
  }
test_buffered_msg()
void fabomatic::tests::test_buffered_msg ()
Definition at line 201 of file test_savedconfig.cpp.
  {
    constexpr auto NUM_MESSAGES = std::min(30, Buffer::MAX_MESSAGES - 3);
    Buffer buff;
    BufferedMsg msg1{"msg1", "topic1", false};
    BufferedMsg msg2{"msg2", "topic1", false};
    BufferedMsg msg3{"msg3", "topic2", false};
    std::vector messages{msg3, msg2, msg1};
    TEST_ASSERT_TRUE(msg1.mqtt_message == "msg1");
    TEST_ASSERT_TRUE(msg1.mqtt_topic == "topic1");
    TEST_ASSERT_TRUE(msg2.mqtt_message == "msg2");
    TEST_ASSERT_TRUE(msg2.mqtt_topic == "topic1");
    TEST_ASSERT_TRUE(msg3.mqtt_message == "msg3");
    TEST_ASSERT_TRUE(msg3.mqtt_topic == "topic2");
    // Create some more messages
    for (auto msg_num = 0; msg_num < NUM_MESSAGES; msg_num++)
    {
      std::string message{"{action=\"test\", value=\""};
      message.append(std::to_string(msg_num));
      message.append("\", test: true}");
      std::string topic{"machine/TESTTOPIC/"};
      topic.append(std::to_string(msg_num));
      messages.push_back({message, topic, true});
    }
    TEST_ASSERT_TRUE_MESSAGE(buff.hasChanged(), "Buffer has pending changes");
    // Nothing to test
    if constexpr (!conf::debug::ENABLE_BUFFERING)
      return;
    // Test insertion, messages must be queued newest first (msg3-msg2-msg1)
    auto msg_count = 0;
    for (const auto &msg : messages)
    {
      TEST_ASSERT_EQUAL_MESSAGE(msg_count, buff.count(), "Push_back: Buffer count is correct");
      const auto &bmsg = BufferedMsg{msg.mqtt_message, msg.mqtt_topic, msg.wait_for_answer};
      buff.push_front(bmsg);
      msg_count++;
    }
    TEST_ASSERT_EQUAL_MESSAGE(messages.size(), buff.count(), "Buffer contains all expected messages");
    TEST_ASSERT_TRUE_MESSAGE(buff.hasChanged(), "Buffer has pending changes");
    buff.setChanged(false);
    // Test retrieval oldest first (msg1-msg2-msg3-...)
    for (auto elem = messages.rbegin(); elem != messages.rend(); ++elem)
    {
      auto &msg = buff.getMessage();
      TEST_ASSERT_EQUAL_STRING_MESSAGE(elem->mqtt_message.c_str(), msg.mqtt_message.c_str(), "(1) Retrieval oldest first message is correct");
      TEST_ASSERT_EQUAL_STRING_MESSAGE(elem->mqtt_topic.c_str(), msg.mqtt_topic.c_str(), "(1) Retrieval oldest first topic is correct");
      TEST_ASSERT_EQUAL_MESSAGE(elem->wait_for_answer, msg.wait_for_answer, "(1) Retrieval oldest first wait_for_answer is correct");
    }
    TEST_ASSERT_EQUAL_MESSAGE(0, buff.count(), "Buffer is now empty");
    TEST_ASSERT_TRUE_MESSAGE(buff.hasChanged(), "Buffer has pending changes");
    buff.setChanged(false);
    // Test insertion in reverse order
    msg_count = 0;
    for (const auto &msg : messages)
    {
      TEST_ASSERT_EQUAL_MESSAGE(msg_count, buff.count(), "(1) Push_front: Buffer count is correct");
      const auto &bmsg = BufferedMsg{msg.mqtt_message, msg.mqtt_topic, msg.wait_for_answer};
      buff.push_back(bmsg);
      msg_count++;
    }
    TEST_ASSERT_TRUE_MESSAGE(buff.hasChanged(), "Buffer has pending changes");
    buff.setChanged(false);
    for (auto elem = messages.begin(); elem != messages.end(); ++elem)
    {
      auto &msg = buff.getMessage();
      TEST_ASSERT_EQUAL_STRING_MESSAGE(elem->mqtt_message.c_str(), msg.mqtt_message.c_str(), "(2) Retrieval oldest first message is correct");
      TEST_ASSERT_EQUAL_STRING_MESSAGE(elem->mqtt_topic.c_str(), msg.mqtt_topic.c_str(), "(2) Retrieval oldest first topic is correct");
      TEST_ASSERT_EQUAL_MESSAGE(elem->wait_for_answer, msg.wait_for_answer, "(2) Retrieval oldest first wait_for_answer is correct");
    }
    TEST_ASSERT_EQUAL_MESSAGE(0, buff.count(), "(2) Buffer is now empty");
    TEST_ASSERT_TRUE_MESSAGE(buff.hasChanged(), "Buffer has pending changes");
    buff.setChanged(false);
    // Test empty buffer
    TEST_ASSERT_TRUE_MESSAGE(test_deserialization(buff), "JSON works for empty buffer");
    TEST_ASSERT_FALSE_MESSAGE(buff.hasChanged(), "Buffer has no pending changes");
    // Insert more messages
    msg_count = 0;
    for (const auto &msg : messages)
    {
      TEST_ASSERT_EQUAL_MESSAGE(msg_count, buff.count(), "(2) Push_front: Buffer count is correct");
      const auto &bmsg = BufferedMsg{msg.mqtt_message, msg.mqtt_topic, msg.wait_for_answer};
      buff.push_back(bmsg);
      msg_count++;
    }
    TEST_ASSERT_TRUE_MESSAGE(test_deserialization(buff), "JSON works for full buffer");
    TEST_ASSERT_TRUE_MESSAGE(buff.hasChanged(), "Buffer has pending changes");
  }
References fabomatic::Buffer::count(), fabomatic::conf::debug::ENABLE_BUFFERING, fabomatic::Buffer::getMessage(), fabomatic::Buffer::hasChanged(), fabomatic::Buffer::MAX_MESSAGES, fabomatic::BufferedMsg::mqtt_message, fabomatic::Buffer::push_back(), fabomatic::Buffer::push_front(), fabomatic::Buffer::setChanged(), and test_deserialization().
Referenced by setup().
test_changes()
void fabomatic::tests::test_changes (void)
Definition at line 48 of file test_savedconfig.cpp.
  {
    auto result1 = SavedConfig::LoadFromEEPROM();
    TEST_ASSERT_TRUE_MESSAGE(result1.has_value(), "Loaded config is empty");
    auto result2 = SavedConfig::LoadFromEEPROM();
    TEST_ASSERT_TRUE_MESSAGE(result2.has_value(), "Loaded config is empty");
    auto &original = result1.value();
    auto &loaded = result2.value();
    loaded.ssid = "a";
    loaded.password = "b";
    loaded.mqtt_server = "c";
    loaded.mqtt_user = "d";
    loaded.mqtt_password = "e";
    loaded.mqtt_switch_topic = "f";
    loaded.machine_id = "9";
    // Save changes
    TEST_ASSERT_TRUE_MESSAGE(loaded.SaveToEEPROM(), "Loaded config save failed");
    result2 = SavedConfig::LoadFromEEPROM();
    TEST_ASSERT_TRUE_MESSAGE(result2.has_value(), "Loaded config is empty");
    auto &saved = result2.value();
    TEST_ASSERT_TRUE_MESSAGE(loaded.ssid == saved.ssid, "Loaded config ssid mismatch");
    TEST_ASSERT_TRUE_MESSAGE(loaded.password == saved.password, "Loaded config password mismatch");
    TEST_ASSERT_TRUE_MESSAGE(loaded.mqtt_server == saved.mqtt_server, "Loaded config mqtt_server mismatch");
    TEST_ASSERT_TRUE_MESSAGE(loaded.mqtt_user == saved.mqtt_user, "Loaded config mqtt_user mismatch");
    TEST_ASSERT_TRUE_MESSAGE(loaded.mqtt_password == saved.mqtt_password, "Loaded config mqtt_password mismatch");
    TEST_ASSERT_TRUE_MESSAGE(loaded.mqtt_switch_topic == saved.mqtt_switch_topic, "Loaded config mqtt_switch_topic mismatch");
    TEST_ASSERT_TRUE_MESSAGE(loaded.machine_id == saved.machine_id, "Loaded config machine_id mismatch");
    TEST_ASSERT_TRUE_MESSAGE(loaded.disablePortal == saved.disablePortal, "Loaded config disablePortal mismatch");
    TEST_ASSERT_TRUE_MESSAGE(SavedConfig::MAGIC_NUMBER == saved.magic_number, "Loaded config magic number mismatch");
    // Check that changes have been saved
    TEST_ASSERT_TRUE_MESSAGE(original.ssid != saved.ssid, "Loaded config ssid mismatch");
    TEST_ASSERT_TRUE_MESSAGE(original.password != saved.password, "Loaded config password mismatch");
    TEST_ASSERT_TRUE_MESSAGE(original.mqtt_server != saved.mqtt_server, "Loaded config mqtt_server mismatch");
    TEST_ASSERT_TRUE_MESSAGE(original.mqtt_user != saved.mqtt_user, "Loaded config mqtt_user mismatch");
    TEST_ASSERT_TRUE_MESSAGE(original.mqtt_password != saved.mqtt_password, "Loaded config mqtt_password mismatch");
    TEST_ASSERT_TRUE_MESSAGE(original.mqtt_switch_topic != saved.mqtt_switch_topic, "Loaded config mqtt_switch_topic mismatch");
    TEST_ASSERT_TRUE_MESSAGE(original.machine_id != saved.machine_id, "Loaded config machine_id mismatch");
    // Restore original
    TEST_ASSERT_TRUE_MESSAGE(original.SaveToEEPROM(), "Loaded config save failed");
  }
References fabomatic::SavedConfig::LoadFromEEPROM(), fabomatic::SavedConfig::machine_id, fabomatic::SavedConfig::MAGIC_NUMBER, fabomatic::SavedConfig::mqtt_password, fabomatic::SavedConfig::mqtt_server, fabomatic::SavedConfig::mqtt_switch_topic, fabomatic::SavedConfig::mqtt_user, original, fabomatic::SavedConfig::password, fabomatic::SavedConfig::SaveToEEPROM(), and fabomatic::SavedConfig::ssid.
Referenced by setup().
test_check_transmission()
void fabomatic::tests::test_check_transmission ()
Definition at line 79 of file test_mqtt.cpp.
  {
    auto &server = logic.getServer();
    TEST_ASSERT_TRUE_MESSAGE(server.hasBufferedMsg(), "(1) There are pending messages");
    TEST_ASSERT_TRUE_MESSAGE(server.connect(), "Server connect works");
    TEST_ASSERT_TRUE_MESSAGE(server.hasBufferedMsg(), "(2) There are pending messages");
    TEST_ASSERT_TRUE_MESSAGE(server.alive(), "Alive request works");
    // Since old messages must be sent first, the buffer shall be empty now
    TEST_ASSERT_FALSE_MESSAGE(server.hasBufferedMsg(), "There are no more pending messages");
    TEST_ASSERT_TRUE_MESSAGE(server.saveBuffer(), "Saving pending messages works");
  }
References fabomatic::FabBackend::alive(), fabomatic::FabBackend::connect(), fabomatic::BoardLogic::getServer(), fabomatic::FabBackend::hasBufferedMsg(), logic, and fabomatic::FabBackend::saveBuffer().
Referenced by setup().
test_create_buffered_messages()
void fabomatic::tests::test_create_buffered_messages ()
Definition at line 50 of file test_mqtt.cpp.
  {
    auto &server = logic.getServer();
    for (const auto &[uid, level, name] : secrets::cards::whitelist)
    {
      auto result = server.startUse(uid);
      TEST_ASSERT_FALSE_MESSAGE(result->request_ok, "(1) Request should have failed");
      result = server.inUse(uid, 1s);
      TEST_ASSERT_FALSE_MESSAGE(result->request_ok, "(2) Request should have failed");
      result = server.finishUse(uid, 2s);
      TEST_ASSERT_FALSE_MESSAGE(result->request_ok, "(3) Request should have failed");
      result = server.startUse(uid);
      TEST_ASSERT_FALSE_MESSAGE(result->request_ok, "(4) Request should have failed");
      result = server.finishUse(uid, 3s);
      TEST_ASSERT_FALSE_MESSAGE(result->request_ok, "(5) Request should have failed");
      result = server.registerMaintenance(uid);
      TEST_ASSERT_FALSE_MESSAGE(result->request_ok, "(6) Request should have failed");
    }
    // Should have generated 5 * 10 = 50 messages, truncated to 40.
    TEST_ASSERT_TRUE_MESSAGE(server.hasBufferedMsg(), "There are pending messages");
    TEST_ASSERT_TRUE_MESSAGE(server.saveBuffer(), "Saving pending messages works");
  }
References fabomatic::FabBackend::finishUse(), fabomatic::BoardLogic::getServer(), fabomatic::FabBackend::hasBufferedMsg(), fabomatic::FabBackend::inUse(), logic, fabomatic::FabBackend::registerMaintenance(), fabomatic::FabBackend::saveBuffer(), fabomatic::FabBackend::startUse(), and fabomatic::secrets::cards::whitelist.
Referenced by setup().
test_defaults()
void fabomatic::tests::test_defaults (void)
Definition at line 22 of file test_savedconfig.cpp.
  {
    SavedConfig config;
    auto defaults = SavedConfig::DefaultConfig();
    TEST_ASSERT_TRUE_MESSAGE(SavedConfig::MAGIC_NUMBER == defaults.magic_number, "Default config magic number mismatch");
    TEST_ASSERT_TRUE_MESSAGE(defaults.SaveToEEPROM(), "Default config save failed");
    auto result = SavedConfig::LoadFromEEPROM();
    TEST_ASSERT_TRUE_MESSAGE(result.has_value(), "Loaded config is empty");
    auto loaded = result.value();
    TEST_ASSERT_TRUE_MESSAGE(defaults.ssid == loaded.ssid, "Loaded config ssid mismatch");
    TEST_ASSERT_TRUE_MESSAGE(defaults.password == loaded.password, "Loaded config password mismatch");
    TEST_ASSERT_TRUE_MESSAGE(defaults.mqtt_server == loaded.mqtt_server, "Loaded config mqtt_server mismatch");
    TEST_ASSERT_TRUE_MESSAGE(defaults.mqtt_user == loaded.mqtt_user, "Loaded config mqtt_user mismatch");
    TEST_ASSERT_TRUE_MESSAGE(defaults.mqtt_password == loaded.mqtt_password, "Loaded config mqtt_password mismatch");
    TEST_ASSERT_TRUE_MESSAGE(defaults.mqtt_switch_topic == loaded.mqtt_switch_topic, "Loaded config mqtt_switch_topic mismatch");
    TEST_ASSERT_TRUE_MESSAGE(defaults.machine_id == loaded.machine_id, "Loaded config machine_id mismatch");
    TEST_ASSERT_TRUE_MESSAGE(SavedConfig::MAGIC_NUMBER == loaded.magic_number, "Loaded config magic number mismatch");
    // Test set and get methods
    auto id = MachineID(123);
    loaded.setMachineID(id);
    TEST_ASSERT_TRUE_MESSAGE(id == loaded.getMachineID(), "Loaded config machine_id mismatch");
  }
References fabomatic::SavedConfig::DefaultConfig(), fabomatic::SavedConfig::LoadFromEEPROM(), and fabomatic::SavedConfig::MAGIC_NUMBER.
Referenced by setup().
test_deserialization()
bool fabomatic::tests::test_deserialization (Buffer & buff)
Definition at line 173 of file test_savedconfig.cpp.
  {
    JsonDocument json_doc;
    buff.toJson(json_doc, "message_buffer");
    std::string json_text;
    auto chars = serializeJson(json_doc, json_text);
    TEST_ASSERT_GREATER_THAN_MESSAGE(0, chars, "Non empty JSON text");
    ESP_LOGD(TAG, "test_deserialization: json_text:%s", json_text.c_str());
    auto result = Buffer::fromJsonElement(json_doc["message_buffer"]);
    TEST_ASSERT_TRUE_MESSAGE(result.has_value(), "Deserialization succeeds");
    auto &new_buff = result.value();
    TEST_ASSERT_EQUAL_MESSAGE(buff.count(), new_buff.count(), "Messages are lost in json");
    while (new_buff.count() > 0)
    {
      const auto &msg_new = new_buff.getMessage();
      const auto &msg_old = buff.getMessage();
      TEST_ASSERT_EQUAL_STRING_MESSAGE(msg_new.mqtt_message.c_str(), msg_old.mqtt_message.c_str(), "Messages are in different order or damaged");
      TEST_ASSERT_EQUAL_STRING_MESSAGE(msg_new.mqtt_topic.c_str(), msg_old.mqtt_topic.c_str(), "Topics are in different order or damaged");
      TEST_ASSERT_EQUAL_MESSAGE(msg_new.wait_for_answer, msg_old.wait_for_answer, "Wait flags are in different order or damaged");
    }
    return true;
  }
References fabomatic::Buffer::count(), fabomatic::Buffer::fromJsonElement(), fabomatic::Buffer::getMessage(), TAG, and fabomatic::Buffer::toJson().
Referenced by test_buffered_msg().
test_esp32()
void fabomatic::tests::test_esp32 ()
Definition at line 133 of file test_tasks.cpp.
  {
    auto result = fabomatic::esp32::esp_serial();
    TEST_ASSERT_GREATER_OR_EQUAL_UINT32_MESSAGE(0, result.length(), "ESP32 serial must be non empty");
    auto mem_free = fabomatic::esp32::getFreeHeap();
    TEST_ASSERT_GREATER_OR_EQUAL_UINT32_MESSAGE(0, mem_free, "ESP32 mem free must be > 0");
    fabomatic::esp32::showHeapStats();
    TEST_ASSERT_TRUE_MESSAGE(fabomatic::esp32::setupWatchdog(30s), "Watchdog setup");
    fabomatic::esp32::removeWatchdog();
  }
References fabomatic::esp32::esp_serial(), fabomatic::esp32::getFreeHeap(), fabomatic::esp32::removeWatchdog(), fabomatic::esp32::setupWatchdog(), and fabomatic::esp32::showHeapStats().
Referenced by setup().
test_execute_runs_all_tasks()
void fabomatic::tests::test_execute_runs_all_tasks (void)
Definition at line 84 of file test_tasks.cpp.
  {
    create_tasks(scheduler, 150ms);
    TEST_ASSERT_EQUAL_MESSAGE(NB_TASKS, scheduler.taskCount(), "Scheduler does not contain all tasks");
    scheduler.updateSchedules();
    run_for_duration(execute, 140ms);
    TEST_ASSERT_EQUAL_MESSAGE(NB_TASKS, task_counter, "All tasks were not called once in 140 ms");
    delay(50);
    task_counter = 0;
    run_for_duration(execute, 100ms);
    TEST_ASSERT_EQUAL_MESSAGE(NB_TASKS, task_counter, "All tasks were not called once again after 150 ms");
  }
References create_tasks(), execute, NB_TASKS, run_for_duration(), scheduler, task_counter, fabomatic::Tasks::Scheduler::taskCount(), and fabomatic::Tasks::Scheduler::updateSchedules().
Referenced by setup().
test_fabserver_calls()
void fabomatic::tests::test_fabserver_calls ()
Definition at line 133 of file test_mqtt.cpp.
  {
    const int NB_TESTS = 10;
    const int NB_MACHINES = 5;
    auto &server = logic.getServer();
    for (uint16_t mid = 100; mid <= 100 + NB_MACHINES; mid++)
    {
      // Change MachineID on the fly
      auto saved_config = SavedConfig::DefaultConfig();
      saved_config.setMachineID(mid);
      saved_config.mqtt_server.assign("127.0.0.1");
      ESP_LOGI(TAG3, "Testing machine %d", mid);
      server.configure(saved_config);
      auto connected = false;
      for (auto i = 0; i < 3; i++)
      {
        server.disconnect(); // Force disconnect
        if (connected |= server.connect())
        {
          break;
        }
      }
      TEST_ASSERT_TRUE_MESSAGE(connected, "Server connect failed");
      TEST_ASSERT_TRUE_MESSAGE(server.isOnline(), "Server is not online");
      for (auto i = 0; i < NB_TESTS; ++i)
      {
        server.loop();
        card::uid_t uid = 123456789 + i;
        auto response = server.checkCard(uid);
        TEST_ASSERT_TRUE_MESSAGE(response != nullptr, "Server checkCard failed");
        ESP_LOGD(TAG3, "Server checkCard response: %s", response->toString().c_str());
        TEST_ASSERT_TRUE_MESSAGE(response->request_ok, "Server checkCard request failed");
        auto machine_resp = server.checkMachine(); // Machine ID is in the topic already
        TEST_ASSERT_TRUE_MESSAGE(machine_resp != nullptr, "Server checkMachine failed");
        TEST_ASSERT_TRUE_MESSAGE(machine_resp->request_ok, "Server checkMachine request failed");
        auto maintenance_resp = server.registerMaintenance(uid);
        TEST_ASSERT_TRUE_MESSAGE(maintenance_resp != nullptr, "Server registerMaintenance failed");
        TEST_ASSERT_TRUE_MESSAGE(maintenance_resp->request_ok, "Server registerMaintenance request failed");
        auto start_use_resp = server.startUse(uid);
        TEST_ASSERT_TRUE_MESSAGE(start_use_resp != nullptr, "Server startUse failed");
        TEST_ASSERT_TRUE_MESSAGE(start_use_resp->request_ok, "Server startUse request failed");
        auto in_use_resp = server.inUse(uid, 5s);
        TEST_ASSERT_TRUE_MESSAGE(in_use_resp != nullptr, "Server inUse failed");
        TEST_ASSERT_TRUE_MESSAGE(in_use_resp->request_ok, "Server inUse request failed");
        auto stop_use_resp = server.finishUse(uid, 10s);
        TEST_ASSERT_TRUE_MESSAGE(stop_use_resp != nullptr, "Server stopUse failed");
        TEST_ASSERT_TRUE_MESSAGE(stop_use_resp->request_ok, "Server stopUse request failed");
        auto alive_resp = server.alive();
        TEST_ASSERT_TRUE_MESSAGE(alive_resp, "Server alive failed");
      }
    }
    // Test authentication in online scenario
    AuthProvider auth(secrets::cards::whitelist);
    TEST_ASSERT_TRUE_MESSAGE(server.connect(), "Server is online");
    for (const auto &[uid, level, name] : secrets::cards::whitelist)
    {
      server.loop();
      auto response = auth.tryLogin(uid, server);
      TEST_ASSERT_TRUE_MESSAGE(response.has_value(), "Server checkCard failed");
      if (level == FabUser::UserLevel::Unknown)
      {
        TEST_ASSERT_FALSE_MESSAGE(response.value().authenticated, "Server returned authenticated user for invalid one");
      }
      else
      {
        TEST_ASSERT_TRUE_MESSAGE(response.value().authenticated, "Server returned unauthenticated user for a valid one");
        TEST_ASSERT_TRUE_MESSAGE(response.value().user_level == level, "Server returned wrong user level");
      }
    }
    // Test that saving the cache works
    TEST_ASSERT_TRUE_MESSAGE(auth.saveCache(), "AuthProvider saveCache failed");
    // Test that the cache contains all the valid whitelist entries
    auto cached_entries = SavedConfig::LoadFromEEPROM().value().cachedRfid;
    for (const auto &[uid, level, name] : secrets::cards::whitelist)
    {
      const auto &cached_card = cached_entries.find_uid(uid);
      TEST_ASSERT_TRUE_MESSAGE(cached_card || level == FabUser::UserLevel::Unknown,
                               "AuthProvider saveCache failed to save all whitelist entries");
    }
  }
References fabomatic::FabBackend::alive(), fabomatic::FabBackend::checkCard(), fabomatic::FabBackend::checkMachine(), fabomatic::FabBackend::configure(), fabomatic::FabBackend::connect(), fabomatic::SavedConfig::DefaultConfig(), fabomatic::FabBackend::disconnect(), fabomatic::FabBackend::finishUse(), fabomatic::BoardLogic::getServer(), fabomatic::FabBackend::inUse(), fabomatic::FabBackend::isOnline(), fabomatic::SavedConfig::LoadFromEEPROM(), logic, fabomatic::FabBackend::loop(), fabomatic::FabBackend::registerMaintenance(), fabomatic::AuthProvider::saveCache(), fabomatic::FabBackend::startUse(), TAG3, fabomatic::AuthProvider::tryLogin(), fabomatic::FabUser::Unknown, and fabomatic::secrets::cards::whitelist.
Referenced by setup().
test_machine_allowed()
void fabomatic::tests::test_machine_allowed ()
Definition at line 290 of file test_logic.cpp.
  {
    machine_init(logic, rfid);
    auto &machine = logic.getMachineForTesting();
    auto card_fabuser = get_test_uid(3);
    auto card_admin = get_test_uid(0);
    machine.setAllowed(false);
    machine.setMaintenanceNeeded(false);
    // check if blocked for normal users
    simulate_rfid_card(rfid, logic, card_fabuser);
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::NotAllowed, logic.getStatus(), "Status not NotAllowed");
    simulate_rfid_card(rfid, logic, std::nullopt);
    // still blocked for admins
    simulate_rfid_card(rfid, logic, card_admin);
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::NotAllowed, logic.getStatus(), "Status not NotAllowed for admins");
    simulate_rfid_card(rfid, logic, std::nullopt);
  }
References get_test_uid(), fabomatic::BoardLogic::getMachineForTesting(), fabomatic::BoardLogic::getStatus(), logic, machine_init(), fabomatic::BoardLogic::NotAllowed, rfid, and simulate_rfid_card().
Referenced by setup().
test_machine_defaults()
void fabomatic::tests::test_machine_defaults ()
Definition at line 41 of file test_logic.cpp.
  {
    auto &machine = logic.getMachine();
    TEST_ASSERT_TRUE_MESSAGE(machine.isConfigured(), "Machine not configured");
    auto config_req = machine.getConfig();
    TEST_ASSERT_TRUE_MESSAGE(config_req.has_value(), "Machine config not available");
    auto config = config_req.value();
    auto result = machine.getMachineId().id == fabomatic::conf::default_config::machine_id.id;
    TEST_ASSERT_TRUE_MESSAGE(result, "Machine ID not per default configuration");
    result = machine.getMachineName() == fabomatic::conf::default_config::machine_name;
    TEST_ASSERT_TRUE_MESSAGE(result, "Machine Name not per default configuration");
    result = machine.getAutologoffDelay() == fabomatic::conf::machine::DEFAULT_AUTO_LOGOFF_DELAY;
    TEST_ASSERT_TRUE_MESSAGE(result, "Machine autologoff delay not per default configuration");
    result = machine.toString().length() > 0;
    TEST_ASSERT_TRUE_MESSAGE(result, "Machine toString() failed");
    TEST_ASSERT_TRUE_MESSAGE(config.hasRelay() || fabomatic::pins.relay.ch1_pin == fabomatic::NO_PIN, "Machine relay not configured");
    TEST_ASSERT_TRUE_MESSAGE(config.hasMqttSwitch() || fabomatic::conf::mqtt::mqtt_switch_topic.empty(), "Machine MQTT switch not configured");
    TEST_ASSERT_TRUE_MESSAGE(config.machine_id.id == fabomatic::conf::default_config::machine_id.id, "Machine ID not configured");
  }
References fabomatic::pins_config::relay_config::ch1_pin, fabomatic::conf::machine::DEFAULT_AUTO_LOGOFF_DELAY, fabomatic::BoardLogic::getMachine(), MachineID::id, logic, fabomatic::conf::default_config::machine_id, fabomatic::conf::default_config::machine_name, fabomatic::conf::mqtt::mqtt_switch_topic, fabomatic::NO_PIN, fabomatic::pins, and fabomatic::pins_config::relay.
Referenced by setup().
test_machine_maintenance()
void fabomatic::tests::test_machine_maintenance ()
Definition at line 260 of file test_logic.cpp.
  {
    machine_init(logic, rfid);
    auto &machine = logic.getMachineForTesting();
    const auto card_fabuser = get_test_uid(2);
    const auto card_admin = get_test_uid(0);
    machine.setAllowed(true);
    machine.setMaintenanceNeeded(true);
    simulate_rfid_card(rfid, logic, card_fabuser);
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::MaintenanceNeeded, logic.getStatus(), "Status not MaintenanceNeeded");
    simulate_rfid_card(rfid, logic, std::nullopt);
    simulate_rfid_card(rfid, logic, card_admin, conf::machine::LONG_TAP_DURATION + 10s); // Log in + Conferma manutenzione perch non ritorna prima della conclusione
    simulate_rfid_card(rfid, logic, std::nullopt);                                       // Card away
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::MachineInUse, logic.getStatus(), "Status not MachineInUse by admin");
    TEST_ASSERT_FALSE_MESSAGE(logic.getMachine().isMaintenanceNeeded(), "Maintenance not cleared by admin");
    // Logoff admin
    simulate_rfid_card(rfid, logic, card_admin);
    TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().isFree(), "Machine is not free");
    simulate_rfid_card(rfid, logic, std::nullopt);
    // Now try to logon with fabuser (should succeed because maintenance is cleared)
    simulate_rfid_card(rfid, logic, card_fabuser);
    simulate_rfid_card(rfid, logic, std::nullopt);
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::MachineInUse, logic.getStatus(), "Status not MachineInUse by normal user");
  }
References get_test_uid(), fabomatic::BoardLogic::getMachine(), fabomatic::BoardLogic::getMachineForTesting(), fabomatic::BoardLogic::getStatus(), logic, fabomatic::conf::machine::LONG_TAP_DURATION, machine_init(), fabomatic::BoardLogic::MachineInUse, fabomatic::BoardLogic::MaintenanceNeeded, rfid, and simulate_rfid_card().
Referenced by setup().
test_magic_number()
void fabomatic::tests::test_magic_number ()
Definition at line 152 of file test_savedconfig.cpp.
  {
    auto result1 = SavedConfig::LoadFromEEPROM();
    TEST_ASSERT_TRUE_MESSAGE(result1.has_value(), "Loaded config is empty");
    auto loaded = result1.value();
    auto original_magic = loaded.magic_number;
    loaded.magic_number++;
    TEST_ASSERT_TRUE_MESSAGE(loaded.SaveToEEPROM(), "Loaded config save failed");
    TEST_ASSERT_EQUAL_MESSAGE(original_magic, loaded.magic_number, "Magic number overwritten by application");
    // Force abnormal case after FW update
    TEST_ASSERT_TRUE(EEPROM.begin(sizeof(SavedConfig)));
    loaded.magic_number = SavedConfig::MAGIC_NUMBER - 1;
    EEPROM.put(0, &loaded);
    TEST_ASSERT_TRUE(EEPROM.commit());
    // Now check the loaded version is null due to version mismatch
    auto result2 = SavedConfig::LoadFromEEPROM();
    TEST_ASSERT_FALSE_MESSAGE(result2.has_value(), "Loaded config is not empty");
  }
References fabomatic::SavedConfig::LoadFromEEPROM(), and fabomatic::SavedConfig::MAGIC_NUMBER.
Referenced by setup().
test_messages_buffered()
void fabomatic::tests::test_messages_buffered ()
Definition at line 312 of file test_logic.cpp.
  {
    auto card_admin = get_test_uid(0);
    auto &backend = logic.getServer();
    simulate_rfid_card(rfid, logic, card_admin, 500ms); // Start use
    delay(1);                                           // 1s usage
    simulate_rfid_card(rfid, logic, card_admin, 500ms); // End use
    TEST_ASSERT_TRUE_MESSAGE(backend.hasBufferedMsg(), "Messages have been buffered");
    auto result = backend.transmitBuffer();
    TEST_ASSERT_FALSE_MESSAGE(result, "Retransmission fails");
    auto save_result = backend.saveBuffer();
    TEST_ASSERT_TRUE_MESSAGE(save_result, "Saving buffered messages works");
    auto sc = SavedConfig::LoadFromEEPROM();
    TEST_ASSERT_TRUE_MESSAGE(sc.has_value(), "SavedConfig has valid contents");
    backend.configure(sc.value());
    TEST_ASSERT_TRUE_MESSAGE(backend.hasBufferedMsg(), "Reloading buffered messages works");
  }
References get_test_uid(), fabomatic::BoardLogic::getServer(), fabomatic::SavedConfig::LoadFromEEPROM(), logic, rfid, and simulate_rfid_card().
Referenced by setup().
test_normal_use()
void fabomatic::tests::test_normal_use ()
Definition at line 324 of file test_mqtt.cpp.
  {
    test_scheduler.updateSchedules();
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(6, test_scheduler.taskCount(), "Scheduler does not contain all tasks");
    auto start = fabomatic::Tasks::arduinoNow();
    while (fabomatic::Tasks::arduinoNow() - start <= 1min)
    {
      test_scheduler.execute();
      delay(25);
    }
    // Check that all tasks ran at least once
    for (const auto tp : test_scheduler.getTasks())
    {
      const auto t = *tp;
      ESP_LOGD(TAG3, "Task %s: %lu runs, %llu ms total runtime, %llu ms avg tardiness", t.getId().c_str(), t.getRunCounter(), t.getTotalRuntime().count(), t.getAvgTardiness().count());
      TEST_ASSERT_GREATER_OR_EQUAL_MESSAGE(1, t.getRunCounter(), "Task did not run");
    }
    // Remove the HW Watchdog
    esp32::removeWatchdog();
  }
References fabomatic::Tasks::arduinoNow(), fabomatic::Tasks::Scheduler::execute(), fabomatic::Tasks::Scheduler::getTasks(), fabomatic::esp32::removeWatchdog(), TAG3, fabomatic::Tasks::Scheduler::taskCount(), test_scheduler, and fabomatic::Tasks::Scheduler::updateSchedules().
Referenced by setup().
test_one_user_at_a_time()
void fabomatic::tests::test_one_user_at_a_time ()
Definition at line 163 of file test_logic.cpp.
  {
    machine_init(logic, rfid);
    const auto card_uid = get_test_uid(0);
    auto new_state = simulate_rfid_card(rfid, logic, card_uid);
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::LoggedIn, new_state, "Status not LoggedIn");
    TEST_ASSERT_TRUE_MESSAGE(!logic.getMachine().isFree(), "Machine is free");
    // Card away, machine shall be busy
    new_state = simulate_rfid_card(rfid, logic, std::nullopt);
    TEST_ASSERT_TRUE_MESSAGE(!logic.getMachine().isFree(), "Machine is free");
    // New card, shall be denied
    const auto card_uid2 = get_test_uid(1);
    simulate_rfid_card(rfid, logic, card_uid2, 100ms);
    TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().getActiveUser().card_uid == card_uid, "User UID has changed");
    // New card away, first user shall still be here
    simulate_rfid_card(rfid, logic, std::nullopt);
    TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().getActiveUser().card_uid == card_uid, "User UID has changed");
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::MachineInUse, logic.getStatus(), "Status not MachineInUse");
    // Original card, shall log out
    simulate_rfid_card(rfid, logic, card_uid);
    TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().isFree(), "Machine is not free");
    // Original card away
    simulate_rfid_card(rfid, logic, std::nullopt);
    TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().isFree(), "Machine is not free");
    // Now new card must succeed
    simulate_rfid_card(rfid, logic, card_uid2);
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::LoggedIn, logic.getStatus(), "Status not LoggedIn");
    // Card away
    simulate_rfid_card(rfid, logic, std::nullopt);
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::MachineInUse, logic.getStatus(), "Status not MachineInUse");
    TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().getActiveUser().card_uid == card_uid2, "User UID is not expected");
    TEST_ASSERT_TRUE_MESSAGE(!logic.getMachine().isFree(), "Machine is free");
    auto save_result = logic.getServer().saveBuffer();
    TEST_ASSERT_TRUE_MESSAGE(save_result, "Saving buffered messages works");
  }
References get_test_uid(), fabomatic::BoardLogic::getMachine(), fabomatic::BoardLogic::getServer(), fabomatic::BoardLogic::getStatus(), fabomatic::BoardLogic::LoggedIn, logic, machine_init(), fabomatic::BoardLogic::MachineInUse, rfid, and simulate_rfid_card().
Referenced by setup().
test_rfid_cache()
void fabomatic::tests::test_rfid_cache ()
Definition at line 94 of file test_savedconfig.cpp.
  {
    auto defaults = SavedConfig::DefaultConfig();
    defaults.SaveToEEPROM();
    TEST_ASSERT_TRUE_MESSAGE(defaults.cachedRfid.size() == conf::rfid_tags::CACHE_LEN, "Default config cachedRfid size mismatch");
    // Test that default config has empty cache
    for (auto i = 0; i < defaults.cachedRfid.size(); i++)
    {
      const auto &tag = defaults.cachedRfid[i];
      TEST_ASSERT_TRUE_MESSAGE(tag.uid == 0, "Default config cachedRfid not empty");
      TEST_ASSERT_TRUE_MESSAGE(tag.level == FabUser::UserLevel::Unknown, "Default config cachedRfid not empty");
    }
    AuthProvider authProvider(secrets::cards::whitelist);
    TEST_ASSERT_TRUE_MESSAGE(authProvider.saveCache(), "AuthProvider saveCache failed");
    defaults = SavedConfig::LoadFromEEPROM().value_or(SavedConfig::DefaultConfig());
    // Test that default config is still empty
    for (auto i = 0; i < defaults.cachedRfid.size(); i++)
    {
      const auto &tag = defaults.cachedRfid[i];
      TEST_ASSERT_TRUE_MESSAGE(tag.uid == 0, "Default config cachedRfid not empty after AuthProvider saveCache");
      TEST_ASSERT_TRUE_MESSAGE(tag.level == FabUser::UserLevel::Unknown, "Default config cachedRfid not empty after AuthProvider saveCache");
    }
    FabBackend server;
    defaults.mqtt_server = "INVALID_SERVER"; // Must be invalid to test the cache
    server.configure(defaults);
    auto [wl_uid, wl_level, name] = secrets::cards::whitelist[0];
    auto result = authProvider.tryLogin(wl_uid, server);
    TEST_ASSERT_TRUE_MESSAGE(result.has_value(), "AuthProvider tryLogin failed");
    // Now save the positive result (should not be do anything, because offline)
    TEST_ASSERT_TRUE_MESSAGE(authProvider.saveCache(), "AuthProvider saveCache 2 failed");
    // Reload the cache
    defaults = SavedConfig::LoadFromEEPROM().value_or(SavedConfig::DefaultConfig());
    TEST_ASSERT_TRUE_MESSAGE(0 == defaults.cachedRfid[0].uid, "AuthProvider tryLogin card_uid mismatch");
    TEST_ASSERT_TRUE_MESSAGE(FabUser::UserLevel::Unknown == defaults.cachedRfid[0].level, "AuthProvider tryLogin user_level mismatch");
    // Generate many events
    for (auto i = 0; i < 50; i++)
    {
      auto rnd = random(0, conf::rfid_tags::CACHE_LEN);
      auto result = authProvider.tryLogin(defaults.cachedRfid[rnd].uid, server);
    }
    TEST_ASSERT_TRUE_MESSAGE(authProvider.saveCache(), "AuthProvider saveCache 2 failed");
    defaults = SavedConfig::LoadFromEEPROM().value_or(SavedConfig::DefaultConfig());
    // Online scenario with cache is testing in MQTT testcase with the broker.
  }
References fabomatic::conf::rfid_tags::CACHE_LEN, fabomatic::FabBackend::configure(), fabomatic::SavedConfig::DefaultConfig(), fabomatic::SavedConfig::LoadFromEEPROM(), fabomatic::AuthProvider::saveCache(), fabomatic::AuthProvider::tryLogin(), fabomatic::FabUser::Unknown, and fabomatic::secrets::cards::whitelist.
Referenced by setup().
test_simple_methods()
void fabomatic::tests::test_simple_methods ()
Definition at line 70 of file test_logic.cpp.
  {
    {
      auto cpt = logic.getBuzzerForTesting()->getBeepCount();
      logic.beepFail();
      auto beeps = logic.getBuzzerForTesting()->getBeepCount() - cpt;
      TEST_ASSERT_EQUAL_UINT16_MESSAGE(conf::buzzer::NB_BEEPS, beeps, "Buzzer FAIL has been beeped");
    }
    {
      auto cpt = logic.getBuzzerForTesting()->getBeepCount();
      logic.beepOk();
      auto beeps = logic.getBuzzerForTesting()->getBeepCount() - cpt;
      TEST_ASSERT_EQUAL_UINT16_MESSAGE(1, beeps, "Buzzer OK has been beeped");
    }
    logic.blinkLed();
    std::vector statuses{BoardLogic::Status::Error, BoardLogic::Status::ErrorHardware, BoardLogic::Status::Connected,
                         BoardLogic::Status::Connecting, BoardLogic::Status::Clear, BoardLogic::Status::MachineFree,
                         BoardLogic::Status::LoggedIn, BoardLogic::Status::LoginDenied, BoardLogic::Status::Busy,
                         BoardLogic::Status::LoggedOut, BoardLogic::Status::AlreadyInUse, BoardLogic::Status::MachineInUse,
                         BoardLogic::Status::Offline, BoardLogic::Status::NotAllowed, BoardLogic::Status::Verifying,
                         BoardLogic::Status::MaintenanceNeeded, BoardLogic::Status::MaintenanceQuery,
                         BoardLogic::Status::MaintenanceDone, BoardLogic::Status::PortalStarting, BoardLogic::Status::PortalFailed,
                         BoardLogic::Status::PortalSuccess, BoardLogic::Status::Booting, BoardLogic::Status::ShuttingDown,
                         BoardLogic::Status::OTAStarting, BoardLogic::Status::FactoryDefaults};
    for (const auto status : statuses)
    {
      logic.changeStatus(status);
      TEST_ASSERT_EQUAL_UINT8_MESSAGE(status, logic.getStatus(), "Status mismatch");
    }
    logic.getMachineForTesting().setMaintenanceInfo("Lente laser");
    logic.getMachineForTesting().setMaintenanceNeeded(true);
    logic.changeStatus(BoardLogic::Status::MachineFree);
    sleep(2);
    for (auto i = 0; i < 3; ++i)
    {
      logic.checkPowerOff();
      logic.blinkLed();
      logic.updateLCD();
      logic.reconfigure();
    }
  }
References fabomatic::BoardLogic::AlreadyInUse, fabomatic::BoardLogic::beepFail(), fabomatic::BoardLogic::beepOk(), fabomatic::BoardLogic::blinkLed(), fabomatic::BoardLogic::Booting, fabomatic::BoardLogic::Busy, fabomatic::BoardLogic::changeStatus(), fabomatic::BoardLogic::checkPowerOff(), fabomatic::BoardLogic::Clear, fabomatic::BoardLogic::Connected, fabomatic::BoardLogic::Connecting, fabomatic::BoardLogic::Error, fabomatic::BoardLogic::ErrorHardware, fabomatic::BoardLogic::FactoryDefaults, fabomatic::BoardLogic::getBuzzerForTesting(), fabomatic::BoardLogic::getMachineForTesting(), fabomatic::BoardLogic::getStatus(), fabomatic::BoardLogic::LoggedIn, fabomatic::BoardLogic::LoggedOut, logic, fabomatic::BoardLogic::LoginDenied, fabomatic::BoardLogic::MachineFree, fabomatic::BoardLogic::MachineInUse, fabomatic::BoardLogic::MaintenanceDone, fabomatic::BoardLogic::MaintenanceNeeded, fabomatic::BoardLogic::MaintenanceQuery, fabomatic::conf::buzzer::NB_BEEPS, fabomatic::BoardLogic::NotAllowed, fabomatic::BoardLogic::Offline, fabomatic::BoardLogic::OTAStarting, fabomatic::BoardLogic::PortalFailed, fabomatic::BoardLogic::PortalStarting, fabomatic::BoardLogic::PortalSuccess, fabomatic::BoardLogic::reconfigure(), fabomatic::BoardLogic::ShuttingDown, fabomatic::BoardLogic::updateLCD(), and fabomatic::BoardLogic::Verifying.
Referenced by setup().
test_start_broker()
void fabomatic::tests::test_start_broker ()
Definition at line 97 of file test_mqtt.cpp.
  {
    auto &server = logic.getServer();
    server.setChannel(-1);
    TEST_ASSERT_TRUE_MESSAGE(server.connectWiFi(), "WiFi works");
    // Set the same IP Adress as MQTT server
    auto config = SavedConfig::LoadFromEEPROM();
    TEST_ASSERT_TRUE_MESSAGE(config.has_value(), "Config load failed");
    config.value().mqtt_server.assign("127.0.0.1");
    TEST_ASSERT_TRUE_MESSAGE(config.value().SaveToEEPROM(), "Config save failed");
    server.configure(config.value());
    // Start MQTT server thread in simulation
    attr_mqtt_broker.stacksize = 3 * 1024; // Required for ESP32-S2
    attr_mqtt_broker.detachstate = PTHREAD_CREATE_DETACHED;
    exit_request = false;
    pthread_create(&thread_mqtt_broker, &attr_mqtt_broker, threadMQTTServer, NULL);
    auto start = fabomatic::Tasks::arduinoNow();
    constexpr auto timeout = 5s;
    while (!broker.isRunning() && fabomatic::Tasks::arduinoNow() - start < timeout)
    {
      delay(100);
    }
    TEST_ASSERT_TRUE_MESSAGE(broker.isRunning(), "MQTT server not running");
    delay(5000);
    TEST_ASSERT_TRUE_MESSAGE(server.connect(), "Server connect failed in start MQTT");
  }
References fabomatic::Tasks::arduinoNow(), attr_mqtt_broker, broker, fabomatic::FabBackend::configure(), fabomatic::FabBackend::connect(), fabomatic::FabBackend::connectWiFi(), exit_request, fabomatic::BoardLogic::getServer(), fabomatic::MockMQTTBroker::isRunning(), fabomatic::SavedConfig::LoadFromEEPROM(), logic, fabomatic::FabBackend::setChannel(), thread_mqtt_broker, and threadMQTTServer().
Referenced by setup().
test_steady_clock()
void fabomatic::tests::test_steady_clock (void)
Definition at line 30 of file test_chrono.cpp.
  {
    static constexpr auto nb_tests = 100;
    auto cpt = 0;
    TEST_ASSERT_TRUE_MESSAGE(std::chrono::steady_clock::is_steady, "Steady clock available");
    auto previous_val = std::chrono::steady_clock::now();
    while (cpt < nb_tests)
    {
      auto val = std::chrono::steady_clock::now();
      auto duration = (val - previous_val);
      auto count = duration.count();
      std::stringstream ss{};
      ss << "Duration = " << duration << ", tse=" << val.time_since_epoch();
      auto log = ss.str().c_str();
      ESP_LOGI(TAG4, "%s", log);
      TEST_ASSERT_GREATER_THAN_MESSAGE(0, count, "Duration");
      ::delay(10);
      previous_val = val;
      cpt++;
    }
  }
References TAG4.
Referenced by setup().
test_stop_broker()
void fabomatic::tests::test_stop_broker ()
Definition at line 127 of file test_mqtt.cpp.
  {
    exit_request = true;
    pthread_join(thread_mqtt_broker, NULL);
  }
References exit_request, and thread_mqtt_broker.
Referenced by setup().
test_stop_start_tasks()
void fabomatic::tests::test_stop_start_tasks (void)
Definition at line 101 of file test_tasks.cpp.
  {
    create_tasks(scheduler, 150ms);
    TEST_ASSERT_EQUAL_MESSAGE(NB_TASKS, scheduler.taskCount(), "Scheduler does not contain all tasks");
    for (auto &t : tasks)
    {
      t->disable();
    }
    task_counter = 0;
    run_for_duration(execute, 150ms);
    TEST_ASSERT_EQUAL_MESSAGE(0, task_counter, "Stopped tasks has been executed");
    for (auto &t : tasks)
    {
      t->enable();
    }
    task_counter = 0;
    run_for_duration(execute, 150ms);
    TEST_ASSERT_EQUAL_MESSAGE(NB_TASKS, task_counter, "Started tasks have not all been executed");
    task_counter = 0;
    for (auto &t : tasks)
    {
      t->updateSchedule();
    }
    execute();
    TEST_ASSERT_EQUAL_MESSAGE(NB_TASKS, task_counter, "Restarted tasks did not run immediately");
  }
References create_tasks(), execute, NB_TASKS, run_for_duration(), scheduler, task_counter, fabomatic::Tasks::Scheduler::taskCount(), and tasks.
Referenced by setup().
test_taskCheckRfid()
void fabomatic::tests::test_taskCheckRfid ()
periodic check for new RFID card
Definition at line 245 of file test_mqtt.cpp.
  {
    logic.checkRfid();
  }
References fabomatic::BoardLogic::checkRfid(), and logic.
test_taskConnect()
void fabomatic::tests::test_taskConnect ()
Opens WiFi and server connection and updates board state accordingly.
Definition at line 222 of file test_mqtt.cpp.
  {
    auto &server = logic.getServer();
    if (!server.isOnline())
    {
      // connection to wifi
      logic.changeStatus(BoardLogic::Status::Connecting);
      // Try to connect
      server.connect();
      // Refresh after connection
      logic.changeStatus(server.isOnline() ? BoardLogic::Status::Connected : BoardLogic::Status::Offline);
    }
    if (server.isOnline())
    {
      ESP_LOGI(TAG3, "taskConnect - online, calling refreshFromServer");
      // Get machine data from the server if it is online
      logic.refreshFromServer();
    }
  }
References fabomatic::BoardLogic::changeStatus(), fabomatic::FabBackend::connect(), fabomatic::BoardLogic::Connected, fabomatic::BoardLogic::Connecting, fabomatic::BoardLogic::getServer(), fabomatic::FabBackend::isOnline(), logic, fabomatic::BoardLogic::Offline, fabomatic::BoardLogic::refreshFromServer(), and TAG3.
test_taskEspWatchdog()
void fabomatic::tests::test_taskEspWatchdog ()
Keep the ESP32 HW watchdog alive. If code gets stuck this will cause an automatic reset.
Definition at line 274 of file test_mqtt.cpp.
  {
    static auto initialized = false;
    if (conf::tasks::WATCHDOG_TIMEOUT > 0s)
    {
      if (!initialized)
      {
        initialized = esp32::setupWatchdog(conf::tasks::WATCHDOG_TIMEOUT);
        TEST_ASSERT_TRUE_MESSAGE(initialized, "Watchdog initialization works");
      }
      if (initialized)
      {
        TEST_ASSERT_TRUE_MESSAGE(esp32::signalWatchdog(), "Watchdog signalling failed");
      }
    }
  }
References fabomatic::esp32::setupWatchdog(), fabomatic::esp32::signalWatchdog(), and fabomatic::conf::tasks::WATCHDOG_TIMEOUT.
test_taskMQTTAlive()
void fabomatic::tests::test_taskMQTTAlive ()
sends the MQTT alive message
Definition at line 308 of file test_mqtt.cpp.
  {
    auto &server = logic.getServer();
    if (server.isOnline())
    {
      TEST_ASSERT_TRUE_MESSAGE(server.loop(), "test_taskMQTTAlive: Server loop failed");
    }
  }
References fabomatic::BoardLogic::getServer(), fabomatic::FabBackend::isOnline(), logic, and fabomatic::FabBackend::loop().
test_taskRfidWatchdog()
void fabomatic::tests::test_taskRfidWatchdog ()
checks the RFID chip status and re-init it if necessary.
Definition at line 293 of file test_mqtt.cpp.
  {
    auto result = rfid.selfTest();
    TEST_ASSERT_TRUE_MESSAGE(result, "test_taskRfidWatchdog: RFID chip failure");
    if (!result)
    {
      ESP_LOGE(TAG3, "RFID chip failure");
      // Infinite retry until success or hw watchdog timeout
      while (!rfid.rfidInit())
        TEST_FAIL_MESSAGE("Init RFID chip failed");
    }
  }
References rfid, and TAG3.
test_taskVarious()
void fabomatic::tests::test_taskVarious ()
blink led
Definition at line 251 of file test_mqtt.cpp.
  {
    logic.blinkLed();
    logic.checkPowerOff();
    if (logic.getMachine().isShutdownImminent())
    {
      logic.beepFail();
      ESP_LOGI(TAG3, "Machine is about to shutdown");
    }
    // auto logout after delay
    auto &machine = logic.getMachine();
    if (machine.isAutologoffExpired())
    {
      ESP_LOGI(TAG3, "Auto-logging out user %s\r\n", machine.getActiveUser().holder_name.data());
      logic.logout();
      logic.beepFail();
    }
  }
References fabomatic::BoardLogic::beepFail(), fabomatic::BoardLogic::blinkLed(), fabomatic::BoardLogic::checkPowerOff(), fabomatic::BoardLogic::getMachine(), logic, fabomatic::BoardLogic::logout(), and TAG3.
test_user_autologoff()
void fabomatic::tests::test_user_autologoff ()
Definition at line 209 of file test_logic.cpp.
  {
    machine_init(logic, rfid);
    auto &machine = logic.getMachineForTesting();
    machine.setGracePeriod(5s);
    TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().getAutologoffDelay() == conf::machine::DEFAULT_AUTO_LOGOFF_DELAY, "Autologoff delay not default");
    logic.setAutologoffDelay(10s);
    TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().getAutologoffDelay() == 10s, "Autologoff delay not 10s");
    simulate_rfid_card(rfid, logic, get_test_uid(0));
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::LoggedIn, logic.getStatus(), "Status not LoggedIn");
    TEST_ASSERT_TRUE_MESSAGE(machine.getPowerState() == Machine::PowerState::PoweredOn, "Machine is powered on");
    // Card away
    simulate_rfid_card(rfid, logic, std::nullopt);
    TEST_ASSERT_FALSE_MESSAGE(logic.getMachine().isFree(), "Machine is free");
    TEST_ASSERT_FALSE_MESSAGE(logic.getMachine().isAutologoffExpired(), "Autologoff not expired");
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::MachineInUse, logic.getStatus(), "Status not MachineInUse");
    // Now shall expire afer 10s
    simulate_rfid_card(rfid, logic, std::nullopt, 10s);
    TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().isAutologoffExpired(), "Autologoff expired");
    logic.logout();
    simulate_rfid_card(rfid, logic, std::nullopt, 5s);
    TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().isFree(), "Machine is free");
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::MachineFree, logic.getStatus(), "Status not MachineFree");
    TEST_ASSERT_TRUE_MESSAGE(machine.canPowerOff(), "Machine should be powered off");
    machine.power(false);
    TEST_ASSERT_EQUAL_UINT8_MESSAGE(Machine::PowerState::PoweredOff, machine.getPowerState(), "(2) Machine is powered off");
    // Check Grace period
    simulate_rfid_card(rfid, logic, get_test_uid(0), 1s); // Login
    TEST_ASSERT_EQUAL_UINT8_MESSAGE(Machine::PowerState::PoweredOn, machine.getPowerState(), "(2) Machine is ON");
    simulate_rfid_card(rfid, logic, get_test_uid(0), 1s); // Logout
    TEST_ASSERT_EQUAL_UINT8_MESSAGE(Machine::PowerState::WaitingPowerOff, machine.getPowerState(), "(2) Machine is waiting for power off");
    TEST_ASSERT_TRUE_MESSAGE(machine.isShutdownImminent(), "Machine in grace period");
    TEST_ASSERT_FALSE_MESSAGE(machine.canPowerOff(), "Machine cannot be powered off yet");
    simulate_rfid_card(rfid, logic, std::nullopt, 5s); // Let grace period expire
    TEST_ASSERT_FALSE_MESSAGE(machine.isShutdownImminent(), "Machine is still in grace period");
    TEST_ASSERT_TRUE_MESSAGE(machine.canPowerOff(), "Machine can now be powered off");
    machine.power(false);
    TEST_ASSERT_EQUAL_UINT8_MESSAGE(Machine::PowerState::PoweredOff, machine.getPowerState(), "Machine is powered off");
    auto save_result = logic.getServer().saveBuffer();
    TEST_ASSERT_TRUE_MESSAGE(save_result, "Saving buffered messages works");
  }
References fabomatic::conf::machine::DEFAULT_AUTO_LOGOFF_DELAY, get_test_uid(), fabomatic::BoardLogic::getMachine(), fabomatic::BoardLogic::getMachineForTesting(), fabomatic::BoardLogic::getServer(), fabomatic::BoardLogic::getStatus(), fabomatic::BoardLogic::LoggedIn, logic, fabomatic::BoardLogic::logout(), machine_init(), fabomatic::BoardLogic::MachineFree, fabomatic::BoardLogic::MachineInUse, fabomatic::Machine::PoweredOff, fabomatic::Machine::PoweredOn, rfid, fabomatic::BoardLogic::setAutologoffDelay(), simulate_rfid_card(), and fabomatic::Machine::WaitingPowerOff.
Referenced by setup().
test_whitelist_no_network()
void fabomatic::tests::test_whitelist_no_network ()
Definition at line 117 of file test_logic.cpp.
  {
    machine_init(logic, rfid);
    // Check whitelist is recognized
    for (auto &wle : test_whitelist)
    {
      const auto [card_uid, level, name] = wle;
      TEST_ASSERT_TRUE_MESSAGE(logic.authorize(card_uid), "Card not authorized");
      TEST_ASSERT_TRUE_MESSAGE(logic.getStatus() == BoardLogic::Status::LoggedIn, "Status not LoggedIn");
      TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().getActiveUser().card_uid == card_uid, "User UID not equal");
      // Name may not be equal because of cache RFID feature which does not save strings
      // TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().getActiveUser().holder_name == name, "User name not equal");
      TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().getActiveUser().user_level == level, "User level not equal");
      logic.logout();
      TEST_ASSERT_TRUE_MESSAGE(logic.getStatus() == BoardLogic::Status::LoggedOut, "Status not LoggedOut");
    }
    // Check that machine is free
    logic.checkRfid();
    TEST_ASSERT_TRUE_MESSAGE(logic.getStatus() == BoardLogic::Status::MachineFree, "Status not MachineFree");
    TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().isFree(), "Machine not free");
    // Logon simulating RFID tag
    const auto card_uid = get_test_uid(1);
    simulate_rfid_card(rfid, logic, card_uid, std::nullopt);
    TEST_ASSERT_TRUE_MESSAGE(rfid.isNewCardPresent(), "New card not present");
    TEST_ASSERT_TRUE_MESSAGE(rfid.readCardSerial().has_value(), "Card serial not read");
    TEST_ASSERT_TRUE_MESSAGE(rfid.readCardSerial().value() == card_uid, "Card serial not equal");
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::LoggedIn, logic.getStatus(), "Status not LoggedIn");
    // Card away, machine shall be busy
    auto new_state = simulate_rfid_card(rfid, logic, std::nullopt);
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::MachineInUse, new_state, "Status not MachineInUse");
    TEST_ASSERT_FALSE_MESSAGE(logic.getMachine().isFree(), "Machine is free");
    // Same card back, shall logout user
    new_state = simulate_rfid_card(rfid, logic, card_uid);
    TEST_ASSERT_EQUAL_UINT16_MESSAGE(BoardLogic::Status::LoggedOut, new_state, "Status not LoggedOut");
    TEST_ASSERT_TRUE_MESSAGE(logic.getMachine().isFree(), "Machine is not free");
    auto save_result = logic.getServer().saveBuffer();
    TEST_ASSERT_TRUE_MESSAGE(save_result, "Saving buffered messages works");
  }
References fabomatic::BoardLogic::authorize(), fabomatic::BoardLogic::checkRfid(), get_test_uid(), fabomatic::BoardLogic::getMachine(), fabomatic::BoardLogic::getServer(), fabomatic::BoardLogic::getStatus(), fabomatic::BoardLogic::LoggedIn, fabomatic::BoardLogic::LoggedOut, logic, fabomatic::BoardLogic::logout(), machine_init(), fabomatic::BoardLogic::MachineFree, fabomatic::BoardLogic::MachineInUse, rfid, simulate_rfid_card(), and test_whitelist.
Referenced by setup().
threadMQTTServer()
void * fabomatic::tests::threadMQTTServer (void * arg)
Definition at line 39 of file test_mqtt.cpp.
  {
    while (!exit_request)
    {
      broker.mainLoop();
      delay(15);
    }
    ESP_LOGI(TAG3, "MQTT server thread exiting");
    return arg;
  }
References broker, exit_request, fabomatic::MockMQTTBroker::mainLoop(), and TAG3.
Referenced by test_start_broker().
Variable Documentation
broker
fabomatic::MockMQTTBroker fabomatic::tests::broker
Definition at line 34 of file test_mqtt.cpp.
Referenced by test_start_broker(), and threadMQTTServer().
execute
const auto fabomatic::tests::execute
Initial value:
= []()
  { scheduler.execute(); }
Definition at line 25 of file test_tasks.cpp.
  { scheduler.execute(); };
Referenced by test_execute_runs_all_tasks(), and test_stop_start_tasks().
exit_request
std::atomic<bool> fabomatic::tests::exit_request {false}
Definition at line 37 of file test_mqtt.cpp.
{false};
Referenced by test_start_broker(), test_stop_broker(), and threadMQTTServer().
lcd
fabomatic::LCDWrapper fabomatic::tests::lcd {fabomatic::pins.lcd}
Definition at line 32 of file test_mqtt.cpp.
{fabomatic::pins.lcd};
Referenced by setUp().
logic
fabomatic::BoardLogic fabomatic::tests::logic
Definition at line 33 of file test_mqtt.cpp.
Referenced by machine_init(), setUp(), simulate_rfid_card(), test_check_transmission(), test_create_buffered_messages(), test_fabserver_calls(), test_machine_allowed(), test_machine_defaults(), test_machine_maintenance(), test_messages_buffered(), test_one_user_at_a_time(), test_simple_methods(), test_start_broker(), test_taskCheckRfid(), test_taskConnect(), test_taskMQTTAlive(), test_taskVarious(), test_user_autologoff(), and test_whitelist_no_network().
NB_TASKS
constexpr int fabomatic::tests::NB_TASKS = 100 constexpr
Definition at line 20 of file test_tasks.cpp.
Referenced by create_tasks(), test_execute_runs_all_tasks(), and test_stop_start_tasks().
original
SavedConfig fabomatic::tests::original
Definition at line 20 of file test_savedconfig.cpp.
Referenced by test_changes().
rfid
fabomatic::RFIDWrapper<fabomatic::MockMrfc522> fabomatic::tests::rfid
Definition at line 31 of file test_mqtt.cpp.
Referenced by machine_init(), setUp(), simulate_rfid_card(), test_machine_allowed(), test_machine_maintenance(), test_messages_buffered(), test_one_user_at_a_time(), test_taskRfidWatchdog(), test_user_autologoff(), and test_whitelist_no_network().
scheduler
Scheduler fabomatic::tests::scheduler
Definition at line 24 of file test_tasks.cpp.
Referenced by create_tasks(), delete_tasks(), test_execute_runs_all_tasks(), and test_stop_start_tasks().
t1
auto fabomatic::tests::t1 = Tasks::Task("taskConnect", 15s, &test_taskConnect, test_scheduler)
Definition at line 317 of file test_mqtt.cpp.
t2
auto fabomatic::tests::t2 = Tasks::Task("taskCheckRfid", 50ms, &test_taskCheckRfid, test_scheduler)
Definition at line 318 of file test_mqtt.cpp.
t3
auto fabomatic::tests::t3 = Tasks::Task("taskVarious", 1s, &test_taskVarious, test_scheduler)
Definition at line 319 of file test_mqtt.cpp.
t4
auto fabomatic::tests::t4 = Tasks::Task("taskEspWatchdog", 5s, &test_taskEspWatchdog, test_scheduler)
Definition at line 320 of file test_mqtt.cpp.
t5
auto fabomatic::tests::t5 = Tasks::Task("taskRfidWatchdog", 30s, &test_taskRfidWatchdog, test_scheduler)
Definition at line 321 of file test_mqtt.cpp.
t6
auto fabomatic::tests::t6 = Tasks::Task("taskMQTTAlive", 30s, &test_taskMQTTAlive, test_scheduler)
Definition at line 322 of file test_mqtt.cpp.
task_counter
size_t fabomatic::tests::task_counter {0}
Definition at line 23 of file test_tasks.cpp.
{0};
Referenced by create_tasks(), test_execute_runs_all_tasks(), and test_stop_start_tasks().
tasks
Task* fabomatic::tests::tasks[NB_TASKS] {nullptr}
Definition at line 22 of file test_tasks.cpp.
{nullptr};
Referenced by create_tasks(), delete_tasks(), and test_stop_start_tasks().
tasks_status
bool fabomatic::tests::tasks_status[NB_TASKS] {false}
Definition at line 21 of file test_tasks.cpp.
{false};
Referenced by create_tasks().
test_scheduler
fabomatic::Tasks::Scheduler fabomatic::tests::test_scheduler
Definition at line 35 of file test_mqtt.cpp.
Referenced by test_normal_use().
test_whitelist
constexpr WhiteList fabomatic::tests::test_whitelist static constexpr
Initial value:
{
          std::make_tuple(0xAABBCCD1, FabUser::UserLevel::FabAdmin, "ABCDEFG"),
          std::make_tuple(0xAABBCCD2, FabUser::UserLevel::FabStaff, "PIPPO"),
          std::make_tuple(0xAABBCCD3, FabUser::UserLevel::NormalUser, "USER1"),
          std::make_tuple(0xAABBCCD4, FabUser::UserLevel::NormalUser, "USER2"),
          std::make_tuple(0xAABBCCD5, FabUser::UserLevel::NormalUser, "USER3"),
          std::make_tuple(0xAABBCCD7, FabUser::UserLevel::NormalUser, "USER4"),
          std::make_tuple(0xAABBCCD8, FabUser::UserLevel::NormalUser, "USER5"),
          std::make_tuple(0xAABBCCD9, FabUser::UserLevel::NormalUser, "USER6"),
          std::make_tuple(0xAABBCCD0, FabUser::UserLevel::NormalUser, "USER7"),
          std::make_tuple(0xAABBCCDA, FabUser::UserLevel::NormalUser, "USER8"),
      }
Definition at line 14 of file test_common.h.
      {
          std::make_tuple(0xAABBCCD1, FabUser::UserLevel::FabAdmin, "ABCDEFG"),
          std::make_tuple(0xAABBCCD2, FabUser::UserLevel::FabStaff, "PIPPO"),
          std::make_tuple(0xAABBCCD3, FabUser::UserLevel::NormalUser, "USER1"),
          std::make_tuple(0xAABBCCD4, FabUser::UserLevel::NormalUser, "USER2"),
          std::make_tuple(0xAABBCCD5, FabUser::UserLevel::NormalUser, "USER3"),
          std::make_tuple(0xAABBCCD7, FabUser::UserLevel::NormalUser, "USER4"),
          std::make_tuple(0xAABBCCD8, FabUser::UserLevel::NormalUser, "USER5"),
          std::make_tuple(0xAABBCCD9, FabUser::UserLevel::NormalUser, "USER6"),
          std::make_tuple(0xAABBCCD0, FabUser::UserLevel::NormalUser, "USER7"),
          std::make_tuple(0xAABBCCDA, FabUser::UserLevel::NormalUser, "USER8"),
      };
Referenced by get_test_uid(), setUp(), and test_whitelist_no_network().