Fab-O-Matic: fabomatic::esp32 Namespace Reference
fabomatic::esp32 Namespace Reference
Functions
void showHeapStats ()
auto setupWatchdog (std::chrono::milliseconds msecs) -> bool
auto signalWatchdog () -> bool
auto removeWatchdog () -> void
auto esp_serial () -> const std::string_view
Returns the ESP32 serial number as a string.
auto getFreeHeap () -> uint32_t
auto restart () -> void
Function Documentation
esp_serial()
auto fabomatic::esp32::esp_serial () -> const std::string_view
Returns the ESP32 serial number as a string.
Definition at line 67 of file Espressif.cpp.
  {
    static std::array<char, 13> result; // +1 for null termination
    if (result[0] == '\0') // Compute only once
    {
      std::stringstream serial{};
      std::array<uint8_t, 8> mac{0};
      esp_efuse_mac_get_default(mac.data());
      for (const auto val : mac)
      {
        serial << std::setfill('0') << std::setw(2) << std::hex << +val;
      }
      auto res = serial.str().substr(0U, 6 * 2);
      std::copy(res.cbegin(), res.cend(), result.begin());
      result[result.size() - 1] = '\0';
    }
    return {result.data()};
  }
Referenced by fabomatic::ServerMQTT::AliveQuery::payload(), fabomatic::taskFactoryReset(), and fabomatic::tests::test_esp32().
getFreeHeap()
auto fabomatic::esp32::getFreeHeap () -> uint32_t
Definition at line 88 of file Espressif.cpp.
  {
    return esp_get_free_heap_size();
  }
Referenced by fabomatic::ServerMQTT::AliveQuery::payload(), and fabomatic::tests::test_esp32().
removeWatchdog()
auto fabomatic::esp32::removeWatchdog () -> void
Definition at line 61 of file Espressif.cpp.
  {
    esp_task_wdt_deinit();
  }
Referenced by setupWatchdog(), fabomatic::taskFactoryReset(), fabomatic::tests::test_esp32(), and fabomatic::tests::test_normal_use().
restart()
auto fabomatic::esp32::restart () -> void
Definition at line 93 of file Espressif.cpp.
  {
    esp_restart();
  }
Referenced by fabomatic::taskPoweroffWarning().
setupWatchdog()
auto fabomatic::esp32::setupWatchdog (std::chrono::milliseconds msecs) -> bool
Definition at line 32 of file Espressif.cpp.
  {
    removeWatchdog();
#if ESP_IDF_VERSION_MAJOR < 5
    auto secs = static_cast<uint32_t>(std::chrono::duration_cast<std::chrono::seconds>(msecs).count());
    auto retVal = esp_task_wdt_init(secs, true);
    ESP_LOGI(TAG, "taskEspWatchdog - initialized %u seconds", secs);
#else
    auto ui_msecs = static_cast<uint32_t>(msecs.count());
    esp_task_wdt_config_t conf{.timeout_ms = ui_msecs, .idle_core_mask = 1, .trigger_panic = true};
    auto retVal = esp_task_wdt_init(&conf);
    ESP_LOGI(TAG, "taskEspWatchdog - initialized %lu milliseconds", ui_msecs);
#endif
    if (retVal != ESP_OK)
    {
      return false;
    }
    retVal = esp_task_wdt_add(NULL); // add current thread to WDT watch
    return (retVal == ESP_OK);
  }
References removeWatchdog(), and TAG.
Referenced by setup(), fabomatic::taskEspWatchdog(), fabomatic::tests::test_esp32(), and fabomatic::tests::test_taskEspWatchdog().
showHeapStats()
auto fabomatic::esp32::showHeapStats ()
Definition at line 15 of file Espressif.cpp.
  {
    heap_caps_print_heap_info(MALLOC_CAP_8BIT);
    // Get heap summary
    multi_heap_info_t heap_info;
    heap_caps_get_info(&heap_info, MALLOC_CAP_8BIT);
    // Log heap statistics
    ESP_LOGI("Heap Stats", "Total Free Heap Size: %zu bytes", heap_info.total_free_bytes);
    ESP_LOGI("Heap Stats", "Total Allocated Size: %zu bytes", heap_info.total_allocated_bytes);
    ESP_LOGI("Heap Stats", "Largest Free Block: %zu bytes", heap_info.largest_free_block);
    ESP_LOGI("Heap Stats", "Min Free Heap Size Ever: %zu bytes", heap_info.minimum_free_bytes);
    ESP_LOGI("Heap Stats", "Free Blocks: %zu", heap_info.free_blocks);
    ESP_LOGI("Heap Stats", "Allocated Blocks: %zu", heap_info.allocated_blocks);
  }
Referenced by fabomatic::taskIsAlive(), and fabomatic::tests::test_esp32().
signalWatchdog()
auto fabomatic::esp32::signalWatchdog () -> bool
Definition at line 56 of file Espressif.cpp.
  {
    return esp_task_wdt_reset() == ESP_OK;
  }
Referenced by fabomatic::taskEspWatchdog(), and fabomatic::tests::test_taskEspWatchdog().