Fab-O-Matic: fabomatic::card Namespace Reference
fabomatic::card Namespace Reference
Typedefs
using uid_t = u_int64_t
Functions
auto uid_str (const card::uid_t uid) -> const std::string
Returns a string representation of the UID.
constexpr auto from_array (const std::array< uint8_t, conf::rfid_tags::UID_BYTE_LEN > &uid) -> uid_t
Converts a UID from an array of bytes to a number.
constexpr auto to_array (const uid_t uid) -> const std::array< uint8_t, conf::rfid_tags::UID_BYTE_LEN >
Converts a UID from an array of bytes to a number.
auto print (uint64_t uid) -> void
Variables
static constexpr uid_t INVALID = 0ULL
Typedef Documentation
uid_t
using fabomatic::card::uid_t = typedef u_int64_t
Definition at line 15 of file card.hpp.
Function Documentation
from_array()
constexpr auto fabomatic::card::from_array (const std::array< uint8_t, conf::rfid_tags::UID_BYTE_LEN > & uid) -> uid_t inline constexpr
Converts a UID from an array of bytes to a number.
Parameters
uid array of bytes
Returns
the UID as a number
Definition at line 40 of file card.hpp.
  {
    card::uid_t result = 0;
    for (auto i = (conf::rfid_tags::UID_BYTE_LEN - 1); i >= 0; i--)
    {
      result <<= 8;
      result |= uid[i];
    }
    return result;
  }
References fabomatic::conf::rfid_tags::UID_BYTE_LEN.
print()
auto fabomatic::card::print (uint64_t uid) -> void inline
Definition at line 64 of file card.hpp.
  {
    ESP_LOGI(TAG, "Card UID = %s", card::uid_str(uid).c_str());
  }
References TAG, and uid_str().
to_array()
constexpr auto fabomatic::card::to_array (const uid_t uid) -> const std::array<uint8_t, conf::rfid_tags::UID_BYTE_LEN> inline constexpr
Converts a UID from an array of bytes to a number.
Parameters
uid array of bytes
Returns
the UID as a number
Definition at line 54 of file card.hpp.
  {
    std::array<uint8_t, conf::rfid_tags::UID_BYTE_LEN> retVal{0};
    for (auto i = (conf::rfid_tags::UID_BYTE_LEN - 1); i >= 0; i--)
    {
      retVal[i] = (uid >> (i * 8)) & 0xFF;
    }
    return retVal;
  }
References fabomatic::conf::rfid_tags::UID_BYTE_LEN.
Referenced by fabomatic::MockMrfc522::getDriverUid().
uid_str()
auto fabomatic::card::uid_str (const card::uid_t uid) -> const std::string inline
Returns a string representation of the UID.
Parameters
uid number to convert
Returns
an hex string representation of the UID (e.g. "123456ADCD")
Definition at line 23 of file card.hpp.
  {
    uint64_t number = static_cast<uint64_t>(uid);
    uint32_t long1 = static_cast<uint32_t>(number & 0xFFFF0000) >> 16;
    uint32_t long2 = static_cast<uint32_t>(number & 0x0000FFFF);
    std::stringstream ss{};
    ss << std::setfill('0') << std::setw(4) << std::hex << long1;
    ss << std::setfill('0') << std::setw(4) << std::hex << long2;
    return ss.str();
  }
Referenced by fabomatic::BoardLogic::authorize(), fabomatic::MockMQTTBroker::defaultReplies(), fabomatic::BoardLogic::onNewCard(), fabomatic::MQTTInterface::UserQuery::payload(), fabomatic::MQTTInterface::StartUseQuery::payload(), fabomatic::MQTTInterface::StopUseQuery::payload(), fabomatic::MQTTInterface::InUseQuery::payload(), fabomatic::MQTTInterface::RegisterMaintenanceQuery::payload(), print(), fabomatic::AuthProvider::tryLogin(), fabomatic::AuthProvider::uidInWhitelist(), and fabomatic::BoardLogic::updateLCD().
Variable Documentation
INVALID
constexpr uid_t fabomatic::card::INVALID = 0ULL static constexpr
Definition at line 16 of file card.hpp.
Referenced by fabomatic::CachedCards::find_uid(), fabomatic::SavedConfig::fromJsonDocument(), and fabomatic::AuthProvider::uidInWhitelist().