Fab-O-Matic: fabomatic Namespace Reference
fabomatic Namespace Reference
Namespaces
namespace Board
namespace card
namespace conf
namespace esp32
Contains all espressif32 features not masked by Arduino IDE.
namespace MQTT
Contains all the types for MQTT messages between board and backend.
namespace secrets
namespace strings
namespace Tasks
This namespace contains the classes that implement a cooperative task scheduler.
namespace tests
Classes
class AuthProvider
This class manages authentication of a RFID tag through cache, whitelist or network request.
class BaseRFIDWrapper
Base class for the real and mock implementation of RFID tag reader chip.
struct BoardInfo
Helper struct representing the display state.
class BoardLogic
Main class implementing the state changes.
class Buffer
Class containing the buffered messages for future replay.
struct BufferedMsg
Message that can be saved in Flash for future replay.
class BufferedQuery
Query to be replayed.
class Buzzer
Represents the buzzer for BoardLogic.
struct CachedCard
A Cached card contains only RFID tag ID + access level. Name is intentionally not saved.
struct CachedCards
This struct contains CACHE_LEN RFID tags with their authentication by the backend.
class FabBackend
This class is used to exchange messages with the MQTT broker and the backend.
struct FabUser
Represents a user with access level, name, RFID tag, and auth result.
class LCDWrapper
LCD display wrapper.
class Led
RGB/LED/NeoPixel class.
class Machine
Represents the FabLab machine connected to the board.
struct MachineConfig
Represents the configuration settings for the machine.
class MockMQTTBroker
This class implements an MQTT broker with predefined responses to FabBackend requests.
class MockMrfc522
This class implements a Mrfc522 with settable tag ID in order to allow simulation.
class Mrfc522Driver
The real Mrfc522Driver around the Arduino library.
struct pins_config
class RFIDWrapper
Driver class for the RFID reader chip.
class SavedConfig
Facility to load or save data from Flash.
Typedefs
using milliseconds = std::chrono::milliseconds
using Scheduler = Tasks::Scheduler
using Task = Tasks::Task
using Status = BoardLogic::Status
using WhiteListEntry = std::tuple< card::uid_t, FabUser::UserLevel, std::string_view >
using WhiteList = std::array< WhiteListEntry, conf::cards::LEN >
Functions
void taskConnect ()
Opens WiFi and server connection and updates board state accordingly.
void taskCheckRfid ()
periodic check for new RFID card
void taskBlink ()
blink led
void taskPoweroffCheck ()
periodic check if the machine must be powered off
void taskPoweroffWarning ()
periodic check if the machine must be powered off
void taskLogoffCheck ()
periodic check if the user shall be logged off
void taskEspWatchdog ()
Keep the ESP32 HW watchdog alive. If code gets stuck this will cause an automatic reset.
void taskRfidWatchdog ()
checks the RFID chip status and re-init it if necessary.
void taskMQTTClientLoop ()
sends the MQTT alive message
void taskIsAlive ()
void taskFactoryReset ()
void printCompileSettings ()
void saveConfigCallback ()
void configModeCallback (WiFiManager *myWiFiManager)
auto getConfig (bool force_reset) -> SavedConfig
void openConfigPortal (bool force_reset, bool disable_portal) -> void
Open the ArduinoOTA configuration portal.
void OTAComplete ()
void setupOTA () -> void
Initialization of the Arduino OTA library with settings for fabomatic.
constexpr auto configure_pins_esp32 () -> const pins_config
Returns configuration for an ESP32 dev board used in HW revision 0.1.
constexpr auto configure_pins_wokwi () -> const pins_config
Returns configuration for Wokwi ESP32S2 environment.
constexpr auto configure_pins_esp32s3 () -> const pins_config
Returns configuration for esp32s3 dev kit board.
constexpr auto configure_pins_hwrev0 () -> const pins_config
Returns configuration for PCB hardware in this repository.
constexpr auto configure_pins_wrover () -> const pins_config
Configuration for ESP32 Wrover Kit 4.1 (https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-wrover-kit.html)
constexpr auto configure_pins () -> const pins_config
Returns the actual pins configuration to be used depending on preprocessor constants.
constexpr bool no_duplicates (pins_config pins)
Check at compile time that there are no duplicate pin definitions.
Variables
const Task t_rfid ("RFIDChip", conf::tasks::RFID_CHECK_PERIOD, &taskCheckRfid, Board::scheduler, true)
const Task t_network ("Wifi/MQTT", conf::tasks::MQTT_REFRESH_PERIOD, &taskConnect, Board::scheduler, true, conf::tasks::MQTT_REFRESH_PERIOD)
const Task t_powoff ("Poweroff", 1s, &taskPoweroffCheck, Board::scheduler, true)
const Task t_log ("Logoff", 1s, &taskLogoffCheck, Board::scheduler, true)
Task t_wdg ("Watchdog", conf::tasks::WATCHDOG_PERIOD, &taskEspWatchdog, Board::scheduler, false)
const Task t_test ("Selftest", conf::tasks::RFID_SELFTEST_PERIOD, &taskRfidWatchdog, Board::scheduler, true)
const Task t_warn ("PoweroffWarning", conf::machine::DELAY_BETWEEN_BEEPS, &taskPoweroffWarning, Board::scheduler, true)
const Task t_mqtt ("MQTT client loop", 1s, &taskMQTTClientLoop, Board::scheduler, true)
const Task t_led ("LED", 1s, &taskBlink, Board::scheduler, true)
const Task t_rst ("FactoryReset", 500ms, &taskFactoryReset, Board::scheduler, pins.buttons.factory_defaults_pin !=NO_PIN)
const Task t_alive ("IsAlive", conf::tasks::MQTT_ALIVE_PERIOD, &taskIsAlive, Board::scheduler, true, conf::tasks::MQTT_ALIVE_PERIOD)
std::atomic< bool > shouldSaveConfig {false}
static constexpr pins_config pins = configure_pins()
static constexpr uint8_t NO_PIN = -1
Constant used to indicate the pin is not used.
Typedef Documentation
milliseconds
typedef std::chrono::milliseconds fabomatic::milliseconds
Definition at line 26 of file BoardLogic.cpp.
Scheduler
using fabomatic::Scheduler = typedef Tasks::Scheduler
Definition at line 25 of file main.cpp.
Status
typedef BoardLogic::Status fabomatic::Status
Definition at line 27 of file main.cpp.
Task
using fabomatic::Task = typedef Tasks::Task
Definition at line 26 of file main.cpp.
WhiteList
using fabomatic::WhiteList = typedef std::array<WhiteListEntry, conf::cards::LEN>
Definition at line 20 of file WhiteList.hpp.
WhiteListEntry
using fabomatic::WhiteListEntry = typedef std::tuple<card::uid_t, FabUser::UserLevel, std::string_view>
Definition at line 19 of file WhiteList.hpp.
Function Documentation
configModeCallback()
void fabomatic::configModeCallback (WiFiManager * myWiFiManager)
Definition at line 25 of file OTA.cpp.
  {
    ESP_LOGI(TAG, "Entering portal config mode");
    ESP_LOGD(TAG, "%s", WiFi.softAPIP().toString().c_str());
    ESP_LOGD(TAG, "%s", myWiFiManager->getConfigPortalSSID().c_str());
    Board::logic.changeStatus(Status::PortalStarting);
  }
References fabomatic::BoardLogic::changeStatus(), fabomatic::Board::logic, and TAG.
Referenced by openConfigPortal().
configure_pins()
constexpr auto fabomatic::configure_pins () -> const pins_config constexpr
Returns the actual pins configuration to be used depending on preprocessor constants.
Returns
pins_config
Definition at line 227 of file pins.hpp.
  {
#ifdef PINS_ESP32
    return configure_pins_esp32();
#endif
#ifdef PINS_WOKWI
    return configure_pins_wokwi();
#endif
#ifdef PINS_ESP32S3
    return configure_pins_esp32s3();
#endif
#ifdef PINS_HARDWARE_REV0
    return configure_pins_hwrev0();
#endif
#ifdef PINS_ESP32_WROVERKIT
    return configure_pins_wrover();
#endif
  }
References configure_pins_esp32(), configure_pins_esp32s3(), configure_pins_hwrev0(), configure_pins_wokwi(), and configure_pins_wrover().
configure_pins_esp32()
constexpr auto fabomatic::configure_pins_esp32 () -> const pins_config constexpr
Returns configuration for an ESP32 dev board used in HW revision 0.1.
Returns
pins_config
Definition at line 12 of file pins.hpp.
  {
    return pins_config{
        {
            .sda_pin = 27U,
            .mosi_pin = 33U,
            .miso_pin = 32U,
            .sck_pin = 26U,
            .reset_pin = 20U,
        }, // RFID
        {
            .rs_pin = 15U,
            .en_pin = 2U,
            .d0_pin = 0U,
            .d1_pin = 4U,
            .d2_pin = 16U,
            .d3_pin = 17U,
            .bl_pin = 18U,
            .active_low = false,
        }, // LCD
        {
            .ch1_pin = 14U,
            .active_low = true,
        }, // relay
        {
            .pin = 12U,
        }, // buzzer
        {
            .pin = 19U,
            .is_neopixel = true,
            .neopixel_config = NEO_RGB + NEO_KHZ800,
            .is_rgb = false,
            .green_pin = NO_PIN,
            .blue_pin = NO_PIN,
        }, // LED config
        {
            .factory_defaults_pin = NO_PIN,
        } // Factory defaults button
    };
  }
References NO_PIN.
Referenced by configure_pins().
configure_pins_esp32s3()
constexpr auto fabomatic::configure_pins_esp32s3 () -> const pins_config constexpr
Returns configuration for esp32s3 dev kit board.
Returns
pins_config
Definition at line 98 of file pins.hpp.
  {
    return pins_config{
        {
            .sda_pin = 17U,
            .mosi_pin = 8U,
            .miso_pin = 3U,
            .sck_pin = 18U,
            .reset_pin = 12U,
        }, // RFID
        {
            .rs_pin = 5U,
            .en_pin = 4U,
            .d0_pin = 6U,
            .d1_pin = 7U,
            .d2_pin = 15U,
            .d3_pin = 2U,
            .bl_pin = 13U,
            .active_low = false,
        }, // LCD
        {
            .ch1_pin = 10U,
            .active_low = true,
        }, // relay
        {
            .pin = 9U,
        }, // buzzer
        {
            .pin = 48U,
            .is_neopixel = true,
            .neopixel_config = NEO_GRB + NEO_KHZ800,
            .is_rgb = false,
            .green_pin = NO_PIN,
            .blue_pin = NO_PIN,
        }, // LED config
        {
            .factory_defaults_pin = NO_PIN,
        } // Factory defaults button
    };
  }
References NO_PIN.
Referenced by configure_pins().
configure_pins_hwrev0()
constexpr auto fabomatic::configure_pins_hwrev0 () -> const pins_config constexpr
Returns configuration for PCB hardware in this repository.
Returns
pins_config
Definition at line 141 of file pins.hpp.
  {
    return pins_config{
        {
            .sda_pin = 39U,
            .mosi_pin = 37U,
            .miso_pin = 36U,
            .sck_pin = 38U,
            .reset_pin = 35U,
        }, // RFID
        {
            .rs_pin = 13U,
            .en_pin = 14U,
            .d0_pin = 21U,
            .d1_pin = 47U,
            .d2_pin = 48U,
            .d3_pin = 40U,
            .bl_pin = NO_PIN,
            .active_low = false,
        }, // LCD
        {
            .ch1_pin = 10U,
            .active_low = true,
        }, // relay
        {
            .pin = 15U,
        }, // buzzer
        {
            .pin = 18U,
            .is_neopixel = true,
            .neopixel_config = NEO_GRB + NEO_KHZ800,
            .is_rgb = false,
            .green_pin = NO_PIN,
            .blue_pin = NO_PIN,
        }, // LED config
        {
            .factory_defaults_pin = 8U,
        } // Factory defaults button
    };
  }
References NO_PIN.
Referenced by configure_pins().
configure_pins_wokwi()
constexpr auto fabomatic::configure_pins_wokwi () -> const pins_config constexpr
Returns configuration for Wokwi ESP32S2 environment.
Returns
pins_config
Definition at line 55 of file pins.hpp.
  {
    return pins_config{
        {
            .sda_pin = 27U,
            .mosi_pin = 26U,
            .miso_pin = 33U,
            .sck_pin = 32U,
            .reset_pin = 16U,
        }, // RFID
        {
            .rs_pin = 15U,
            .en_pin = 18U,
            .d0_pin = 2U,
            .d1_pin = 4U,
            .d2_pin = 5U,
            .d3_pin = 19U,
            .bl_pin = NO_PIN,
            .active_low = false,
        }, // LCD
        {
            .ch1_pin = 14U,
            .active_low = false,
        }, // relay
        {
            .pin = 12U,
        }, // buzzer
        {
            .pin = 20U,
            .is_neopixel = true,
            .neopixel_config = NEO_GRB + NEO_KHZ800,
            .is_rgb = false,
            .green_pin = NO_PIN,
            .blue_pin = NO_PIN,
        }, // LED config
        {
            .factory_defaults_pin = 21U,
        } // Factory defaults button
    };
  }
References NO_PIN.
Referenced by configure_pins().
configure_pins_wrover()
constexpr auto fabomatic::configure_pins_wrover () -> const pins_config constexpr
Configuration for ESP32 Wrover Kit 4.1 (https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-wrover-kit.html)
Returns
pins_config
Definition at line 184 of file pins.hpp.
  {
    return pins_config{
        {
            .sda_pin = 15U,
            .mosi_pin = 19U,
            .miso_pin = 16U,
            .sck_pin = 20U,
            .reset_pin = 18U,
        }, // RFID
        {
            .rs_pin = 12U,
            .en_pin = 14U,
            .d0_pin = 26U,
            .d1_pin = 21U,
            .d2_pin = 22U,
            .d3_pin = 23U,
            .bl_pin = NO_PIN,
            .active_low = false,
        }, // LCD
        {
            .ch1_pin = 5U,
            .active_low = false,
        }, // relay
        {
            .pin = 13U,
        }, // buzzer
        {
            .pin = 0U,
            .is_neopixel = false,
            .neopixel_config = 0,
            .is_rgb = true,
            .green_pin = 2U,
            .blue_pin = 4U,
        }, // LED configuration
        {
            .factory_defaults_pin = NO_PIN,
        } // Factory defaults button
    };
  }
References NO_PIN.
Referenced by configure_pins().
getConfig()
auto fabomatic::getConfig (bool force_reset) -> SavedConfig
Definition at line 33 of file OTA.cpp.
  {
    const auto &opt_settings = SavedConfig::LoadFromEEPROM();
    if (force_reset || !opt_settings)
    {
      return SavedConfig::DefaultConfig();
    }
    return opt_settings.value();
  }
References fabomatic::SavedConfig::DefaultConfig(), and fabomatic::SavedConfig::LoadFromEEPROM().
Referenced by openConfigPortal().
no_duplicates()
constexpr bool fabomatic::no_duplicates (pins_config pins) constexpr
Check at compile time that there are no duplicate pin definitions.
Definition at line 77 of file PinsConfig.hpp.
  {
    std::array pin_nums{
        pins.mfrc522.sda_pin,
        pins.mfrc522.mosi_pin,
        pins.mfrc522.miso_pin,
        pins.mfrc522.sck_pin,
        pins.mfrc522.reset_pin,
        pins.lcd.rs_pin,
        pins.lcd.en_pin,
        pins.lcd.d0_pin,
        pins.lcd.d1_pin,
        pins.lcd.d2_pin,
        pins.lcd.d3_pin,
        pins.lcd.bl_pin,
        pins.relay.ch1_pin,
        pins.buzzer.pin,
        pins.led.pin,
        pins.led.green_pin,
        pins.led.blue_pin,
        pins.buttons.factory_defaults_pin};
    // No constexpr std::sort available
    for (auto i = 0; i < pin_nums.size(); ++i)
    {
      if (pin_nums[i] == NO_PIN)
        continue;
      for (auto j = i + 1; j < pin_nums.size(); ++j)
      {
        if (pin_nums[i] == pin_nums[j])
          return false;
      }
      // Check pins numbers are convertible to gpio_num_t
      static_cast<gpio_num_t>(pin_nums[i]);
    }
    return true;
  }
References fabomatic::pins_config::lcd_config::bl_pin, fabomatic::pins_config::led_config::blue_pin, fabomatic::pins_config::buttons, fabomatic::pins_config::buzzer, fabomatic::pins_config::relay_config::ch1_pin, fabomatic::pins_config::lcd_config::d0_pin, fabomatic::pins_config::lcd_config::d1_pin, fabomatic::pins_config::lcd_config::d2_pin, fabomatic::pins_config::lcd_config::d3_pin, fabomatic::pins_config::lcd_config::en_pin, fabomatic::pins_config::buttons_config::factory_defaults_pin, fabomatic::pins_config::led_config::green_pin, fabomatic::pins_config::lcd, fabomatic::pins_config::led, fabomatic::pins_config::mfrc522, fabomatic::pins_config::mfrc522_config::miso_pin, fabomatic::pins_config::mfrc522_config::mosi_pin, NO_PIN, fabomatic::pins_config::buzzer_config::pin, fabomatic::pins_config::led_config::pin, pins, fabomatic::pins_config::relay, fabomatic::pins_config::mfrc522_config::reset_pin, fabomatic::pins_config::lcd_config::rs_pin, fabomatic::pins_config::mfrc522_config::sck_pin, and fabomatic::pins_config::mfrc522_config::sda_pin.
openConfigPortal()
auto fabomatic::openConfigPortal (bool force_reset, bool disable_portal)
Open the ArduinoOTA configuration portal.
Parameters
force_reset if true, the portal will be reset to factory defaults
disable_portal if true, the portal will be disabled (useful at boot-time)
force_reset true to discard saved settings and restore compile-time settings
disable_portal true to skip portal opening (used at boot time)
Definition at line 47 of file OTA.cpp.
  {
    WiFiManager wifiManager;
    auto config = getConfig(force_reset);
    // We are using config as a buffer for the WiFiManager parameters, make sure it can hold the content
    config.mqtt_server.resize(conf::common::STR_MAX_LENGTH);
    config.mqtt_switch_topic.resize(conf::common::STR_MAX_LENGTH);
    config.machine_id.resize(conf::common::INT_MAX_LENGTH);
    WiFiManagerParameter custom_mqtt_server("Broker", strings::PORTAL_MQTT_BROKER_PROMPT, config.mqtt_server.data(), conf::common::STR_MAX_LENGTH);
    WiFiManagerParameter custom_mqtt_topic("Topic", strings::PORTAL_SHELLY_MQTT_PROMPT, config.mqtt_switch_topic.data(), conf::common::STR_MAX_LENGTH);
    WiFiManagerParameter custom_machine_id("MachineID", strings::PORTAL_MACHINE_ID_PROMPT, config.machine_id.data(), conf::common::INT_MAX_LENGTH, "type='number' min='0' max='65535'");
    wifiManager.addParameter(&custom_mqtt_server);
    wifiManager.addParameter(&custom_mqtt_topic);
    wifiManager.addParameter(&custom_machine_id);
    wifiManager.setTimeout(std::chrono::duration_cast<std::chrono::seconds>(conf::tasks::PORTAL_CONFIG_TIMEOUT).count());
    wifiManager.setConnectRetries(3);  // 3 retries
    wifiManager.setConnectTimeout(10); // 10 seconds
    wifiManager.setCountry("IT");
    wifiManager.setTitle(strings::PORTAL_TITLE);
    wifiManager.setCaptivePortalEnable(true);
    wifiManager.setAPCallback(configModeCallback);
    wifiManager.setSaveConfigCallback(saveConfigCallback);
    if (force_reset)
    {
      wifiManager.resetSettings();
    }
#if (PINS_WOKWI)
    wifiManager.setDebugOutput(true);
    wifiManager.resetSettings();
    wifiManager.setTimeout(10); // fail fast for debugging
#endif
    auto must_skip = disable_portal || config.disablePortal;
    if (must_skip)
    {
      wifiManager.setTimeout(1);
    }
    if (wifiManager.autoConnect())
    {
      Board::logic.changeStatus(Status::PortalSuccess);
      delay(1000);
    }
    else
    {
      if (!must_skip)
      {
        Board::logic.changeStatus(Status::PortalFailed);
        delay(3000);
      }
    }
    if (shouldSaveConfig)
    {
      // save SSID data from WiFiManager
      config.ssid.assign(WiFi.SSID().c_str());
      config.password.assign(WiFi.psk().c_str());
      // read updated parameters
      config.mqtt_server.assign(custom_mqtt_server.getValue());
      config.mqtt_switch_topic.assign(custom_mqtt_topic.getValue());
      config.machine_id.assign(custom_machine_id.getValue());
      config.disablePortal = true;
      // save the custom parameters to EEPROM
      if (config.SaveToEEPROM())
      {
        ESP_LOGD(TAG, "Config saved to EEPROM");
      }
      else
      {
        ESP_LOGE(TAG, "Failed to save config to EEPROM");
      }
      // WiFi settings change may require full reboot
      Board::logic.setRebootRequest(true);
    }
  }
References fabomatic::BoardLogic::changeStatus(), configModeCallback(), getConfig(), fabomatic::conf::common::INT_MAX_LENGTH, fabomatic::Board::logic, fabomatic::conf::tasks::PORTAL_CONFIG_TIMEOUT, saveConfigCallback(), fabomatic::BoardLogic::setRebootRequest(), shouldSaveConfig, fabomatic::conf::common::STR_MAX_LENGTH, and TAG.
Referenced by setup(), and taskFactoryReset().
OTAComplete()
void fabomatic::OTAComplete ()
Definition at line 132 of file OTA.cpp.
  {
    ESP_LOGI(TAG, "OTA complete, reboot requested");
    Board::logic.setRebootRequest(true);
  }
References fabomatic::Board::logic, fabomatic::BoardLogic::setRebootRequest(), and TAG.
Referenced by setupOTA().
printCompileSettings()
void fabomatic::printCompileSettings ()
Definition at line 320 of file main.cpp.
  {
    using namespace conf;
    std::cout << "Compile-time settings (may be overriden)" << '\n';
    // namespace conf::default_config
    std::cout << "Machine defaults:" << '\n';
    std::cout << "\tmachine_id: " << default_config::machine_id.id << '\n';
    std::cout << "\tmachine_name: " << default_config::machine_name << '\n';
    std::cout << "\tmachine_type: " << static_cast<int>(default_config::machine_type) << '\n';
    std::cout << "\thostname: " << default_config::hostname << '\n';
    // simulation constants
    std::cout << "Compilation settings" << '\n';
    std::cout << "\tMQTT_SIMULATION: " << MQTT_SIMULATION << '\n';
    std::cout << "\tRFID_SIMULATION: " << RFID_SIMULATION << '\n';
    std::cout << "\tCORE_DEBUG_LEVEL: " << CORE_DEBUG_LEVEL << '\n';
    std::cout << "\tLANGUAGE: " << fabomatic::strings::S_LANG_ID << '\n';
    std::cout << "\tBUILD: " << FABOMATIC_BUILD << '\n';
    // namespace conf::rfid_tags
    std::cout << "RFID tags:" << '\n';
    std::cout << "\tUID_BYTE_LEN: " << +rfid_tags::UID_BYTE_LEN << '\n';
    std::cout << "\tCACHE_LEN: " << +rfid_tags::CACHE_LEN << '\n';
    // namespace conf::lcd
    std::cout << "LCD config" << '\n';
    std::cout << "\tLCD ROWS: " << +lcd::ROWS << ", COLS: " << +lcd::COLS << '\n';
    std::cout << "\tSHORT_MESSAGE_DELAY: " << std::chrono::milliseconds(lcd::SHORT_MESSAGE_DELAY).count() << "ms" << '\n';
    // namespace conf::machine
    std::cout << "General settings:" << '\n';
    std::cout << "\tDEFAULT_AUTO_LOGOFF_DELAY: " << std::chrono::hours(machine::DEFAULT_AUTO_LOGOFF_DELAY).count() << "h" << '\n';
    std::cout << "\tDEFAULT_GRACE_PERIOD: " << std::chrono::seconds(machine::DEFAULT_GRACE_PERIOD).count() << "s" << '\n';
    std::cout << "\tDELAY_BETWEEN_BEEPS: " << std::chrono::seconds(machine::DELAY_BETWEEN_BEEPS).count() << "s" << '\n';
    std::cout << "\tMAINTENANCE_BLOCK: " << machine::MAINTENANCE_BLOCK << '\n';
    std::cout << "\tLONG_TAP_DURATION: " << std::chrono::seconds(machine::LONG_TAP_DURATION).count() << "s" << '\n';
    // namespace conf::debug
    std::cout << "Debug settings:" << '\n';
    std::cout << "\tENABLE_LOGS: " << debug::ENABLE_LOGS << '\n';
    std::cout << "\tENABLE_TASK_LOGS: " << debug::ENABLE_TASK_LOGS << '\n';
    std::cout << "\tSERIAL_SPEED_BDS: " << debug::SERIAL_SPEED_BDS << '\n';
    std::cout << "\tFORCE_PORTAL: " << debug::FORCE_PORTAL << '\n';
    std::cout << "\tLOAD_EEPROM_DEFAULTS: " << debug::LOAD_EEPROM_DEFAULTS << '\n';
    // namespace conf::buzzer
    std::cout << "Buzzer settings:" << '\n';
    std::cout << "\tSTANDARD_BEEP_DURATION: " << std::chrono::milliseconds(buzzer::STANDARD_BEEP_DURATION).count() << "ms" << '\n';
    std::cout << "\tNB_BEEPS: " << buzzer::NB_BEEPS << '\n';
    // namespace conf::tasks
    std::cout << "Tasks settings:" << '\n';
    std::cout << "\tRFID_CHECK_PERIOD: " << std::chrono::milliseconds(tasks::RFID_CHECK_PERIOD).count() << "ms" << '\n';
    std::cout << "\tRFID_SELFTEST_PERIOD: " << std::chrono::seconds(tasks::RFID_SELFTEST_PERIOD).count() << "s" << '\n';
    std::cout << "\tMQTT_REFRESH_PERIOD: " << std::chrono::seconds(tasks::MQTT_REFRESH_PERIOD).count() << "s" << '\n';
    std::cout << "\tWATCHDOG_TIMEOUT: " << std::chrono::seconds(tasks::WATCHDOG_TIMEOUT).count() << "s" << '\n';
    std::cout << "\tWATCHDOG_PERIOD: " << std::chrono::seconds(tasks::WATCHDOG_PERIOD).count() << "s" << '\n';
    std::cout << "\tPORTAL_CONFIG_TIMEOUT: " << std::chrono::seconds(tasks::PORTAL_CONFIG_TIMEOUT).count() << "s" << '\n';
    std::cout << "\tMQTT_ALIVE_PERIOD: " << std::chrono::seconds(tasks::MQTT_ALIVE_PERIOD).count() << "s" << '\n';
    // namespace conf::mqtt
    std::cout << "MQTT settings:" << '\n';
    std::cout << "\tmqtt_server: " << mqtt::mqtt_server << '\n';
    std::cout << "\tmqtt_switch_topic: " << mqtt::mqtt_switch_topic << '\n';
    std::cout << "\tmqtt_switch_on_message: " << mqtt::mqtt_switch_on_message << '\n';
    std::cout << "\tmqtt_switch_off_message: " << mqtt::mqtt_switch_off_message << '\n';
    std::cout << "\ttopic: " << mqtt::topic << '\n';
    std::cout << "\tresponse_topic: " << mqtt::response_topic << '\n';
    std::cout << "\tMAX_TRIES: " << mqtt::MAX_TRIES << '\n';
    std::cout << "\tTIMEOUT_REPLY_SERVER: " << std::chrono::milliseconds(mqtt::TIMEOUT_REPLY_SERVER).count() << "ms" << '\n';
    std::cout << "\tPORT_NUMBER: " << mqtt::PORT_NUMBER << '\n';
    // Now dump all pins.hpp settings
    std::cout << "Hardware settings:" << '\n';
    std::cout << "\tLED:" << '\n';
    std::cout << "\t\tPin:" << +pins.led.pin << " (G:" << +pins.led.green_pin << ", B:" << +pins.led.blue_pin << ")" << '\n';
    std::cout << "\t\tType is neopixel:" << pins.led.is_neopixel << ", is rgb:" << pins.led.is_rgb << '\n';
    std::cout << "\t\tNeopixel config flags:" << pins.led.neopixel_config << '\n';
    std::cout << "\tMfrc522 chip:" << '\n';
    std::cout << "\t\tSPI settings: MISO: " << +pins.mfrc522.miso_pin << ","
              << " MOSI: " << +pins.mfrc522.mosi_pin << ","
              << " SCK: " << +pins.mfrc522.sck_pin << ","
              << " SDA: " << +pins.mfrc522.sda_pin << '\n';
    std::cout << "\t\tRESET pin:" << +pins.mfrc522.reset_pin << '\n';
    std::cout << "\tLCD module:" << '\n';
    std::cout << "\t\tParallel interface D0:" << +pins.lcd.d0_pin << ", D1:" << +pins.lcd.d1_pin << ", D2:" << +pins.lcd.d2_pin << ", D3:" << +pins.lcd.d3_pin << '\n';
    std::cout << "\t\tReset pin:" << +pins.lcd.rs_pin << ", Enable pin:" << +pins.lcd.en_pin << '\n';
    std::cout << "\t\tBacklight pin:" << +pins.lcd.bl_pin << " (active low:" << pins.lcd.active_low << ")" << '\n';
    std::cout << "\tRelay:" << '\n';
    std::cout << "\t\tControl pin:" << +pins.relay.ch1_pin << " (active low:" << pins.relay.active_low << ")" << '\n';
    std::cout << "\tBuzzer:" << '\n';
    std::cout << "\t\tPin:" << +pins.buzzer.pin << '\n';
    std::cout << "\tButtons:" << '\n';
    std::cout << "\t\tFactory defaults pin:" << +pins.buttons.factory_defaults_pin << '\n';
    std::cout << std::endl;
  }
References fabomatic::pins_config::lcd_config::active_low, fabomatic::pins_config::relay_config::active_low, fabomatic::pins_config::lcd_config::bl_pin, fabomatic::pins_config::led_config::blue_pin, fabomatic::pins_config::buttons, fabomatic::pins_config::buzzer, fabomatic::pins_config::relay_config::ch1_pin, fabomatic::pins_config::lcd_config::d0_pin, fabomatic::pins_config::lcd_config::d1_pin, fabomatic::pins_config::lcd_config::d2_pin, fabomatic::pins_config::lcd_config::d3_pin, fabomatic::pins_config::lcd_config::en_pin, fabomatic::pins_config::buttons_config::factory_defaults_pin, fabomatic::pins_config::led_config::green_pin, fabomatic::pins_config::led_config::is_neopixel, fabomatic::pins_config::led_config::is_rgb, fabomatic::pins_config::lcd, fabomatic::pins_config::led, fabomatic::pins_config::mfrc522, fabomatic::pins_config::mfrc522_config::miso_pin, fabomatic::pins_config::mfrc522_config::mosi_pin, fabomatic::pins_config::led_config::neopixel_config, fabomatic::pins_config::buzzer_config::pin, fabomatic::pins_config::led_config::pin, pins, fabomatic::pins_config::relay, fabomatic::pins_config::mfrc522_config::reset_pin, fabomatic::pins_config::lcd_config::rs_pin, fabomatic::pins_config::mfrc522_config::sck_pin, and fabomatic::pins_config::mfrc522_config::sda_pin.
Referenced by setup().
saveConfigCallback()
void fabomatic::saveConfigCallback ()
Definition at line 19 of file OTA.cpp.
  {
    shouldSaveConfig.store(true);
  }
References shouldSaveConfig.
Referenced by openConfigPortal().
setupOTA()
auto fabomatic::setupOTA ()
Initialization of the Arduino OTA library with settings for fabomatic.
Definition at line 138 of file OTA.cpp.
  {
    ArduinoOTA.setHostname(Board::logic.getHostname().c_str());
    ArduinoOTA.onStart([]()
                       { Board::logic.changeStatus(Status::OTAStarting); });
    ArduinoOTA.onEnd(OTAComplete);
    ArduinoOTA.onError([](ota_error_t error)
                       { Board::logic.changeStatus(Status::OTAError); });
    ArduinoOTA.setMdnsEnabled(true);
    ArduinoOTA.setRebootOnSuccess(false);
    ArduinoOTA.setTimeout(45000);
    ArduinoOTA.begin();
  }
References fabomatic::BoardLogic::changeStatus(), fabomatic::Board::logic, and OTAComplete().
Referenced by setup().
taskBlink()
void fabomatic::taskBlink ()
blink led
Definition at line 88 of file main.cpp.
  {
    Board::logic.blinkLed();
  }
References fabomatic::BoardLogic::blinkLed(), and fabomatic::Board::logic.
taskCheckRfid()
void fabomatic::taskCheckRfid ()
periodic check for new RFID card
Definition at line 82 of file main.cpp.
  {
    Board::logic.checkRfid();
  }
References fabomatic::BoardLogic::checkRfid(), and fabomatic::Board::logic.
taskConnect()
void fabomatic::taskConnect ()
Opens WiFi and server connection and updates board state accordingly.
Definition at line 42 of file main.cpp.
  {
    auto &server = Board::logic.getServer();
    if (!server.isOnline())
    {
      // connection to wifi
      Board::logic.changeStatus(Status::Connecting);
      // Try to connect
      server.connect();
      // Refresh after connection
      Board::logic.changeStatus(server.isOnline() ? Status::Connected : Status::Offline);
      if (server.isOnline())
      {
        // Briefly show to the user
        Tasks::delay(conf::lcd::SHORT_MESSAGE_DELAY);
      }
    }
    if (server.isOnline())
    {
      ESP_LOGI(TAG, "taskConnect - online, calling refreshFromServer");
      // Get machine data from the server if it is online
      Board::logic.refreshFromServer();
      if (auto &machine = Board::logic.getMachine(); !machine.isFree())
      {
        const auto response = Board::logic.getServer().inUse(
            machine.getActiveUser().card_uid,
            machine.getUsageDuration());
        if (!response)
        {
          ESP_LOGE(TAG, "taskConnect - inUse failed");
        }
      }
    }
  }
References fabomatic::BoardLogic::changeStatus(), fabomatic::FabBackend::connect(), fabomatic::Tasks::delay(), fabomatic::BoardLogic::getServer(), fabomatic::FabBackend::isOnline(), fabomatic::Board::logic, fabomatic::BoardLogic::refreshFromServer(), fabomatic::conf::lcd::SHORT_MESSAGE_DELAY, and TAG.
Referenced by setup().
taskEspWatchdog()
void fabomatic::taskEspWatchdog ()
Keep the ESP32 HW watchdog alive. If code gets stuck this will cause an automatic reset.
Definition at line 135 of file main.cpp.
  {
    static auto initialized = false;
    if (conf::tasks::WATCHDOG_TIMEOUT > 0s)
    {
      if (!initialized)
      {
        initialized = esp32::setupWatchdog(conf::tasks::WATCHDOG_TIMEOUT);
      }
      if (initialized)
      {
        if (!esp32::signalWatchdog())
        {
          ESP_LOGE(TAG, "Failure to signal watchdog");
        }
      }
    }
  }
References fabomatic::esp32::setupWatchdog(), fabomatic::esp32::signalWatchdog(), TAG, and fabomatic::conf::tasks::WATCHDOG_TIMEOUT.
taskFactoryReset()
void fabomatic::taskFactoryReset ()
Definition at line 213 of file main.cpp.
  {
    if constexpr (pins.buttons.factory_defaults_pin == NO_PIN)
    {
      return;
    }
    // Skip factory reset for this specific board because Factory Reset is soldered under the MCU with the reset pin.
    if (const auto &serial = esp32::esp_serial(); serial == "dcda0c419794")
    {
      pinMode(pins.buttons.factory_defaults_pin, INPUT); // Disable pull-up/pull-downs
      return;
    }
    pinMode(pins.buttons.factory_defaults_pin, INPUT_PULLUP);
    if (Board::logic.getRebootRequest())
    {
      Board::logic.blinkLed(255, 165, 0); // Blink orange
      ESP_LOGI(TAG, "Factory reset pending...");
      return;
    }
    if (digitalRead(pins.buttons.factory_defaults_pin) == LOW)
    {
      ESP_LOGI(TAG, "Factory reset button pressed");
      esp32::removeWatchdog();
      openConfigPortal(true, false); // Network configuration setup
    }
  }
References fabomatic::BoardLogic::blinkLed(), fabomatic::pins_config::buttons, fabomatic::esp32::esp_serial(), fabomatic::pins_config::buttons_config::factory_defaults_pin, fabomatic::Board::logic, NO_PIN, openConfigPortal(), pins, fabomatic::esp32::removeWatchdog(), and TAG.
taskIsAlive()
void fabomatic::taskIsAlive ()
Definition at line 184 of file main.cpp.
  {
    // notify the server that the machine is still alive
    auto &server = Board::logic.getServer();
    if (server.isOnline())
    {
      if (auto resp = server.alive(); !resp)
      {
        ESP_LOGE(TAG, "taskIsAlive - alive failed");
      }
    }
    if (!Board::logic.saveRfidCache())
    {
      ESP_LOGE(TAG, "taskIsAlive - saveRfidCache failed");
    }
    if (!server.saveBuffer())
    {
      ESP_LOGE(TAG, "Failure to save buffered MQTT messages");
    }
    if constexpr (conf::debug::ENABLE_LOGS)
    {
      fabomatic::esp32::showHeapStats();
    }
  }
References fabomatic::FabBackend::alive(), fabomatic::conf::debug::ENABLE_LOGS, fabomatic::BoardLogic::getServer(), fabomatic::FabBackend::isOnline(), fabomatic::Board::logic, fabomatic::FabBackend::saveBuffer(), fabomatic::esp32::showHeapStats(), and TAG.
taskLogoffCheck()
void fabomatic::taskLogoffCheck ()
periodic check if the user shall be logged off
Definition at line 121 of file main.cpp.
  {
    // auto logout after delay
    const auto &machine = Board::logic.getMachine();
    if (machine.isAutologoffExpired())
    {
      ESP_LOGI(TAG, "Auto-logging out user %s\r\n", machine.getActiveUser().holder_name.data());
      Board::logic.logout();
      Board::logic.beepFail();
    }
  }
References fabomatic::BoardLogic::beepFail(), fabomatic::BoardLogic::getMachine(), fabomatic::Board::logic, fabomatic::BoardLogic::logout(), and TAG.
taskMQTTClientLoop()
void fabomatic::taskMQTTClientLoop ()
sends the MQTT alive message
Definition at line 175 of file main.cpp.
  {
    auto &server = Board::logic.getServer();
    if (server.isOnline())
    {
      server.loop();
    }
  }
References fabomatic::BoardLogic::getServer(), fabomatic::FabBackend::isOnline(), fabomatic::Board::logic, and fabomatic::FabBackend::loop().
taskPoweroffCheck()
void fabomatic::taskPoweroffCheck ()
periodic check if the machine must be powered off
Definition at line 94 of file main.cpp.
  {
    Board::logic.checkPowerOff();
  }
References fabomatic::BoardLogic::checkPowerOff(), and fabomatic::Board::logic.
taskPoweroffWarning()
void fabomatic::taskPoweroffWarning ()
periodic check if the machine must be powered off
Definition at line 100 of file main.cpp.
  {
    if (Board::logic.getMachine().isShutdownImminent())
    {
      Board::logic.changeStatus(Status::ShuttingDown);
      Board::logic.beepFail();
      if (conf::debug::ENABLE_LOGS)
        ESP_LOGI(TAG, "Machine is about to shutdown");
    }
    if (Board::logic.getRebootRequest())
    {
      if (Board::logic.getMachine().getPowerState() == Machine::PowerState::PoweredOff)
      {
        ESP_LOGI(TAG, "Rebooting as per request");
        esp32::restart();
      }
    }
  }
References fabomatic::BoardLogic::beepFail(), fabomatic::BoardLogic::changeStatus(), fabomatic::conf::debug::ENABLE_LOGS, fabomatic::Board::logic, fabomatic::Machine::PoweredOff, fabomatic::esp32::restart(), and TAG.
taskRfidWatchdog()
void fabomatic::taskRfidWatchdog ()
checks the RFID chip status and re-init it if necessary.
Definition at line 156 of file main.cpp.
  {
    if (!Board::rfid.selfTest())
    {
      ESP_LOGE(TAG, "RFID chip failure");
      // Infinite retry until success or hw watchdog timeout
      while (!Board::rfid.rfidInit())
      {
        Board::logic.changeStatus(Status::ErrorHardware);
        Tasks::delay(conf::tasks::RFID_CHECK_PERIOD);
#ifdef DEBUG
        break;
#endif
      }
    }
  }
References fabomatic::BoardLogic::changeStatus(), fabomatic::Tasks::delay(), fabomatic::Board::logic, fabomatic::Board::rfid, fabomatic::conf::tasks::RFID_CHECK_PERIOD, and TAG.
Variable Documentation
NO_PIN
constexpr uint8_t fabomatic::NO_PIN = -1 static constexpr
Constant used to indicate the pin is not used.
Definition at line 10 of file PinsConfig.hpp.
Referenced by fabomatic::Buzzer::beepFail(), fabomatic::Buzzer::beepOk(), fabomatic::Buzzer::configure(), configure_pins_esp32(), configure_pins_esp32s3(), configure_pins_hwrev0(), configure_pins_wokwi(), configure_pins_wrover(), fabomatic::MachineConfig::hasRelay(), fabomatic::Led::init(), fabomatic::BoardLogic::initBoard(), no_duplicates(), taskFactoryReset(), and fabomatic::tests::test_machine_defaults().
pins
constexpr pins_config fabomatic::pins = configure_pins() static constexpr
Definition at line 246 of file pins.hpp.
Referenced by fabomatic::Buzzer::beepFail(), fabomatic::Buzzer::beepOk(), fabomatic::Buzzer::configure(), fabomatic::Mrfc522Driver::hardReset(), fabomatic::Led::init(), fabomatic::BoardLogic::initBoard(), fabomatic::Mrfc522Driver::Mrfc522Driver(), no_duplicates(), fabomatic::Led::outputColor(), printCompileSettings(), fabomatic::BoardLogic::reconfigure(), taskFactoryReset(), and fabomatic::tests::test_machine_defaults().
shouldSaveConfig
std::atomic<bool> fabomatic::shouldSaveConfig {false}
Definition at line 11 of file OTA.cpp.
{false};
Referenced by openConfigPortal(), and saveConfigCallback().
t_alive
const Task fabomatic::t_alive("IsAlive", conf::tasks::MQTT_ALIVE_PERIOD, &taskIsAlive, Board::scheduler, true, conf::tasks::MQTT_ALIVE_PERIOD) ("IsAlive" , conf::tasks::MQTT_ALIVE_PERIOD , & taskIsAlive, Board::scheduler , true , conf::tasks::MQTT_ALIVE_PERIOD)
t_led
const Task fabomatic::t_led("LED", 1s, &taskBlink, Board::scheduler, true) ("LED" , 1s , & taskBlink, Board::scheduler , true)
t_log
const Task fabomatic::t_log("Logoff", 1s, &taskLogoffCheck, Board::scheduler, true) ("Logoff" , 1s , & taskLogoffCheck, Board::scheduler , true)
t_mqtt
const Task fabomatic::t_mqtt("MQTT client loop", 1s, &taskMQTTClientLoop, Board::scheduler, true) ("MQTT client loop" , 1s , & taskMQTTClientLoop, Board::scheduler , true)
t_network
const Task fabomatic::t_network("Wifi/MQTT", conf::tasks::MQTT_REFRESH_PERIOD, &taskConnect, Board::scheduler, true, conf::tasks::MQTT_REFRESH_PERIOD) ("Wifi/MQTT" , conf::tasks::MQTT_REFRESH_PERIOD , & taskConnect, Board::scheduler , true , conf::tasks::MQTT_REFRESH_PERIOD)
t_powoff
const Task fabomatic::t_powoff("Poweroff", 1s, &taskPoweroffCheck, Board::scheduler, true) ("Poweroff" , 1s , & taskPoweroffCheck, Board::scheduler , true)
t_rfid
const Task fabomatic::t_rfid("RFIDChip", conf::tasks::RFID_CHECK_PERIOD, &taskCheckRfid, Board::scheduler, true) ("RFIDChip" , conf::tasks::RFID_CHECK_PERIOD , & taskCheckRfid, Board::scheduler , true)
t_rst
const Task fabomatic::t_rst("FactoryReset", 500ms, &taskFactoryReset, Board::scheduler, pins.buttons.factory_defaults_pin !=NO_PIN) ("FactoryReset" , 500ms , & taskFactoryReset, Board::scheduler , pins.buttons.factory_defaults_pin ! = NO_PIN)
t_test
const Task fabomatic::t_test("Selftest", conf::tasks::RFID_SELFTEST_PERIOD, &taskRfidWatchdog, Board::scheduler, true) ("Selftest" , conf::tasks::RFID_SELFTEST_PERIOD , & taskRfidWatchdog, Board::scheduler , true)
t_warn
const Task fabomatic::t_warn("PoweroffWarning", conf::machine::DELAY_BETWEEN_BEEPS, &taskPoweroffWarning, Board::scheduler, true) ("PoweroffWarning" , conf::machine::DELAY_BETWEEN_BEEPS , & taskPoweroffWarning, Board::scheduler , true)
t_wdg
Task fabomatic::t_wdg("Watchdog", conf::tasks::WATCHDOG_PERIOD, &taskEspWatchdog, Board::scheduler, false) ("Watchdog" , conf::tasks::WATCHDOG_PERIOD , & taskEspWatchdog, Board::scheduler , false)
Referenced by setup().