Fab-O-Matic: fabomatic::MachineConfig Struct Reference
fabomatic::MachineConfig Struct Reference
#include <MachineConfig.hpp>
Public Member Functions
MachineConfig (MachineID id, MachineType type, const std::string &name, const pins_config::relay_config &relay, const std::string &topic, std::chrono::seconds autologoff, std::chrono::seconds grace_period)
auto toString () const -> const std::string
auto hasRelay () const -> bool
Indicates if the machine is controller by hard-wired relay.
auto hasMqttSwitch () const -> bool
Indicates if the machine is controller by MQTT switch (Shelly)
MachineConfig ()=delete
MachineConfig (const MachineConfig &)=default
MachineConfig & operator= (const MachineConfig &x)=default
MachineConfig (MachineConfig &&)=delete
MachineConfig & operator= (MachineConfig &&)=delete
Public Attributes
MachineID machine_id {0}
MachineType machine_type {MachineType::Invalid}
std::string machine_name {""}
const pins_config::relay_config & relay_config
const std::string mqtt_switch_topic {""}
std::chrono::seconds autologoff {conf::machine::DEFAULT_AUTO_LOGOFF_DELAY}
Time after which the active user on the machine shall be logged-off.
std::chrono::seconds grace_period
Time after which the active user on the machine shall be logged-off.
Detailed Description
Definition at line 14 of file MachineConfig.hpp.
Constructor & Destructor Documentation
MachineConfig() [1/4]
fabomatic::MachineConfig::MachineConfig (MachineID id, MachineType type, const std::string & name, const pins_config::relay_config & relay, const std::string & topic, std::chrono::seconds autologoff, std::chrono::seconds grace_period) inline
Definition at line 28 of file MachineConfig.hpp.
                                                 : machine_id(id), machine_type(type),
                                                       machine_name(name),
                                                       relay_config{relay},
                                                       mqtt_switch_topic(topic),
                                                       autologoff(autologoff),
                                                       grace_period{grace_period} {};
MachineConfig() [2/4]
fabomatic::MachineConfig::MachineConfig () delete
MachineConfig() [3/4]
fabomatic::MachineConfig::MachineConfig (const MachineConfig &) default
MachineConfig() [4/4]
fabomatic::MachineConfig::MachineConfig (MachineConfig &&) delete
Member Function Documentation
hasMqttSwitch()
auto fabomatic::MachineConfig::hasMqttSwitch () const -> bool
Indicates if the machine is controller by MQTT switch (Shelly)
Definition at line 28 of file MachineConfig.cpp.
  {
    return !mqtt_switch_topic.empty();
  }
References mqtt_switch_topic.
Referenced by toString().
hasRelay()
auto fabomatic::MachineConfig::hasRelay () const -> bool
Indicates if the machine is controller by hard-wired relay.
Definition at line 23 of file MachineConfig.cpp.
  {
    return relay_config.ch1_pin != NO_PIN;
  }
References fabomatic::pins_config::relay_config::ch1_pin, fabomatic::NO_PIN, and relay_config.
Referenced by toString().
operator=() [1/2]
MachineConfig & fabomatic::MachineConfig::operator= (const MachineConfig & x) default
operator=() [2/2]
MachineConfig & fabomatic::MachineConfig::operator= (MachineConfig &&) delete
toString()
auto fabomatic::MachineConfig::toString () const -> const std::string
Definition at line 6 of file MachineConfig.cpp.
  {
    std::stringstream sstream;
    sstream << "MachineConfig (ID:" << machine_id.id;
    sstream << ", Name:" << machine_name;
    sstream << ", Type:" << static_cast<int>(machine_type);
    sstream << ", AutologoffDelay (min):" << std::chrono::duration_cast<std::chrono::minutes>(autologoff).count();
    sstream << ", MQTT Switch topic:" << mqtt_switch_topic;
    sstream << ", HasRelay:" << hasRelay();
    sstream << ", HasMqttSwitch:" << hasMqttSwitch();
    sstream << ", GracePeriod (s):" << std::chrono::duration_cast<std::chrono::seconds>(grace_period).count();
    sstream << "))";
    return sstream.str();
  }
References autologoff, grace_period, hasMqttSwitch(), hasRelay(), MachineID::id, machine_id, machine_name, machine_type, and mqtt_switch_topic.
Member Data Documentation
autologoff
std::chrono::seconds fabomatic::MachineConfig::autologoff {conf::machine::DEFAULT_AUTO_LOGOFF_DELAY}
Time after which the active user on the machine shall be logged-off.
Definition at line 23 of file MachineConfig.hpp.
{conf::machine::DEFAULT_AUTO_LOGOFF_DELAY};
Referenced by toString().
grace_period
std::chrono::seconds fabomatic::MachineConfig::grace_period
Time after which the active user on the machine shall be logged-off.
Definition at line 26 of file MachineConfig.hpp.
Referenced by toString().
machine_id
MachineID fabomatic::MachineConfig::machine_id {0}
Definition at line 16 of file MachineConfig.hpp.
{0};
Referenced by toString().
machine_name
std::string fabomatic::MachineConfig::machine_name {""}
Definition at line 18 of file MachineConfig.hpp.
{""};
Referenced by toString().
machine_type
MachineType fabomatic::MachineConfig::machine_type {MachineType::Invalid}
Definition at line 17 of file MachineConfig.hpp.
{MachineType::Invalid};
Referenced by toString().
mqtt_switch_topic
const std::string fabomatic::MachineConfig::mqtt_switch_topic {""}
Definition at line 20 of file MachineConfig.hpp.
{""};
Referenced by hasMqttSwitch(), and toString().
relay_config
const pins_config::relay_config& fabomatic::MachineConfig::relay_config
Definition at line 19 of file MachineConfig.hpp.
Referenced by hasRelay().
The documentation for this struct was generated from the following files:
MachineConfig.hpp
MachineConfig.cpp