Fab-O-Matic: test_logic.cpp File Reference
test_logic.cpp File Reference
#include <atomic>
#include <chrono>
#include <functional>
#include <pthread.h>
#include <string>
#include <vector>
#include "BoardLogic.hpp"
#include "FabBackend.hpp"
#include "LCDWrapper.hpp"
#include "RFIDWrapper.hpp"
#include "SavedConfig.hpp"
#include "conf.hpp"
#include "mock/MockMQTTBroker.hpp"
#include "mock/MockMrfc522.hpp"
#include "test_common.h"
#include <Arduino.h>
#include <unity.h>
#include "LiquidCrystal.h"
Namespaces
namespace fabomatic
namespace fabomatic::tests
Typedefs
using BoardLogic = fabomatic::BoardLogic
Functions
constexpr fabomatic::card::uid_t get_test_uid (size_t idx)
void fabomatic::tests::test_machine_defaults ()
void fabomatic::tests::test_simple_methods ()
void fabomatic::tests::test_whitelist_no_network ()
void fabomatic::tests::test_one_user_at_a_time ()
void fabomatic::tests::test_user_autologoff ()
void fabomatic::tests::test_machine_maintenance ()
void fabomatic::tests::test_machine_allowed ()
void fabomatic::tests::test_messages_buffered ()
void tearDown (void)
void setUp (void)
void setup ()
void loop ()
Variables
static const char * TAG3 = "test_logic"
fabomatic::RFIDWrapper< fabomatic::MockMrfc522 > rfid
fabomatic::LCDWrapper lcd {fabomatic::pins.lcd}
fabomatic::BoardLogic logic
Typedef Documentation
BoardLogic
using BoardLogic = fabomatic::BoardLogic
Definition at line 31 of file test_logic.cpp.
Function Documentation
get_test_uid()
constexpr fabomatic::card::uid_t get_test_uid (size_t idx) constexpr
Definition at line 33 of file test_logic.cpp.
{
  auto [card_uid, level, name] = fabomatic::tests::test_whitelist[idx];
  return card_uid;
}
References fabomatic::tests::test_whitelist.
Referenced by fabomatic::tests::test_machine_allowed(), fabomatic::tests::test_machine_maintenance(), fabomatic::tests::test_messages_buffered(), fabomatic::tests::test_one_user_at_a_time(), fabomatic::tests::test_user_autologoff(), and fabomatic::tests::test_whitelist_no_network().
loop()
void loop ()
Definition at line 369 of file test_logic.cpp.
{
}
setup()
void setup ()
Definition at line 349 of file test_logic.cpp.
{
  delay(1000);
  auto config = fabomatic::SavedConfig::LoadFromEEPROM();
  UNITY_BEGIN();
  RUN_TEST(fabomatic::tests::test_machine_defaults);
  RUN_TEST(fabomatic::tests::test_simple_methods);
  RUN_TEST(fabomatic::tests::test_machine_allowed);
  RUN_TEST(fabomatic::tests::test_machine_maintenance);
  RUN_TEST(fabomatic::tests::test_whitelist_no_network);
  RUN_TEST(fabomatic::tests::test_one_user_at_a_time);
  RUN_TEST(fabomatic::tests::test_user_autologoff);
  RUN_TEST(fabomatic::tests::test_messages_buffered);
  UNITY_END(); // stop unit testing
  if (config.has_value())
  {
    config.value().SaveToEEPROM();
  }
};
References fabomatic::SavedConfig::LoadFromEEPROM(), fabomatic::tests::test_machine_allowed(), fabomatic::tests::test_machine_defaults(), fabomatic::tests::test_machine_maintenance(), fabomatic::tests::test_messages_buffered(), fabomatic::tests::test_one_user_at_a_time(), fabomatic::tests::test_simple_methods(), fabomatic::tests::test_user_autologoff(), and fabomatic::tests::test_whitelist_no_network().
setUp()
void setUp (void)
Definition at line 334 of file test_logic.cpp.
{
  TEST_ASSERT_TRUE_MESSAGE(fabomatic::SavedConfig::DefaultConfig().SaveToEEPROM(), "Default config save failed");
  TEST_ASSERT_TRUE_MESSAGE(logic.configure(rfid, lcd), "BoardLogic configure failed");
  TEST_ASSERT_TRUE_MESSAGE(logic.initBoard(), "BoardLogic init failed");
  logic.setWhitelist(fabomatic::tests::test_whitelist);
  // Disable MQTT for tests
  if (auto server_config = fabomatic::SavedConfig::LoadFromEEPROM(); server_config.has_value())
  {
    auto conf = server_config.value();
    conf.mqtt_server.assign("INVALID_SERVER");
    logic.getServer().configure(conf);
  }
};
References fabomatic::BoardLogic::configure(), fabomatic::SavedConfig::DefaultConfig(), fabomatic::BoardLogic::getServer(), fabomatic::BoardLogic::initBoard(), lcd, fabomatic::SavedConfig::LoadFromEEPROM(), logic, rfid, fabomatic::BoardLogic::setWhitelist(), and fabomatic::tests::test_whitelist.
tearDown()
void tearDown (void)
Definition at line 332 of file test_logic.cpp.
{};
Variable Documentation
lcd
fabomatic::LCDWrapper lcd {fabomatic::pins.lcd}
Definition at line 28 of file test_logic.cpp.
{fabomatic::pins.lcd};
Referenced by fabomatic::LCDWrapper::begin(), setup(), setUp(), and fabomatic::LCDWrapper::update().
logic
fabomatic::BoardLogic logic
Definition at line 29 of file test_logic.cpp.
Referenced by setup(), and setUp().
rfid
fabomatic::RFIDWrapper<fabomatic::MockMrfc522> rfid
Definition at line 27 of file test_logic.cpp.
Referenced by setup(), and setUp().
TAG3
const char* TAG3 = "test_logic" static
Definition at line 25 of file test_logic.cpp.
Referenced by fabomatic::tests::test_fabserver_calls(), fabomatic::tests::test_normal_use(), fabomatic::tests::test_taskConnect(), fabomatic::tests::test_taskRfidWatchdog(), fabomatic::tests::test_taskVarious(), and fabomatic::tests::threadMQTTServer().