Fab-O-Matic: test_mqtt.cpp File Reference
test_mqtt.cpp File Reference
#include <atomic>
#include <chrono>
#include <functional>
#include <pthread.h>
#include <string>
#include <vector>
#include "BoardLogic.hpp"
#include "Espressif.hpp"
#include "FabBackend.hpp"
#include "LCDWrapper.hpp"
#include "RFIDWrapper.hpp"
#include "SavedConfig.hpp"
#include "Tasks.hpp"
#include "conf.hpp"
#include "mock/MockMQTTBroker.hpp"
#include "mock/MockMrfc522.hpp"
#include <Arduino.h>
#include <unity.h>
#include "LiquidCrystal.h"
Namespaces
namespace fabomatic
namespace fabomatic::tests
Functions
void * fabomatic::tests::threadMQTTServer (void *arg)
void fabomatic::tests::test_create_buffered_messages ()
void fabomatic::tests::test_check_transmission ()
void fabomatic::tests::test_start_broker ()
void fabomatic::tests::test_stop_broker ()
void fabomatic::tests::test_fabserver_calls ()
void fabomatic::tests::test_taskConnect ()
Opens WiFi and server connection and updates board state accordingly.
void fabomatic::tests::test_taskCheckRfid ()
periodic check for new RFID card
void fabomatic::tests::test_taskVarious ()
blink led
void fabomatic::tests::test_taskEspWatchdog ()
Keep the ESP32 HW watchdog alive. If code gets stuck this will cause an automatic reset.
void fabomatic::tests::test_taskRfidWatchdog ()
checks the RFID chip status and re-init it if necessary.
void fabomatic::tests::test_taskMQTTAlive ()
sends the MQTT alive message
void fabomatic::tests::test_normal_use ()
void tearDown (void)
void setUp (void)
void setup ()
void loop ()
Variables
pthread_t thread_mqtt_broker
pthread_attr_t attr_mqtt_broker
static const char * TAG3 = "test_mqtt"
fabomatic::RFIDWrapper< fabomatic::MockMrfc522 > fabomatic::tests::rfid
fabomatic::LCDWrapper< LiquidCrystal > fabomatic::tests::lcd {fabomatic::pins.lcd}
fabomatic::BoardLogic fabomatic::tests::logic
fabomatic::MockMQTTBroker fabomatic::tests::broker
fabomatic::Tasks::Scheduler fabomatic::tests::test_scheduler
std::atomic< bool > fabomatic::tests::exit_request {false}
auto fabomatic::tests::t1 = Tasks::Task("taskConnect", 15s, &test_taskConnect, test_scheduler)
auto fabomatic::tests::t2 = Tasks::Task("taskCheckRfid", 50ms, &test_taskCheckRfid, test_scheduler)
auto fabomatic::tests::t3 = Tasks::Task("taskVarious", 1s, &test_taskVarious, test_scheduler)
auto fabomatic::tests::t4 = Tasks::Task("taskEspWatchdog", 5s, &test_taskEspWatchdog, test_scheduler)
auto fabomatic::tests::t5 = Tasks::Task("taskRfidWatchdog", 30s, &test_taskRfidWatchdog, test_scheduler)
auto fabomatic::tests::t6 = Tasks::Task("taskMQTTAlive", 30s, &test_taskMQTTAlive, test_scheduler)
Function Documentation
loop()
void loop ()
Definition at line 380 of file test_mqtt.cpp.
{
}
setup()
void setup ()
Definition at line 357 of file test_mqtt.cpp.
{
  delay(1000);
  // Save original config
  auto original = fabomatic::SavedConfig::LoadFromEEPROM();
  UNITY_BEGIN();
  RUN_TEST(fabomatic::tests::test_create_buffered_messages);
  RUN_TEST(fabomatic::tests::test_start_broker);
  RUN_TEST(fabomatic::tests::test_check_transmission);
  RUN_TEST(fabomatic::tests::test_fabserver_calls);
  RUN_TEST(fabomatic::tests::test_normal_use);
  RUN_TEST(fabomatic::tests::test_stop_broker);
  UNITY_END(); // stop unit testing
  // Restore original config
  if (original.has_value())
  {
    original.value().SaveToEEPROM();
  }
};
References fabomatic::SavedConfig::LoadFromEEPROM(), fabomatic::SavedConfig::SaveToEEPROM(), fabomatic::tests::test_check_transmission(), fabomatic::tests::test_create_buffered_messages(), fabomatic::tests::test_fabserver_calls(), fabomatic::tests::test_normal_use(), fabomatic::tests::test_start_broker(), and fabomatic::tests::test_stop_broker().
setUp()
void setUp (void)
Definition at line 351 of file test_mqtt.cpp.
{
  TEST_ASSERT_TRUE_MESSAGE(fabomatic::tests::logic.configure(fabomatic::tests::rfid, fabomatic::tests::lcd), "BoardLogic configure failed");
  TEST_ASSERT_TRUE_MESSAGE(fabomatic::tests::logic.initBoard(), "BoardLogic init failed");
};
References fabomatic::tests::lcd, fabomatic::tests::logic, and fabomatic::tests::rfid.
tearDown()
void tearDown (void)
Definition at line 349 of file test_mqtt.cpp.
{};
Variable Documentation
attr_mqtt_broker
pthread_attr_t attr_mqtt_broker
Definition at line 25 of file test_mqtt.cpp.
Referenced by fabomatic::tests::test_start_broker().
TAG3
const char* TAG3 = "test_mqtt" static
Definition at line 27 of file test_mqtt.cpp.
thread_mqtt_broker
pthread_t thread_mqtt_broker
Definition at line 24 of file test_mqtt.cpp.
Referenced by fabomatic::tests::test_start_broker(), and fabomatic::tests::test_stop_broker().