Fab-O-Matic: test_tasks.cpp File Reference
test_tasks.cpp File Reference
#include <chrono>
#include <string>
#include <functional>
#include <Arduino.h>
#include <unity.h>
#include "Tasks.hpp"
#include "Logging.hpp"
#include "Espressif.hpp"
Namespaces
namespace fabomatic
namespace fabomatic::tests
Macros
#define UNITY_INCLUDE_PRINT_FORMATTED
Typedefs
using fabomatic::tests::Task = fabomatic::Tasks::Task
using fabomatic::tests::Scheduler = fabomatic::Tasks::Scheduler
Functions
void fabomatic::tests::delete_tasks (void)
void fabomatic::tests::tearDown (void)
void fabomatic::tests::create_tasks (Scheduler &scheduler, std::chrono::milliseconds period)
void fabomatic::tests::run_for_duration (std::function< void()> callback, std::chrono::milliseconds duration)
void fabomatic::tests::setUp (void)
void fabomatic::tests::test_execute_runs_all_tasks (void)
void fabomatic::tests::test_stop_start_tasks (void)
void fabomatic::tests::test_esp32 ()
void setup ()
void loop ()
Variables
constexpr int fabomatic::tests::NB_TASKS = 100
bool fabomatic::tests::tasks_status [NB_TASKS] {false}
Task * fabomatic::tests::tasks [NB_TASKS] {nullptr}
size_t fabomatic::tests::task_counter {0}
Scheduler fabomatic::tests::scheduler
auto fabomatic::tests::execute
Macro Definition Documentation
UNITY_INCLUDE_PRINT_FORMATTED
#define UNITY_INCLUDE_PRINT_FORMATTED
Definition at line 6 of file test_tasks.cpp.
Function Documentation
loop()
void loop ()
Definition at line 154 of file test_tasks.cpp.
{
}
setup()
void setup ()
Definition at line 144 of file test_tasks.cpp.
{
  delay(1000);
  UNITY_BEGIN();
  RUN_TEST(fabomatic::tests::test_execute_runs_all_tasks);
  RUN_TEST(fabomatic::tests::test_stop_start_tasks);
  RUN_TEST(fabomatic::tests::test_esp32);
  UNITY_END(); // stop unit testing
}
References fabomatic::tests::test_esp32(), fabomatic::tests::test_execute_runs_all_tasks(), and fabomatic::tests::test_stop_start_tasks().