Fab-O-Matic: test_savedconfig.cpp File Reference
test_savedconfig.cpp File Reference
#include <chrono>
#include <string>
#include <functional>
#include <algorithm>
#include <Arduino.h>
#include <unity.h>
#include "SavedConfig.hpp"
#include <AuthProvider.hpp>
#include <FabBackend.hpp>
#include "BoardLogic.hpp"
#include "BufferedMsg.hpp"
Namespaces
namespace fabomatic
namespace fabomatic::tests
Functions
void fabomatic::tests::test_defaults (void)
void fabomatic::tests::test_changes (void)
void fabomatic::tests::test_rfid_cache ()
void fabomatic::tests::test_magic_number ()
bool fabomatic::tests::test_deserialization (Buffer &buff)
void fabomatic::tests::test_buffered_msg ()
void tearDown (void)
void setUp (void)
void setup ()
void loop ()
Variables
static const char * TAG3 = "test_logic"
SavedConfig fabomatic::tests::original
Function Documentation
loop()
void loop ()
Definition at line 338 of file test_savedconfig.cpp.
{
}
setup()
void setup ()
Definition at line 318 of file test_savedconfig.cpp.
{
  delay(1000);
  auto original = fabomatic::SavedConfig::LoadFromEEPROM();
  UNITY_BEGIN();
  RUN_TEST(fabomatic::tests::test_defaults);
  RUN_TEST(fabomatic::tests::test_changes);
  RUN_TEST(fabomatic::tests::test_magic_number);
  RUN_TEST(fabomatic::tests::test_rfid_cache);
  RUN_TEST(fabomatic::tests::test_buffered_msg);
  if (original.has_value())
  {
    original.value().SaveToEEPROM();
  }
  UNITY_END(); // stop unit testing
}
References fabomatic::SavedConfig::LoadFromEEPROM(), fabomatic::SavedConfig::SaveToEEPROM(), fabomatic::tests::test_buffered_msg(), fabomatic::tests::test_changes(), fabomatic::tests::test_defaults(), fabomatic::tests::test_magic_number(), and fabomatic::tests::test_rfid_cache().
setUp()
void setUp (void)
Definition at line 313 of file test_savedconfig.cpp.
{
  // set stuff up here
}
tearDown()
void tearDown (void)
Definition at line 308 of file test_savedconfig.cpp.
{
  // clean stuff up here
}
Variable Documentation
TAG3
const char* TAG3 = "test_logic" static
Definition at line 16 of file test_savedconfig.cpp.